[
{"message":"file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237\n        throw new Error(y, { cause: u });\n              ^\n","level":"FATAL","type":"PLAYGROUND","test":"jspi-boot","plugin":"feedlist","details":"file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237\n        throw new Error(y, { cause: u });\n              ^\n","log":"/tmp/tmp.2SaBAuPI4V"}
,
{"message":"Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>fluentchatbasic</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href=\"https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/\">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /wordpress/wp-includes/functions.php on line 6121","level":"NOTICE","type":"PHP","test":"jspi-boot","plugin":"feedlist","details":"[20-Apr-2025 13:07:17 UTC] PHP Notice:  Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>fluentchatbasic</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href=\"https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/\">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /wordpress/wp-includes/functions.php on line 6121","log":"/logs/plugins/f/feedlist/error.json"}
,
{"message":"Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>fluentchatbasic</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href=\"https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/\">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /wordpress/wp-includes/functions.php on line 6121","level":"NOTICE","type":"PHP","test":"jspi-boot","plugin":"feedlist","details":"[20-Apr-2025 13:07:26 UTC] PHP Notice:  Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>fluentchatbasic</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href=\"https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/\">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /wordpress/wp-includes/functions.php on line 6121","log":"/logs/plugins/f/feedlist/error.json"}
,
{"message":"Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>fluentchatbasic</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href=\"https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/\">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /wordpress/wp-includes/functions.php on line 6121","level":"NOTICE","type":"PHP","test":"jspi-boot","plugin":"feedlist","details":"[20-Apr-2025 13:07:37 UTC] PHP Notice:  Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>fluentchatbasic</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href=\"https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/\">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /wordpress/wp-includes/functions.php on line 6121","log":"/logs/plugins/f/feedlist/error.json"}
,
{"message":"Uncaught Error: Call to undefined function mysql_query() in /wordpress/wp-content/plugins/follow-my-blog-post/index.php:56","level":"FATAL","type":"PHP","test":"jspi-boot","plugin":"feedlist","details":"[20-Apr-2025 13:08:17 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_query() in /wordpress/wp-content/plugins/follow-my-blog-post/index.php:56\nStack trace:\n#0 /wordpress/wp-includes/class-wp-hook.php(324): ww_fp_install(false)\n#1 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#2 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#3 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_follow...', false)\n#4 /internal/eval.php(20): activate_plugin('follow-my-blog-...')\n#5 {main}\n  thrown in /wordpress/wp-content/plugins/follow-my-blog-post/index.php on line 56","log":"/logs/plugins/f/feedlist/error.json"}
,
{"message":"Uncaught Error: Call to undefined function mysql_query() in /wordpress/wp-content/plugins/follow-my-blog-post/index.php:56","level":"FATAL","type":"PHP","test":"jspi-boot","plugin":"feedlist","details":"[20-Apr-2025 13:08:25 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_query() in /wordpress/wp-content/plugins/follow-my-blog-post/index.php:56\nStack trace:\n#0 /wordpress/wp-includes/class-wp-hook.php(324): ww_fp_install(false)\n#1 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#2 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#3 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_follow...', false)\n#4 /internal/eval.php(20): activate_plugin('follow-my-blog-...')\n#5 {main}\n  thrown in /wordpress/wp-content/plugins/follow-my-blog-post/index.php on line 56","log":"/logs/plugins/f/feedlist/error.json"}
,
{"message":"Uncaught Error: Call to undefined function mysql_query() in /wordpress/wp-content/plugins/follow-my-blog-post/index.php:56","level":"FATAL","type":"PHP","test":"jspi-boot","plugin":"feedlist","details":"[20-Apr-2025 13:08:33 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_query() in /wordpress/wp-content/plugins/follow-my-blog-post/index.php:56\nStack trace:\n#0 /wordpress/wp-includes/class-wp-hook.php(324): ww_fp_install(false)\n#1 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#2 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#3 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_follow...', false)\n#4 /internal/eval.php(20): activate_plugin('follow-my-blog-...')\n#5 {main}\n  thrown in /wordpress/wp-content/plugins/follow-my-blog-post/index.php on line 56","log":"/logs/plugins/f/feedlist/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: oml_facto_log.","level":"FATAL","type":"SQL","test":"jspi-boot","plugin":"feedlist","details":"[20-Apr-2025 13:09:46 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>\r\n    \t\t\t\t\tALTER TABLE `oml_facto_log`\r\n                        ADD COLUMN order_id INT</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: oml_facto_log, order_id, int</li>\n<li>Executing: ALTER TABLE oml_facto_log\r\n                        ADD COLUMN order_id integer | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: oml_facto_log.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/facto-facturacioacuten-electroacutenica/factofacturacionelectronica_setup.php(182): WP_SQLite_DB->query('\\r\\n    \\t\\t\\t\\t\\tALTE...')\n#2 /wordpress/wp-includes/class-wp-hook.php(324): facto_fe_setup(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_facto-...', false)\n#6 /internal/eval.php(20): activate_plugin('facto-facturaci...')\n#7 {main}</pre>\n for query \r\n    \t\t\t\t\tALTER TABLE `oml_facto_log`\r\n                        ADD COLUMN order_id INT made by activate_plugin, do_action('activate_facto-facturacioacuten-electroacutenica/factofacturacionelectronica.php'), WP_Hook->do_action, WP_Hook->apply_filters, facto_fe_setup, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/f/feedlist/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: oml_facto_log.","level":"FATAL","type":"SQL","test":"jspi-boot","plugin":"feedlist","details":"[20-Apr-2025 13:09:46 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE `oml_facto_log`\r\n                        CHANGE COLUMN fecha fecha DATETIME</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: oml_facto_log, fecha, datetime</li>\n<li>Executing: DROP TRIGGER IF EXISTS &quot;__oml_facto_log_fecha_on_update__&quot; | (no parameters)</li>\n<li>Executing: SELECT sql FROM sqlite_master WHERE type=&quot;table&quot; AND name=:table | (no parameters)</li>\n<li>Executing: SELECT * FROM pragma_index_list(&quot;oml_facto_log&quot;) as l; | (no parameters)</li>\n<li>Executing: CREATE TABLE `_tmp__oml_facto_log_23760613` as SELECT * FROM `oml_facto_log` | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: oml_facto_log.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/facto-facturacioacuten-electroacutenica/factofacturacionelectronica_setup.php(186): WP_SQLite_DB->query('ALTER TABLE `om...')\n#2 /wordpress/wp-includes/class-wp-hook.php(324): facto_fe_setup(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_facto-...', false)\n#6 /internal/eval.php(20): activate_plugin('facto-facturaci...')\n#7 {main}</pre>\n for query ALTER TABLE `oml_facto_log`\r\n                        CHANGE COLUMN fecha fecha DATETIME made by activate_plugin, do_action('activate_facto-facturacioacuten-electroacutenica/factofacturacionelectronica.php'), WP_Hook->do_action, WP_Hook->apply_filters, facto_fe_setup, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/f/feedlist/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: oml_facto_log.","level":"FATAL","type":"SQL","test":"jspi-boot","plugin":"feedlist","details":"[20-Apr-2025 13:09:55 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>\r\n    \t\t\t\t\tALTER TABLE `oml_facto_log`\r\n                        ADD COLUMN order_id INT</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: oml_facto_log, order_id, int</li>\n<li>Executing: ALTER TABLE oml_facto_log\r\n                        ADD COLUMN order_id integer | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: oml_facto_log.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/facto-facturacioacuten-electroacutenica/factofacturacionelectronica_setup.php(182): WP_SQLite_DB->query('\\r\\n    \\t\\t\\t\\t\\tALTE...')\n#2 /wordpress/wp-includes/class-wp-hook.php(324): facto_fe_setup(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_facto-...', false)\n#6 /internal/eval.php(20): activate_plugin('facto-facturaci...')\n#7 {main}</pre>\n for query \r\n    \t\t\t\t\tALTER TABLE `oml_facto_log`\r\n                        ADD COLUMN order_id INT made by activate_plugin, do_action('activate_facto-facturacioacuten-electroacutenica/factofacturacionelectronica.php'), WP_Hook->do_action, WP_Hook->apply_filters, facto_fe_setup, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/f/feedlist/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: oml_facto_log.","level":"FATAL","type":"SQL","test":"jspi-boot","plugin":"feedlist","details":"[20-Apr-2025 13:09:55 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE `oml_facto_log`\r\n                        CHANGE COLUMN fecha fecha DATETIME</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: oml_facto_log, fecha, datetime</li>\n<li>Executing: DROP TRIGGER IF EXISTS &quot;__oml_facto_log_fecha_on_update__&quot; | (no parameters)</li>\n<li>Executing: SELECT sql FROM sqlite_master WHERE type=&quot;table&quot; AND name=:table | (no parameters)</li>\n<li>Executing: SELECT * FROM pragma_index_list(&quot;oml_facto_log&quot;) as l; | (no parameters)</li>\n<li>Executing: CREATE TABLE `_tmp__oml_facto_log_44882428` as SELECT * FROM `oml_facto_log` | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: oml_facto_log.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/facto-facturacioacuten-electroacutenica/factofacturacionelectronica_setup.php(186): WP_SQLite_DB->query('ALTER TABLE `om...')\n#2 /wordpress/wp-includes/class-wp-hook.php(324): facto_fe_setup(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_facto-...', false)\n#6 /internal/eval.php(20): activate_plugin('facto-facturaci...')\n#7 {main}</pre>\n for query ALTER TABLE `oml_facto_log`\r\n                        CHANGE COLUMN fecha fecha DATETIME made by activate_plugin, do_action('activate_facto-facturacioacuten-electroacutenica/factofacturacionelectronica.php'), WP_Hook->do_action, WP_Hook->apply_filters, facto_fe_setup, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/f/feedlist/error.json"}
,
{"message":"Undefined variable $table_prefix in /wordpress/wp-content/plugins/forgetfail/forgetfail.php on line 10","level":"WARNING","type":"PHP","test":"jspi-boot","plugin":"feedlist","details":"[20-Apr-2025 13:11:30 UTC] PHP Warning:  Undefined variable $table_prefix in /wordpress/wp-content/plugins/forgetfail/forgetfail.php on line 10","log":"/logs/plugins/f/feedlist/error.json"}
,
{"message":"Undefined variable $table_prefix in /wordpress/wp-content/plugins/forgetfail/forgetfail.php on line 10","level":"WARNING","type":"PHP","test":"jspi-boot","plugin":"feedlist","details":"[20-Apr-2025 13:11:40 UTC] PHP Warning:  Undefined variable $table_prefix in /wordpress/wp-content/plugins/forgetfail/forgetfail.php on line 10","log":"/logs/plugins/f/feedlist/error.json"}
,
{"message":"Undefined variable $table_prefix in /wordpress/wp-content/plugins/forgetfail/forgetfail.php on line 10","level":"WARNING","type":"PHP","test":"jspi-boot","plugin":"feedlist","details":"[20-Apr-2025 13:11:49 UTC] PHP Warning:  Undefined variable $table_prefix in /wordpress/wp-content/plugins/forgetfail/forgetfail.php on line 10\n\n    at Object.onBind (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async V (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:64:10)\n    at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {\n  [cause]: Error: Error when executing the blueprint step #1 ({\"step\":\"installPlugin\",\"pluginData\":{\"resource\":\"wordpress.org/plugins\",\"slug\":\"feedlist\"},\"options\":{\"activate\":true}}) : Plugin /wordpress/wp-content/plugins/feedlist could not be activated – WordPress exited with no error. Sometimes, when $_SERVER or site options are not configured correctly, WordPress exits early with a 301 redirect. Inspect the \"debug\" logs in the console for more details.\n      at Object.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12449:19)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async ms (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12552:3)\n      ... 2 lines matching cause stack trace ...\n      at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {\n    [cause]: Error: Plugin /wordpress/wp-content/plugins/feedlist could not be activated – WordPress exited with no error. Sometimes, when $_SERVER or site options are not configured correctly, WordPress exits early with a 301 redirect. Inspect the \"debug\" logs in the console for more details.\n        at wr (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:119:51)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Object.gt [as installPlugin] (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:974:42)\n        at async g (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12517:30)\n        at async Object.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12446:23)\n        at async ms (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12552:3)\n        at async Object.onBind (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:227:48)\n        at async V (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:64:10)\n        at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12)\n  }\n}\n\n","log":"/logs/plugins/f/feedlist/error.json"}
]
