file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237
        throw new Error(y, { cause: u });
              ^

Error: [11-May-2025 17:46:38 UTC] PHP Fatal error:  Uncaught Error: Class "WC_Payment_Gateway" not found in /wordpress/wp-content/plugins/payment-gateway-cashbaba-for-wc/includes/class-cashbaba-woocommerce-gateway.php:7
Stack trace:
#0 /wordpress/wp-content/plugins/payment-gateway-cashbaba-for-wc/includes/class-cashbaba-woocommerce.php(96): require_once()
#1 /wordpress/wp-includes/class-wp-hook.php(324): Cashbaba_Woocommerce->init('')
#2 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#3 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /wordpress/wp-settings.php(578): do_action('plugins_loaded')
#5 /wordpress/wp-config.php(102): require_once('/wordpress/wp-s...')
#6 /wordpress/wp-load.php(50): require_once('/wordpress/wp-c...')
#7 /internal/eval.php(3): require_once('/wordpress/wp-l...')
#8 {main}
  thrown in /wordpress/wp-content/plugins/payment-gateway-cashbaba-for-wc/includes/class-cashbaba-woocommerce-gateway.php on line 7
[11-May-2025 17:46:47 UTC] PHP Fatal error:  Uncaught Error: Class "WC_Payment_Gateway" not found in /wordpress/wp-content/plugins/payment-gateway-cashbaba-for-wc/includes/class-cashbaba-woocommerce-gateway.php:7
Stack trace:
#0 /wordpress/wp-content/plugins/payment-gateway-cashbaba-for-wc/includes/class-cashbaba-woocommerce.php(96): require_once()
#1 /wordpress/wp-includes/class-wp-hook.php(324): Cashbaba_Woocommerce->init('')
#2 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#3 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /wordpress/wp-settings.php(578): do_action('plugins_loaded')
#5 /wordpress/wp-config.php(102): require_once('/wordpress/wp-s...')
#6 /wordpress/wp-load.php(50): require_once('/wordpress/wp-c...')
#7 /internal/eval.php(3): require_once('/wordpress/wp-l...')
#8 {main}
  thrown in /wordpress/wp-content/plugins/payment-gateway-cashbaba-for-wc/includes/class-cashbaba-woocommerce-gateway.php on line 7
[11-May-2025 17:46:56 UTC] PHP Fatal error:  Uncaught Error: Class "WC_Payment_Gateway" not found in /wordpress/wp-content/plugins/payment-gateway-cashbaba-for-wc/includes/class-cashbaba-woocommerce-gateway.php:7
Stack trace:
#0 /wordpress/wp-content/plugins/payment-gateway-cashbaba-for-wc/includes/class-cashbaba-woocommerce.php(96): require_once()
#1 /wordpress/wp-includes/class-wp-hook.php(324): Cashbaba_Woocommerce->init('')
#2 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#3 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /wordpress/wp-settings.php(578): do_action('plugins_loaded')
#5 /wordpress/wp-config.php(102): require_once('/wordpress/wp-s...')
#6 /wordpress/wp-load.php(50): require_once('/wordpress/wp-c...')
#7 /internal/eval.php(3): require_once('/wordpress/wp-l...')
#8 {main}
  thrown in /wordpress/wp-content/plugins/payment-gateway-cashbaba-for-wc/includes/class-cashbaba-woocommerce-gateway.php on line 7
[11-May-2025 17:47:33 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_error_message() on array in /wordpress/wp-content/plugins/pestoai/includes/class-pestoai-activator.php:112
Stack trace:
#0 /wordpress/wp-content/plugins/pestoai/pestoai.php(47): PestoAI_Activator::activate()
#1 /wordpress/wp-includes/class-wp-hook.php(324): pestoai_activate(false)
#2 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#3 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_pestoa...', false)
#5 /internal/eval.php(20): activate_plugin('pestoai/pestoai...')
#6 {main}
  thrown in /wordpress/wp-content/plugins/pestoai/includes/class-pestoai-activator.php on line 112
[11-May-2025 17:47:42 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_error_message() on array in /wordpress/wp-content/plugins/pestoai/includes/class-pestoai-activator.php:112
Stack trace:
#0 /wordpress/wp-content/plugins/pestoai/pestoai.php(47): PestoAI_Activator::activate()
#1 /wordpress/wp-includes/class-wp-hook.php(324): pestoai_activate(false)
#2 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#3 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_pestoa...', false)
#5 /internal/eval.php(20): activate_plugin('pestoai/pestoai...')
#6 {main}
  thrown in /wordpress/wp-content/plugins/pestoai/includes/class-pestoai-activator.php on line 112
[11-May-2025 17:47:50 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_error_message() on array in /wordpress/wp-content/plugins/pestoai/includes/class-pestoai-activator.php:112
Stack trace:
#0 /wordpress/wp-content/plugins/pestoai/pestoai.php(47): PestoAI_Activator::activate()
#1 /wordpress/wp-includes/class-wp-hook.php(324): pestoai_activate(false)
#2 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#3 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_pestoa...', false)
#5 /internal/eval.php(20): activate_plugin('pestoai/pestoai...')
#6 {main}
  thrown in /wordpress/wp-content/plugins/pestoai/includes/class-pestoai-activator.php on line 112
[11-May-2025 17:48:49 UTC] PHP Parse error:  syntax error, unexpected identifier "is_user_logged_in" in /wordpress/wp-content/plugins/pictures-in-comments/PIC.php on line 17
[11-May-2025 17:48:57 UTC] PHP Parse error:  syntax error, unexpected identifier "is_user_logged_in" in /wordpress/wp-content/plugins/pictures-in-comments/PIC.php on line 17
[11-May-2025 17:49:05 UTC] PHP Parse error:  syntax error, unexpected identifier "is_user_logged_in" in /wordpress/wp-content/plugins/pictures-in-comments/PIC.php on line 17
[11-May-2025 17:50:50 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>CREATE TABLE IF NOT EXISTS `wp_pixobe_designer_templates` (
        `id` int(9) unsigned NOT NULL AUTO_INCREMENT,
        `name` varchar(255) NOT NULL,
        `user_id` mediumint(9) NOT NULL,
        `data` json NOT NULL,
        `is_template` tinyint(1) NOT NULL DEFAULT 0,
        `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `modified_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (`id`)
    ) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: MySQL field type cannot be translated to SQLite: json.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-admin/includes/upgrade.php(3280): WP_SQLite_DB->query('CREATE TABLE IF...')
#2 /wordpress/wp-content/plugins/pixobe-designer/plugin/db/templates.php(22): dbDelta(Array)
#3 /wordpress/wp-content/plugins/pixobe-designer/pixobe-designer.php(65): Plugin\PixobeDesigner\create_designer_table()
#4 /wordpress/wp-includes/class-wp-hook.php(324): pixobe_designer_activated(false)
#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_pixobe...', false)
#8 /internal/eval.php(20): activate_plugin('pixobe-designer...')
#9 {main}</pre>
 for query CREATE TABLE IF NOT EXISTS `wp_pixobe_designer_templates` (
        `id` int(9) unsigned NOT NULL AUTO_INCREMENT,
        `name` varchar(255) NOT NULL,
        `user_id` mediumint(9) NOT NULL,
        `data` json NOT NULL,
        `is_template` tinyint(1) NOT NULL DEFAULT 0,
        `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `modified_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (`id`)
    ) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci made by activate_plugin, do_action('activate_pixobe-designer/pixobe-designer.php'), WP_Hook->do_action, WP_Hook->apply_filters, pixobe_designer_activated, Plugin\PixobeDesigner\create_designer_table, dbDelta, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[11-May-2025 17:51:01 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>CREATE TABLE IF NOT EXISTS `wp_pixobe_designer_templates` (
        `id` int(9) unsigned NOT NULL AUTO_INCREMENT,
        `name` varchar(255) NOT NULL,
        `user_id` mediumint(9) NOT NULL,
        `data` json NOT NULL,
        `is_template` tinyint(1) NOT NULL DEFAULT 0,
        `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `modified_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (`id`)
    ) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: MySQL field type cannot be translated to SQLite: json.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-admin/includes/upgrade.php(3280): WP_SQLite_DB->query('CREATE TABLE IF...')
#2 /wordpress/wp-content/plugins/pixobe-designer/plugin/db/templates.php(22): dbDelta(Array)
#3 /wordpress/wp-content/plugins/pixobe-designer/pixobe-designer.php(65): Plugin\PixobeDesigner\create_designer_table()
#4 /wordpress/wp-includes/class-wp-hook.php(324): pixobe_designer_activated(false)
#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_pixobe...', false)
#8 /internal/eval.php(20): activate_plugin('pixobe-designer...')
#9 {main}</pre>
 for query CREATE TABLE IF NOT EXISTS `wp_pixobe_designer_templates` (
        `id` int(9) unsigned NOT NULL AUTO_INCREMENT,
        `name` varchar(255) NOT NULL,
        `user_id` mediumint(9) NOT NULL,
        `data` json NOT NULL,
        `is_template` tinyint(1) NOT NULL DEFAULT 0,
        `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
        `modified_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (`id`)
    ) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci made by activate_plugin, do_action('activate_pixobe-designer/pixobe-designer.php'), WP_Hook->do_action, WP_Hook->apply_filters, pixobe_designer_activated, Plugin\PixobeDesigner\create_designer_table, dbDelta, WP_SQLite_DB->query, WP_SQLite_DB->print_error

    at Object.onBind (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async V (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:64:10)
    at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {
  [cause]: Error: Error when executing the blueprint step #5 ({"step":"installPlugin","pluginData":{"resource":"wordpress.org/plugins","slug":"plugin-information"},"options":{"activate":true}}) : Could not download "https://downloads.wordpress.org/plugin/plugin-information.latest-stable.zip".
  				Check if the URL is correct and the server is reachable.
  				If it is reachable, the server might be blocking the request.
  				Check the browser console and network tabs for more information.
  
  				## Does the console show the error "No 'Access-Control-Allow-Origin' header"?
  
  				This means the server that hosts your file does not allow requests from other sites
  				(cross-origin requests, or CORS).	You need to move the asset to a server that allows
  				cross-origin file downloads. Learn more about CORS at
  				https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS.
  
  				If your file is on GitHub, load it from "raw.githubusercontent.com".
  				Here's how to do that:
  
  				1. Start with the original GitHub URL of the file. For example:
  				https://github.com/username/repository/blob/branch/filename.
  				2. Replace "github.com" with "raw.githubusercontent.com".
  				3. Remove the "/blob/" part of the URL.
  
  				The resulting URL should look like this:
  				https://raw.githubusercontent.com/username/repository/branch/filename
  
  				Error:
  				Error: Could not download "https://downloads.wordpress.org/plugin/plugin-information.latest-stable.zip"
      at Object.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12449:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async ms (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12552:3)
      at async Object.onBind (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:227:48)
      at async V (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:64:10)
      at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {
    [cause]: Error: Could not download "https://downloads.wordpress.org/plugin/plugin-information.latest-stable.zip".
    				Check if the URL is correct and the server is reachable.
    				If it is reachable, the server might be blocking the request.
    				Check the browser console and network tabs for more information.
    
    				## Does the console show the error "No 'Access-Control-Allow-Origin' header"?
    
    				This means the server that hosts your file does not allow requests from other sites
    				(cross-origin requests, or CORS).	You need to move the asset to a server that allows
    				cross-origin file downloads. Learn more about CORS at
    				https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS.
    
    				If your file is on GitHub, load it from "raw.githubusercontent.com".
    				Here's how to do that:
    
    				1. Start with the original GitHub URL of the file. For example:
    				https://github.com/username/repository/blob/branch/filename.
    				2. Replace "github.com" with "raw.githubusercontent.com".
    				3. Remove the "/blob/" part of the URL.
    
    				The resulting URL should look like this:
    				https://raw.githubusercontent.com/username/repository/branch/filename
    
    				Error:
    				Error: Could not download "https://downloads.wordpress.org/plugin/plugin-information.latest-stable.zip"
        at Ct.resolve (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:1472:13)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async _.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@php-wasm/util/index.js:45:14)
  }
}

Node.js v23.11.0
