[
{"message":"file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237\n        throw new Error(y, { cause: u });\n              ^\n","level":"FATAL","type":"PLAYGROUND","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237\n        throw new Error(y, { cause: u });\n              ^\n","log":"/tmp/tmp.Zrj9bUTNXc"}
,
{"message":"syntax error, unexpected ')' in /wordpress/wp-content/plugins/permissionsplus/includes/class-settings.php on line 280","level":"PARSE","type":"PHP","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:34:54 UTC] PHP Parse error:  syntax error, unexpected ')' in /wordpress/wp-content/plugins/permissionsplus/includes/class-settings.php on line 280","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"syntax error, unexpected ')' in /wordpress/wp-content/plugins/permissionsplus/includes/class-settings.php on line 280","level":"PARSE","type":"PHP","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:35:02 UTC] PHP Parse error:  syntax error, unexpected ')' in /wordpress/wp-content/plugins/permissionsplus/includes/class-settings.php on line 280","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"syntax error, unexpected ')' in /wordpress/wp-content/plugins/permissionsplus/includes/class-settings.php on line 280","level":"PARSE","type":"PHP","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:35:11 UTC] PHP Parse error:  syntax error, unexpected ')' in /wordpress/wp-content/plugins/permissionsplus/includes/class-settings.php on line 280","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"syntax error, unexpected ')' in /wordpress/wp-content/plugins/pilllz-avatars/meepha-pilllz.php on line 140","level":"PARSE","type":"PHP","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:35:47 UTC] PHP Parse error:  syntax error, unexpected ')' in /wordpress/wp-content/plugins/pilllz-avatars/meepha-pilllz.php on line 140","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"syntax error, unexpected ')' in /wordpress/wp-content/plugins/pilllz-avatars/meepha-pilllz.php on line 140","level":"PARSE","type":"PHP","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:35:55 UTC] PHP Parse error:  syntax error, unexpected ')' in /wordpress/wp-content/plugins/pilllz-avatars/meepha-pilllz.php on line 140","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"syntax error, unexpected ')' in /wordpress/wp-content/plugins/pilllz-avatars/meepha-pilllz.php on line 140","level":"PARSE","type":"PHP","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:36:03 UTC] PHP Parse error:  syntax error, unexpected ')' in /wordpress/wp-content/plugins/pilllz-avatars/meepha-pilllz.php on line 140","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"Uncaught Error: Cannot use object of type WP_Error as array in /wordpress/wp-content/plugins/plica-stats/plica-stats.php:57","level":"FATAL","type":"PHP","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:36:12 UTC] PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in /wordpress/wp-content/plugins/plica-stats/plica-stats.php:57\nStack trace:\n#0 /wordpress/wp-content/plugins/plica-stats/plica-stats.php(63): plica_stats_api_register()\n#1 /wordpress/wp-includes/class-wp-hook.php(324): plica_stats_activate(false)\n#2 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#3 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#4 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_plica-...', false)\n#5 /internal/eval.php(20): activate_plugin('plica-stats/pli...')\n#6 {main}\n  thrown in /wordpress/wp-content/plugins/plica-stats/plica-stats.php on line 57","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"Uncaught Error: Cannot use object of type WP_Error as array in /wordpress/wp-content/plugins/plica-stats/plica-stats.php:57","level":"FATAL","type":"PHP","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:36:19 UTC] PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in /wordpress/wp-content/plugins/plica-stats/plica-stats.php:57\nStack trace:\n#0 /wordpress/wp-content/plugins/plica-stats/plica-stats.php(63): plica_stats_api_register()\n#1 /wordpress/wp-includes/class-wp-hook.php(324): plica_stats_activate(false)\n#2 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#3 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#4 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_plica-...', false)\n#5 /internal/eval.php(20): activate_plugin('plica-stats/pli...')\n#6 {main}\n  thrown in /wordpress/wp-content/plugins/plica-stats/plica-stats.php on line 57","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"Uncaught Error: Cannot use object of type WP_Error as array in /wordpress/wp-content/plugins/plica-stats/plica-stats.php:57","level":"FATAL","type":"PHP","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:36:28 UTC] PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in /wordpress/wp-content/plugins/plica-stats/plica-stats.php:57\nStack trace:\n#0 /wordpress/wp-content/plugins/plica-stats/plica-stats.php(63): plica_stats_api_register()\n#1 /wordpress/wp-includes/class-wp-hook.php(324): plica_stats_activate(false)\n#2 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#3 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#4 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_plica-...', false)\n#5 /internal/eval.php(20): activate_plugin('plica-stats/pli...')\n#6 {main}\n  thrown in /wordpress/wp-content/plugins/plica-stats/plica-stats.php on line 57","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>portfolio-filter-gallery</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href=\"https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/\">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /wordpress/wp-includes/functions.php on line 6121","level":"NOTICE","type":"PHP","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:39:33 UTC] PHP Notice:  Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>portfolio-filter-gallery</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href=\"https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/\">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /wordpress/wp-includes/functions.php on line 6121","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>portfolio-filter-gallery</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href=\"https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/\">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /wordpress/wp-includes/functions.php on line 6121","level":"NOTICE","type":"PHP","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:39:42 UTC] PHP Notice:  Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>portfolio-filter-gallery</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href=\"https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/\">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /wordpress/wp-includes/functions.php on line 6121","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>portfolio-filter-gallery</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href=\"https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/\">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /wordpress/wp-includes/functions.php on line 6121","level":"NOTICE","type":"PHP","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:39:51 UTC] PHP Notice:  Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>portfolio-filter-gallery</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href=\"https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/\">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /wordpress/wp-includes/functions.php on line 6121","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"Uncaught ArgumentCountError: Too few arguments to function WP_Widget::__construct(), 0 passed in /wordpress/wp-includes/class-wp-widget-factory.php on line 62 and at least 2 expected in /wordpress/wp-includes/class-wp-widget.php:163","level":"FATAL","type":"PHP","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:40:01 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function WP_Widget::__construct(), 0 passed in /wordpress/wp-includes/class-wp-widget-factory.php on line 62 and at least 2 expected in /wordpress/wp-includes/class-wp-widget.php:163\nStack trace:\n#0 /wordpress/wp-includes/class-wp-widget-factory.php(62): WP_Widget->__construct()\n#1 /wordpress/wp-includes/widgets.php(123): WP_Widget_Factory->register('PostHighlightsW...')\n#2 /wordpress/wp-content/plugins/post-highlights/widget.php(74): register_widget('PostHighlightsW...')\n#3 /wordpress/wp-includes/class-wp-hook.php(324): registerPostHighlightsWidget('')\n#4 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#5 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#6 /wordpress/wp-includes/widgets.php(1870): do_action('widgets_init')\n#7 /wordpress/wp-includes/class-wp-hook.php(324): wp_widgets_init('')\n#8 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#9 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#10 /wordpress/wp-settings.php(727): do_action('init')\n#11 /wordpress/wp-config.php(102): require_once('/wordpress/wp-s...')\n#12 /wordpress/wp-load.php(50): require_once('/wordpress/wp-c...')\n#13 /internal/eval.php(3): require_once('/wordpress/wp-l...')\n#14 {main}\n  thrown in /wordpress/wp-includes/class-wp-widget.php on line 163","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"Uncaught ArgumentCountError: Too few arguments to function WP_Widget::__construct(), 0 passed in /wordpress/wp-includes/class-wp-widget-factory.php on line 62 and at least 2 expected in /wordpress/wp-includes/class-wp-widget.php:163","level":"FATAL","type":"PHP","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:40:10 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function WP_Widget::__construct(), 0 passed in /wordpress/wp-includes/class-wp-widget-factory.php on line 62 and at least 2 expected in /wordpress/wp-includes/class-wp-widget.php:163\nStack trace:\n#0 /wordpress/wp-includes/class-wp-widget-factory.php(62): WP_Widget->__construct()\n#1 /wordpress/wp-includes/widgets.php(123): WP_Widget_Factory->register('PostHighlightsW...')\n#2 /wordpress/wp-content/plugins/post-highlights/widget.php(74): register_widget('PostHighlightsW...')\n#3 /wordpress/wp-includes/class-wp-hook.php(324): registerPostHighlightsWidget('')\n#4 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#5 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#6 /wordpress/wp-includes/widgets.php(1870): do_action('widgets_init')\n#7 /wordpress/wp-includes/class-wp-hook.php(324): wp_widgets_init('')\n#8 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#9 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#10 /wordpress/wp-settings.php(727): do_action('init')\n#11 /wordpress/wp-config.php(102): require_once('/wordpress/wp-s...')\n#12 /wordpress/wp-load.php(50): require_once('/wordpress/wp-c...')\n#13 /internal/eval.php(3): require_once('/wordpress/wp-l...')\n#14 {main}\n  thrown in /wordpress/wp-includes/class-wp-widget.php on line 163","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"Uncaught ArgumentCountError: Too few arguments to function WP_Widget::__construct(), 0 passed in /wordpress/wp-includes/class-wp-widget-factory.php on line 62 and at least 2 expected in /wordpress/wp-includes/class-wp-widget.php:163","level":"FATAL","type":"PHP","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:40:18 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function WP_Widget::__construct(), 0 passed in /wordpress/wp-includes/class-wp-widget-factory.php on line 62 and at least 2 expected in /wordpress/wp-includes/class-wp-widget.php:163\nStack trace:\n#0 /wordpress/wp-includes/class-wp-widget-factory.php(62): WP_Widget->__construct()\n#1 /wordpress/wp-includes/widgets.php(123): WP_Widget_Factory->register('PostHighlightsW...')\n#2 /wordpress/wp-content/plugins/post-highlights/widget.php(74): register_widget('PostHighlightsW...')\n#3 /wordpress/wp-includes/class-wp-hook.php(324): registerPostHighlightsWidget('')\n#4 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#5 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#6 /wordpress/wp-includes/widgets.php(1870): do_action('widgets_init')\n#7 /wordpress/wp-includes/class-wp-hook.php(324): wp_widgets_init('')\n#8 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#9 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#10 /wordpress/wp-settings.php(727): do_action('init')\n#11 /wordpress/wp-config.php(102): require_once('/wordpress/wp-s...')\n#12 /wordpress/wp-load.php(50): require_once('/wordpress/wp-c...')\n#13 /internal/eval.php(3): require_once('/wordpress/wp-l...')\n#14 {main}\n  thrown in /wordpress/wp-includes/class-wp-widget.php on line 163","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_post_notification_posts.","level":"FATAL","type":"SQL","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:40:37 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>SELECT id, notification_sent  FROM wp_posts p, wp_post_notification_posts el WHERE( el.notification_sent >= 0 AND p.id = el.post_id AND p.post_status IN('publish', 'private', 'future') AND GREATEST(p.post_date_gmt, el.date_saved) < '2025-04-27 06:40:37' )</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: SELECT id, notification_sent  FROM wp_posts p, wp_post_notification_posts el WHERE( el.notification_sent &gt;= 0 AND p.id = el.post_id AND p.post_status IN(:param0 , :param1 , :param2 ) AND GREATEST(p.post_date_gmt, el.date_saved) &lt; :param3  ) | parameters: publish, private, future, 2025-04-27 06:40:37</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_post_notification_posts.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-includes/class-wpdb.php(3146): WP_SQLite_DB->query('SELECT id, noti...')\n#2 /wordpress/wp-content/plugins/post-notification/sendmail.php(259): wpdb->get_results('SELECT id, noti...')\n#3 /wordpress/wp-content/plugins/post-notification/post_notification.php(209): post_notification_send()\n#4 /wordpress/wp-includes/class-wp-hook.php(324): post_notification_send_check('')\n#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#7 /wordpress/wp-includes/load.php(1304): do_action('shutdown')\n#8 [internal function]: shutdown_action_hook()\n#9 {main}</pre>\n for query SELECT id, notification_sent  FROM wp_posts p, wp_post_notification_posts el WHERE( el.notification_sent >= 0 AND p.id = el.post_id AND p.post_status IN('publish', 'private', 'future') AND GREATEST(p.post_date_gmt, el.date_saved) < '2025-04-27 06:40:37' ) made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, post_notification_send_check, post_notification_send, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_post_notification_emails.","level":"FATAL","type":"SQL","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:40:37 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>SELECT COUNT(*) FROM wp_post_notification_emails WHERE gets_mail = 1</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: SELECT COUNT(*) FROM wp_post_notification_emails WHERE gets_mail = 1 | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_post_notification_emails.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-includes/class-wpdb.php(3031): WP_SQLite_DB->query('SELECT COUNT(*)...')\n#2 /wordpress/wp-content/plugins/post-notification/functions.php(205): wpdb->get_var('SELECT COUNT(*)...')\n#3 /wordpress/wp-content/plugins/post-notification/sendmail.php(264): post_notification_set_next_send()\n#4 /wordpress/wp-content/plugins/post-notification/post_notification.php(209): post_notification_send()\n#5 /wordpress/wp-includes/class-wp-hook.php(324): post_notification_send_check('')\n#6 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#7 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#8 /wordpress/wp-includes/load.php(1304): do_action('shutdown')\n#9 [internal function]: shutdown_action_hook()\n#10 {main}</pre>\n for query SELECT COUNT(*) FROM wp_post_notification_emails WHERE gets_mail = 1 made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, post_notification_send_check, post_notification_send, post_notification_set_next_send, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_post_notification_posts.","level":"FATAL","type":"SQL","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:40:37 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>SELECT MIN(GREATEST(post_date_gmt, date_saved))  FROM wp_posts p, wp_post_notification_posts el WHERE( el.notification_sent >= 0 AND p.id = el.post_id AND p.post_status IN('publish', 'private', 'future') )</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: SELECT MIN(GREATEST(post_date_gmt, date_saved))  FROM wp_posts p, wp_post_notification_posts el WHERE( el.notification_sent &gt;= 0 AND p.id = el.post_id AND p.post_status IN(:param0 , :param1 , :param2 ) ) | parameters: publish, private, future</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_post_notification_posts.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-includes/class-wpdb.php(3031): WP_SQLite_DB->query('SELECT MIN(GREA...')\n#2 /wordpress/wp-content/plugins/post-notification/functions.php(208): wpdb->get_var('SELECT MIN(GREA...')\n#3 /wordpress/wp-content/plugins/post-notification/sendmail.php(264): post_notification_set_next_send()\n#4 /wordpress/wp-content/plugins/post-notification/post_notification.php(209): post_notification_send()\n#5 /wordpress/wp-includes/class-wp-hook.php(324): post_notification_send_check('')\n#6 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#7 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#8 /wordpress/wp-includes/load.php(1304): do_action('shutdown')\n#9 [internal function]: shutdown_action_hook()\n#10 {main}</pre>\n for query SELECT MIN(GREATEST(post_date_gmt, date_saved))  FROM wp_posts p, wp_post_notification_posts el WHERE( el.notification_sent >= 0 AND p.id = el.post_id AND p.post_status IN('publish', 'private', 'future') ) made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, post_notification_send_check, post_notification_send, post_notification_set_next_send, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_post_notification_posts.","level":"FATAL","type":"SQL","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:40:47 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>SELECT id, notification_sent  FROM wp_posts p, wp_post_notification_posts el WHERE( el.notification_sent >= 0 AND p.id = el.post_id AND p.post_status IN('publish', 'private', 'future') AND GREATEST(p.post_date_gmt, el.date_saved) < '2025-04-27 06:40:47' )</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: SELECT id, notification_sent  FROM wp_posts p, wp_post_notification_posts el WHERE( el.notification_sent &gt;= 0 AND p.id = el.post_id AND p.post_status IN(:param0 , :param1 , :param2 ) AND GREATEST(p.post_date_gmt, el.date_saved) &lt; :param3  ) | parameters: publish, private, future, 2025-04-27 06:40:47</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_post_notification_posts.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-includes/class-wpdb.php(3146): WP_SQLite_DB->query('SELECT id, noti...')\n#2 /wordpress/wp-content/plugins/post-notification/sendmail.php(259): wpdb->get_results('SELECT id, noti...')\n#3 /wordpress/wp-content/plugins/post-notification/post_notification.php(209): post_notification_send()\n#4 /wordpress/wp-includes/class-wp-hook.php(324): post_notification_send_check('')\n#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#7 /wordpress/wp-includes/load.php(1304): do_action('shutdown')\n#8 [internal function]: shutdown_action_hook()\n#9 {main}</pre>\n for query SELECT id, notification_sent  FROM wp_posts p, wp_post_notification_posts el WHERE( el.notification_sent >= 0 AND p.id = el.post_id AND p.post_status IN('publish', 'private', 'future') AND GREATEST(p.post_date_gmt, el.date_saved) < '2025-04-27 06:40:47' ) made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, post_notification_send_check, post_notification_send, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_post_notification_emails.","level":"FATAL","type":"SQL","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:40:47 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>SELECT COUNT(*) FROM wp_post_notification_emails WHERE gets_mail = 1</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: SELECT COUNT(*) FROM wp_post_notification_emails WHERE gets_mail = 1 | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_post_notification_emails.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-includes/class-wpdb.php(3031): WP_SQLite_DB->query('SELECT COUNT(*)...')\n#2 /wordpress/wp-content/plugins/post-notification/functions.php(205): wpdb->get_var('SELECT COUNT(*)...')\n#3 /wordpress/wp-content/plugins/post-notification/sendmail.php(264): post_notification_set_next_send()\n#4 /wordpress/wp-content/plugins/post-notification/post_notification.php(209): post_notification_send()\n#5 /wordpress/wp-includes/class-wp-hook.php(324): post_notification_send_check('')\n#6 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#7 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#8 /wordpress/wp-includes/load.php(1304): do_action('shutdown')\n#9 [internal function]: shutdown_action_hook()\n#10 {main}</pre>\n for query SELECT COUNT(*) FROM wp_post_notification_emails WHERE gets_mail = 1 made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, post_notification_send_check, post_notification_send, post_notification_set_next_send, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_post_notification_posts.","level":"FATAL","type":"SQL","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:40:47 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>SELECT MIN(GREATEST(post_date_gmt, date_saved))  FROM wp_posts p, wp_post_notification_posts el WHERE( el.notification_sent >= 0 AND p.id = el.post_id AND p.post_status IN('publish', 'private', 'future') )</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: SELECT MIN(GREATEST(post_date_gmt, date_saved))  FROM wp_posts p, wp_post_notification_posts el WHERE( el.notification_sent &gt;= 0 AND p.id = el.post_id AND p.post_status IN(:param0 , :param1 , :param2 ) ) | parameters: publish, private, future</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_post_notification_posts.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-includes/class-wpdb.php(3031): WP_SQLite_DB->query('SELECT MIN(GREA...')\n#2 /wordpress/wp-content/plugins/post-notification/functions.php(208): wpdb->get_var('SELECT MIN(GREA...')\n#3 /wordpress/wp-content/plugins/post-notification/sendmail.php(264): post_notification_set_next_send()\n#4 /wordpress/wp-content/plugins/post-notification/post_notification.php(209): post_notification_send()\n#5 /wordpress/wp-includes/class-wp-hook.php(324): post_notification_send_check('')\n#6 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#7 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#8 /wordpress/wp-includes/load.php(1304): do_action('shutdown')\n#9 [internal function]: shutdown_action_hook()\n#10 {main}</pre>\n for query SELECT MIN(GREATEST(post_date_gmt, date_saved))  FROM wp_posts p, wp_post_notification_posts el WHERE( el.notification_sent >= 0 AND p.id = el.post_id AND p.post_status IN('publish', 'private', 'future') ) made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, post_notification_send_check, post_notification_send, post_notification_set_next_send, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"Uncaught Error: Non-static method CPTC_Widget::init() cannot be called statically in /wordpress/wp-content/plugins/post-types-calendar/post-types-calendar.widget.php:210","level":"FATAL","type":"PHP","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:41:51 UTC] PHP Fatal error:  Uncaught Error: Non-static method CPTC_Widget::init() cannot be called statically in /wordpress/wp-content/plugins/post-types-calendar/post-types-calendar.widget.php:210\nStack trace:\n#0 /wordpress/wp-admin/includes/plugin.php(2387): include_once()\n#1 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('post-types-cale...')\n#2 /internal/eval.php(20): activate_plugin('post-types-cale...')\n#3 {main}\n  thrown in /wordpress/wp-content/plugins/post-types-calendar/post-types-calendar.widget.php on line 210","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"Uncaught Error: Non-static method CPTC_Widget::init() cannot be called statically in /wordpress/wp-content/plugins/post-types-calendar/post-types-calendar.widget.php:210","level":"FATAL","type":"PHP","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:41:59 UTC] PHP Fatal error:  Uncaught Error: Non-static method CPTC_Widget::init() cannot be called statically in /wordpress/wp-content/plugins/post-types-calendar/post-types-calendar.widget.php:210\nStack trace:\n#0 /wordpress/wp-admin/includes/plugin.php(2387): include_once()\n#1 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('post-types-cale...')\n#2 /internal/eval.php(20): activate_plugin('post-types-cale...')\n#3 {main}\n  thrown in /wordpress/wp-content/plugins/post-types-calendar/post-types-calendar.widget.php on line 210","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"Uncaught Error: Non-static method CPTC_Widget::init() cannot be called statically in /wordpress/wp-content/plugins/post-types-calendar/post-types-calendar.widget.php:210","level":"FATAL","type":"PHP","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:42:07 UTC] PHP Fatal error:  Uncaught Error: Non-static method CPTC_Widget::init() cannot be called statically in /wordpress/wp-content/plugins/post-types-calendar/post-types-calendar.widget.php:210\nStack trace:\n#0 /wordpress/wp-admin/includes/plugin.php(2387): include_once()\n#1 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('post-types-cale...')\n#2 /internal/eval.php(20): activate_plugin('post-types-cale...')\n#3 {main}\n  thrown in /wordpress/wp-content/plugins/post-types-calendar/post-types-calendar.widget.php on line 210","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"Unexpected token in MySQL query: published.","level":"FATAL","type":"SQL","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:42:25 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>CREATE TABLE wp_name_directory_name (\n            id INT( 11 ) NOT NULL AUTO_INCREMENT,\n            directory INT( 11 ) NOT NULL ,\n            name VARCHAR( 255 ) NOT NULL ,\n            letter VARCHAR( 1 ) NOT NULL ,\n            description TEXT NULL ,\n            published BOOL NOT NULL ,\n            submitted_by VARCHAR( 255 ) NULL,\n            UNIQUE KEY id (id),\n            PRIMARY KEY (id));</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unexpected token in MySQL query: published.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-admin/includes/upgrade.php(3280): WP_SQLite_DB->query('CREATE TABLE wp...')\n#2 /wordpress/wp-content/plugins/name-directory/database.php(61): dbDelta(Array)\n#3 /wordpress/wp-includes/class-wp-hook.php(324): name_directory_db_tables(false)\n#4 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#5 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#6 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_name-d...', false)\n#7 /internal/eval.php(20): activate_plugin('name-directory/...')\n#8 {main}</pre>\n for query CREATE TABLE wp_name_directory_name (\n            id INT( 11 ) NOT NULL AUTO_INCREMENT,\n            directory INT( 11 ) NOT NULL ,\n            name VARCHAR( 255 ) NOT NULL ,\n            letter VARCHAR( 1 ) NOT NULL ,\n            description TEXT NULL ,\n            published BOOL NOT NULL ,\n            submitted_by VARCHAR( 255 ) NULL,\n            UNIQUE KEY id (id),\n            PRIMARY KEY (id)); made by activate_plugin, do_action('activate_name-directory/index.php'), WP_Hook->do_action, WP_Hook->apply_filters, name_directory_db_tables, dbDelta, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_name_directory_name.","level":"FATAL","type":"SQL","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:42:26 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>INSERT INTO `wp_name_directory_name` (`directory`, `name`, `letter`, `description`, `published`) VALUES ('1', 'Navi', 'N', 'Navi is a good aviator and navigator. A very strong and big budgie, almost English', '1')</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: INSERT INTO `wp_name_directory_name` (`directory`, `name`, `letter`, `description`, `published`) VALUES (:param0 , :param1 , :param2 , :param3 , :param4 ) | parameters: 1, Navi, N, Navi is a good aviator and navigator. A very strong and big budgie, almost English, 1</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_name_directory_name.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-includes/class-wpdb.php(2614): WP_SQLite_DB->query('INSERT INTO `wp...')\n#2 /wordpress/wp-includes/class-wpdb.php(2503): wpdb->_insert_replace_helper('wp_name_directo...', Array, NULL, 'INSERT')\n#3 /wordpress/wp-content/plugins/name-directory/database.php(133): wpdb->insert('wp_name_directo...', Array)\n#4 /wordpress/wp-includes/class-wp-hook.php(324): name_directory_db_install_demo_data(false)\n#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_name-d...', false)\n#8 /internal/eval.php(20): activate_plugin('name-directory/...')\n#9 {main}</pre>\n for query INSERT INTO `wp_name_directory_name` (`directory`, `name`, `letter`, `description`, `published`) VALUES ('1', 'Navi', 'N', 'Navi is a good aviator and navigator. A very strong and big budgie, almost English', '1') made by activate_plugin, do_action('activate_name-directory/index.php'), WP_Hook->do_action, WP_Hook->apply_filters, name_directory_db_install_demo_data, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_name_directory_name.","level":"FATAL","type":"SQL","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:42:26 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>INSERT INTO `wp_name_directory_name` (`directory`, `name`, `letter`, `description`, `published`) VALUES ('1', 'Mister', 'M', 'Mister is a name which can only be assigned to a typical English Budgie. Big, strong and stringent.', '1')</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: INSERT INTO `wp_name_directory_name` (`directory`, `name`, `letter`, `description`, `published`) VALUES (:param0 , :param1 , :param2 , :param3 , :param4 ) | parameters: 1, Mister, M, Mister is a name which can only be assigned to a typical English Budgie. Big, strong and stringent., 1</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_name_directory_name.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-includes/class-wpdb.php(2614): WP_SQLite_DB->query('INSERT INTO `wp...')\n#2 /wordpress/wp-includes/class-wpdb.php(2503): wpdb->_insert_replace_helper('wp_name_directo...', Array, NULL, 'INSERT')\n#3 /wordpress/wp-content/plugins/name-directory/database.php(140): wpdb->insert('wp_name_directo...', Array)\n#4 /wordpress/wp-includes/class-wp-hook.php(324): name_directory_db_install_demo_data(false)\n#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_name-d...', false)\n#8 /internal/eval.php(20): activate_plugin('name-directory/...')\n#9 {main}</pre>\n for query INSERT INTO `wp_name_directory_name` (`directory`, `name`, `letter`, `description`, `published`) VALUES ('1', 'Mister', 'M', 'Mister is a name which can only be assigned to a typical English Budgie. Big, strong and stringent.', '1') made by activate_plugin, do_action('activate_name-directory/index.php'), WP_Hook->do_action, WP_Hook->apply_filters, name_directory_db_install_demo_data, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_name_directory_name.","level":"FATAL","type":"SQL","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:42:26 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>INSERT INTO `wp_name_directory_name` (`directory`, `name`, `letter`, `description`, `published`) VALUES ('1', 'Isa', 'I', 'Isa is a direct descent of Mister. As a fullblood daughter she is also a typical English Budgie.', '1')</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: INSERT INTO `wp_name_directory_name` (`directory`, `name`, `letter`, `description`, `published`) VALUES (:param0 , :param1 , :param2 , :param3 , :param4 ) | parameters: 1, Isa, I, Isa is a direct descent of Mister. As a fullblood daughter she is also a typical English Budgie., 1</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_name_directory_name.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-includes/class-wpdb.php(2614): WP_SQLite_DB->query('INSERT INTO `wp...')\n#2 /wordpress/wp-includes/class-wpdb.php(2503): wpdb->_insert_replace_helper('wp_name_directo...', Array, NULL, 'INSERT')\n#3 /wordpress/wp-content/plugins/name-directory/database.php(147): wpdb->insert('wp_name_directo...', Array)\n#4 /wordpress/wp-includes/class-wp-hook.php(324): name_directory_db_install_demo_data(false)\n#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_name-d...', false)\n#8 /internal/eval.php(20): activate_plugin('name-directory/...')\n#9 {main}</pre>\n for query INSERT INTO `wp_name_directory_name` (`directory`, `name`, `letter`, `description`, `published`) VALUES ('1', 'Isa', 'I', 'Isa is a direct descent of Mister. As a fullblood daughter she is also a typical English Budgie.', '1') made by activate_plugin, do_action('activate_name-directory/index.php'), WP_Hook->do_action, WP_Hook->apply_filters, name_directory_db_install_demo_data, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"Unknown operation: CONVERT.","level":"FATAL","type":"SQL","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:42:26 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE wp_name_directory CONVERT TO CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci';</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown operation: CONVERT.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/name-directory/database.php(78): WP_SQLite_DB->query('ALTER TABLE wp_...')\n#2 /wordpress/wp-content/plugins/name-directory/database.php(154): name_directory_db_post_update_actions()\n#3 /wordpress/wp-includes/class-wp-hook.php(324): name_directory_db_install_demo_data(false)\n#4 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#5 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#6 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_name-d...', false)\n#7 /internal/eval.php(20): activate_plugin('name-directory/...')\n#8 {main}</pre>\n for query ALTER TABLE wp_name_directory CONVERT TO CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci'; made by activate_plugin, do_action('activate_name-directory/index.php'), WP_Hook->do_action, WP_Hook->apply_filters, name_directory_db_install_demo_data, name_directory_db_post_update_actions, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"Unknown operation: CONVERT.","level":"FATAL","type":"SQL","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:42:26 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE wp_name_directory_name CONVERT TO CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci';</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown operation: CONVERT.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/name-directory/database.php(81): WP_SQLite_DB->query('ALTER TABLE wp_...')\n#2 /wordpress/wp-content/plugins/name-directory/database.php(154): name_directory_db_post_update_actions()\n#3 /wordpress/wp-includes/class-wp-hook.php(324): name_directory_db_install_demo_data(false)\n#4 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#5 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#6 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_name-d...', false)\n#7 /internal/eval.php(20): activate_plugin('name-directory/...')\n#8 {main}</pre>\n for query ALTER TABLE wp_name_directory_name CONVERT TO CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci'; made by activate_plugin, do_action('activate_name-directory/index.php'), WP_Hook->do_action, WP_Hook->apply_filters, name_directory_db_install_demo_data, name_directory_db_post_update_actions, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"Unexpected token in MySQL query: published.","level":"FATAL","type":"SQL","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:42:34 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>CREATE TABLE wp_name_directory_name (\n            id INT( 11 ) NOT NULL AUTO_INCREMENT,\n            directory INT( 11 ) NOT NULL ,\n            name VARCHAR( 255 ) NOT NULL ,\n            letter VARCHAR( 1 ) NOT NULL ,\n            description TEXT NULL ,\n            published BOOL NOT NULL ,\n            submitted_by VARCHAR( 255 ) NULL,\n            UNIQUE KEY id (id),\n            PRIMARY KEY (id));</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unexpected token in MySQL query: published.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-admin/includes/upgrade.php(3280): WP_SQLite_DB->query('CREATE TABLE wp...')\n#2 /wordpress/wp-content/plugins/name-directory/database.php(61): dbDelta(Array)\n#3 /wordpress/wp-includes/class-wp-hook.php(324): name_directory_db_tables(false)\n#4 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#5 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#6 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_name-d...', false)\n#7 /internal/eval.php(20): activate_plugin('name-directory/...')\n#8 {main}</pre>\n for query CREATE TABLE wp_name_directory_name (\n            id INT( 11 ) NOT NULL AUTO_INCREMENT,\n            directory INT( 11 ) NOT NULL ,\n            name VARCHAR( 255 ) NOT NULL ,\n            letter VARCHAR( 1 ) NOT NULL ,\n            description TEXT NULL ,\n            published BOOL NOT NULL ,\n            submitted_by VARCHAR( 255 ) NULL,\n            UNIQUE KEY id (id),\n            PRIMARY KEY (id)); made by activate_plugin, do_action('activate_name-directory/index.php'), WP_Hook->do_action, WP_Hook->apply_filters, name_directory_db_tables, dbDelta, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_name_directory_name.","level":"FATAL","type":"SQL","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:42:34 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>INSERT INTO `wp_name_directory_name` (`directory`, `name`, `letter`, `description`, `published`) VALUES ('1', 'Navi', 'N', 'Navi is a good aviator and navigator. A very strong and big budgie, almost English', '1')</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: INSERT INTO `wp_name_directory_name` (`directory`, `name`, `letter`, `description`, `published`) VALUES (:param0 , :param1 , :param2 , :param3 , :param4 ) | parameters: 1, Navi, N, Navi is a good aviator and navigator. A very strong and big budgie, almost English, 1</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_name_directory_name.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-includes/class-wpdb.php(2614): WP_SQLite_DB->query('INSERT INTO `wp...')\n#2 /wordpress/wp-includes/class-wpdb.php(2503): wpdb->_insert_replace_helper('wp_name_directo...', Array, NULL, 'INSERT')\n#3 /wordpress/wp-content/plugins/name-directory/database.php(133): wpdb->insert('wp_name_directo...', Array)\n#4 /wordpress/wp-includes/class-wp-hook.php(324): name_directory_db_install_demo_data(false)\n#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_name-d...', false)\n#8 /internal/eval.php(20): activate_plugin('name-directory/...')\n#9 {main}</pre>\n for query INSERT INTO `wp_name_directory_name` (`directory`, `name`, `letter`, `description`, `published`) VALUES ('1', 'Navi', 'N', 'Navi is a good aviator and navigator. A very strong and big budgie, almost English', '1') made by activate_plugin, do_action('activate_name-directory/index.php'), WP_Hook->do_action, WP_Hook->apply_filters, name_directory_db_install_demo_data, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_name_directory_name.","level":"FATAL","type":"SQL","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:42:34 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>INSERT INTO `wp_name_directory_name` (`directory`, `name`, `letter`, `description`, `published`) VALUES ('1', 'Mister', 'M', 'Mister is a name which can only be assigned to a typical English Budgie. Big, strong and stringent.', '1')</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: INSERT INTO `wp_name_directory_name` (`directory`, `name`, `letter`, `description`, `published`) VALUES (:param0 , :param1 , :param2 , :param3 , :param4 ) | parameters: 1, Mister, M, Mister is a name which can only be assigned to a typical English Budgie. Big, strong and stringent., 1</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_name_directory_name.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-includes/class-wpdb.php(2614): WP_SQLite_DB->query('INSERT INTO `wp...')\n#2 /wordpress/wp-includes/class-wpdb.php(2503): wpdb->_insert_replace_helper('wp_name_directo...', Array, NULL, 'INSERT')\n#3 /wordpress/wp-content/plugins/name-directory/database.php(140): wpdb->insert('wp_name_directo...', Array)\n#4 /wordpress/wp-includes/class-wp-hook.php(324): name_directory_db_install_demo_data(false)\n#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_name-d...', false)\n#8 /internal/eval.php(20): activate_plugin('name-directory/...')\n#9 {main}</pre>\n for query INSERT INTO `wp_name_directory_name` (`directory`, `name`, `letter`, `description`, `published`) VALUES ('1', 'Mister', 'M', 'Mister is a name which can only be assigned to a typical English Budgie. Big, strong and stringent.', '1') made by activate_plugin, do_action('activate_name-directory/index.php'), WP_Hook->do_action, WP_Hook->apply_filters, name_directory_db_install_demo_data, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"SQLSTATE[HY000]: General error: 1 no such table: wp_name_directory_name.","level":"FATAL","type":"SQL","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:42:34 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>INSERT INTO `wp_name_directory_name` (`directory`, `name`, `letter`, `description`, `published`) VALUES ('1', 'Isa', 'I', 'Isa is a direct descent of Mister. As a fullblood daughter she is also a typical English Budgie.', '1')</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: INSERT INTO `wp_name_directory_name` (`directory`, `name`, `letter`, `description`, `published`) VALUES (:param0 , :param1 , :param2 , :param3 , :param4 ) | parameters: 1, Isa, I, Isa is a direct descent of Mister. As a fullblood daughter she is also a typical English Budgie., 1</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_name_directory_name.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-includes/class-wpdb.php(2614): WP_SQLite_DB->query('INSERT INTO `wp...')\n#2 /wordpress/wp-includes/class-wpdb.php(2503): wpdb->_insert_replace_helper('wp_name_directo...', Array, NULL, 'INSERT')\n#3 /wordpress/wp-content/plugins/name-directory/database.php(147): wpdb->insert('wp_name_directo...', Array)\n#4 /wordpress/wp-includes/class-wp-hook.php(324): name_directory_db_install_demo_data(false)\n#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_name-d...', false)\n#8 /internal/eval.php(20): activate_plugin('name-directory/...')\n#9 {main}</pre>\n for query INSERT INTO `wp_name_directory_name` (`directory`, `name`, `letter`, `description`, `published`) VALUES ('1', 'Isa', 'I', 'Isa is a direct descent of Mister. As a fullblood daughter she is also a typical English Budgie.', '1') made by activate_plugin, do_action('activate_name-directory/index.php'), WP_Hook->do_action, WP_Hook->apply_filters, name_directory_db_install_demo_data, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"Unknown operation: CONVERT.","level":"FATAL","type":"SQL","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:42:34 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE wp_name_directory CONVERT TO CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci';</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown operation: CONVERT.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/name-directory/database.php(78): WP_SQLite_DB->query('ALTER TABLE wp_...')\n#2 /wordpress/wp-content/plugins/name-directory/database.php(154): name_directory_db_post_update_actions()\n#3 /wordpress/wp-includes/class-wp-hook.php(324): name_directory_db_install_demo_data(false)\n#4 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#5 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#6 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_name-d...', false)\n#7 /internal/eval.php(20): activate_plugin('name-directory/...')\n#8 {main}</pre>\n for query ALTER TABLE wp_name_directory CONVERT TO CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci'; made by activate_plugin, do_action('activate_name-directory/index.php'), WP_Hook->do_action, WP_Hook->apply_filters, name_directory_db_install_demo_data, name_directory_db_post_update_actions, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/p/posts-of-today/error.json"}
,
{"message":"Unknown operation: CONVERT.","level":"FATAL","type":"SQL","test":"ast-sqlite-boot","plugin":"posts-of-today","details":"[27-Apr-2025 06:42:34 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE wp_name_directory_name CONVERT TO CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci';</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown operation: CONVERT.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/name-directory/database.php(81): WP_SQLite_DB->query('ALTER TABLE wp_...')\n#2 /wordpress/wp-content/plugins/name-directory/database.php(154): name_directory_db_post_update_actions()\n#3 /wordpress/wp-includes/class-wp-hook.php(324): name_directory_db_install_demo_data(false)\n#4 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#5 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#6 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_name-d...', false)\n#7 /internal/eval.php(20): activate_plugin('name-directory/...')\n#8 {main}</pre>\n for query ALTER TABLE wp_name_directory_name CONVERT TO CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci'; made by activate_plugin, do_action('activate_name-directory/index.php'), WP_Hook->do_action, WP_Hook->apply_filters, name_directory_db_install_demo_data, name_directory_db_post_update_actions, WP_SQLite_DB->query, WP_SQLite_DB->print_error\n\n    at Object.onBind (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async V (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:64:10)\n    at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {\n  [cause]: Error: Error when executing the blueprint step #5 ({\"step\":\"installPlugin\",\"pluginData\":{\"resource\":\"wordpress.org/plugins\",\"slug\":\"posts-of-today\"},\"options\":{\"activate\":true}}) : Could not download \"https://downloads.wordpress.org/plugin/posts-of-today.latest-stable.zip\".\n  \t\t\t\tCheck if the URL is correct and the server is reachable.\n  \t\t\t\tIf it is reachable, the server might be blocking the request.\n  \t\t\t\tCheck the browser console and network tabs for more information.\n  \n  \t\t\t\t## Does the console show the error \"No 'Access-Control-Allow-Origin' header\"?\n  \n  \t\t\t\tThis means the server that hosts your file does not allow requests from other sites\n  \t\t\t\t(cross-origin requests, or CORS).\tYou need to move the asset to a server that allows\n  \t\t\t\tcross-origin file downloads. Learn more about CORS at\n  \t\t\t\thttps://developer.mozilla.org/en-US/docs/Web/HTTP/CORS.\n  \n  \t\t\t\tIf your file is on GitHub, load it from \"raw.githubusercontent.com\".\n  \t\t\t\tHere's how to do that:\n  \n  \t\t\t\t1. Start with the original GitHub URL of the file. For example:\n  \t\t\t\thttps://github.com/username/repository/blob/branch/filename.\n  \t\t\t\t2. Replace \"github.com\" with \"raw.githubusercontent.com\".\n  \t\t\t\t3. Remove the \"/blob/\" part of the URL.\n  \n  \t\t\t\tThe resulting URL should look like this:\n  \t\t\t\thttps://raw.githubusercontent.com/username/repository/branch/filename\n  \n  \t\t\t\tError:\n  \t\t\t\tError: Could not download \"https://downloads.wordpress.org/plugin/posts-of-today.latest-stable.zip\"\n      at Object.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12449:19)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async ms (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12552:3)\n      at async Object.onBind (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:227:48)\n      at async V (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:64:10)\n      at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {\n    [cause]: Error: Could not download \"https://downloads.wordpress.org/plugin/posts-of-today.latest-stable.zip\".\n    \t\t\t\tCheck if the URL is correct and the server is reachable.\n    \t\t\t\tIf it is reachable, the server might be blocking the request.\n    \t\t\t\tCheck the browser console and network tabs for more information.\n    \n    \t\t\t\t## Does the console show the error \"No 'Access-Control-Allow-Origin' header\"?\n    \n    \t\t\t\tThis means the server that hosts your file does not allow requests from other sites\n    \t\t\t\t(cross-origin requests, or CORS).\tYou need to move the asset to a server that allows\n    \t\t\t\tcross-origin file downloads. Learn more about CORS at\n    \t\t\t\thttps://developer.mozilla.org/en-US/docs/Web/HTTP/CORS.\n    \n    \t\t\t\tIf your file is on GitHub, load it from \"raw.githubusercontent.com\".\n    \t\t\t\tHere's how to do that:\n    \n    \t\t\t\t1. Start with the original GitHub URL of the file. For example:\n    \t\t\t\thttps://github.com/username/repository/blob/branch/filename.\n    \t\t\t\t2. Replace \"github.com\" with \"raw.githubusercontent.com\".\n    \t\t\t\t3. Remove the \"/blob/\" part of the URL.\n    \n    \t\t\t\tThe resulting URL should look like this:\n    \t\t\t\thttps://raw.githubusercontent.com/username/repository/branch/filename\n    \n    \t\t\t\tError:\n    \t\t\t\tError: Could not download \"https://downloads.wordpress.org/plugin/posts-of-today.latest-stable.zip\"\n        at Ct.resolve (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:1472:13)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async _.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@php-wasm/util/index.js:45:14)\n  }\n}\n\n","log":"/logs/plugins/p/posts-of-today/error.json"}
]
