file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237
        throw new Error(y, { cause: u });
              ^

Error: [17-May-2025 14:48:02 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>CREATE TABLE IF NOT EXISTS wp_url_parse(
	  id mediumint(10) NOT NULL AUTO_INCREMENT,
	  url VARCHAR(60) NOT NULL,
	  tag VARCHAR(60) NOT NULL,
	  UNIQUE KEY id (url,tag),
	  PRIMARY KEY id (id)
	)DEFAULT CHARACTER SET = utf8,
	  COLLATE = utf8_general_ci</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: Cannot combine AUTOINCREMENT and multiple primary keys in SQLite.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-admin/includes/upgrade.php(3280): WP_SQLite_DB->query('CREATE TABLE IF...')
#2 /wordpress/wp-content/plugins/parse-url/url-parse-plugin.php(505): dbDelta(Array)
#3 /wordpress/wp-includes/class-wp-hook.php(324): create_table(false)
#4 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#5 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_parse-...', false)
#7 /internal/eval.php(20): activate_plugin('parse-url/url-p...')
#8 {main}</pre>
 for query CREATE TABLE IF NOT EXISTS wp_url_parse(
	  id mediumint(10) NOT NULL AUTO_INCREMENT,
	  url VARCHAR(60) NOT NULL,
	  tag VARCHAR(60) NOT NULL,
	  UNIQUE KEY id (url,tag),
	  PRIMARY KEY id (id)
	)DEFAULT CHARACTER SET = utf8,
	  COLLATE = utf8_general_ci made by activate_plugin, do_action('activate_parse-url/url-parse-plugin.php'), WP_Hook->do_action, WP_Hook->apply_filters, create_table, dbDelta, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[17-May-2025 14:48:02 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>INSERT INTO `wp_url_parse` (`url`, `tag`) VALUES ('timesofindia.indiatimes.com', 'div class=Normal')</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: INSERT INTO `wp_url_parse` (`url`, `tag`) VALUES (:param0 , :param1 ) | parameters: timesofindia.indiatimes.com, div class=Normal</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_url_parse.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-includes/class-wpdb.php(2614): WP_SQLite_DB->query('INSERT INTO `wp...')
#2 /wordpress/wp-includes/class-wpdb.php(2503): wpdb->_insert_replace_helper('wp_url_parse', Array, NULL, 'INSERT')
#3 /wordpress/wp-content/plugins/parse-url/url-parse-plugin.php(520): wpdb->insert('wp_url_parse', Array)
#4 /wordpress/wp-includes/class-wp-hook.php(324): add_initial_data(false)
#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_parse-...', false)
#8 /internal/eval.php(20): activate_plugin('parse-url/url-p...')
#9 {main}</pre>
 for query INSERT INTO `wp_url_parse` (`url`, `tag`) VALUES ('timesofindia.indiatimes.com', 'div class=Normal') made by activate_plugin, do_action('activate_parse-url/url-parse-plugin.php'), WP_Hook->do_action, WP_Hook->apply_filters, add_initial_data, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[17-May-2025 14:48:02 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>INSERT INTO `wp_url_parse` (`url`, `tag`) VALUES ('economictimes.indiatimes.com', 'div class=Normal')</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: INSERT INTO `wp_url_parse` (`url`, `tag`) VALUES (:param0 , :param1 ) | parameters: economictimes.indiatimes.com, div class=Normal</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_url_parse.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-includes/class-wpdb.php(2614): WP_SQLite_DB->query('INSERT INTO `wp...')
#2 /wordpress/wp-includes/class-wpdb.php(2503): wpdb->_insert_replace_helper('wp_url_parse', Array, NULL, 'INSERT')
#3 /wordpress/wp-content/plugins/parse-url/url-parse-plugin.php(528): wpdb->insert('wp_url_parse', Array)
#4 /wordpress/wp-includes/class-wp-hook.php(324): add_initial_data(false)
#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_parse-...', false)
#8 /internal/eval.php(20): activate_plugin('parse-url/url-p...')
#9 {main}</pre>
 for query INSERT INTO `wp_url_parse` (`url`, `tag`) VALUES ('economictimes.indiatimes.com', 'div class=Normal') made by activate_plugin, do_action('activate_parse-url/url-parse-plugin.php'), WP_Hook->do_action, WP_Hook->apply_filters, add_initial_data, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[17-May-2025 14:48:02 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>INSERT INTO `wp_url_parse` (`url`, `tag`) VALUES ('www.indiatimes.com', 'div class=lftcolum2 plusFont')</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: INSERT INTO `wp_url_parse` (`url`, `tag`) VALUES (:param0 , :param1 ) | parameters: www.indiatimes.com, div class=lftcolum2 plusFont</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_url_parse.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-includes/class-wpdb.php(2614): WP_SQLite_DB->query('INSERT INTO `wp...')
#2 /wordpress/wp-includes/class-wpdb.php(2503): wpdb->_insert_replace_helper('wp_url_parse', Array, NULL, 'INSERT')
#3 /wordpress/wp-content/plugins/parse-url/url-parse-plugin.php(536): wpdb->insert('wp_url_parse', Array)
#4 /wordpress/wp-includes/class-wp-hook.php(324): add_initial_data(false)
#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_parse-...', false)
#8 /internal/eval.php(20): activate_plugin('parse-url/url-p...')
#9 {main}</pre>
 for query INSERT INTO `wp_url_parse` (`url`, `tag`) VALUES ('www.indiatimes.com', 'div class=lftcolum2 plusFont') made by activate_plugin, do_action('activate_parse-url/url-parse-plugin.php'), WP_Hook->do_action, WP_Hook->apply_filters, add_initial_data, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[17-May-2025 14:48:10 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>CREATE TABLE IF NOT EXISTS wp_url_parse(
	  id mediumint(10) NOT NULL AUTO_INCREMENT,
	  url VARCHAR(60) NOT NULL,
	  tag VARCHAR(60) NOT NULL,
	  UNIQUE KEY id (url,tag),
	  PRIMARY KEY id (id)
	)DEFAULT CHARACTER SET = utf8,
	  COLLATE = utf8_general_ci</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: Cannot combine AUTOINCREMENT and multiple primary keys in SQLite.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-admin/includes/upgrade.php(3280): WP_SQLite_DB->query('CREATE TABLE IF...')
#2 /wordpress/wp-content/plugins/parse-url/url-parse-plugin.php(505): dbDelta(Array)
#3 /wordpress/wp-includes/class-wp-hook.php(324): create_table(false)
#4 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#5 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_parse-...', false)
#7 /internal/eval.php(20): activate_plugin('parse-url/url-p...')
#8 {main}</pre>
 for query CREATE TABLE IF NOT EXISTS wp_url_parse(
	  id mediumint(10) NOT NULL AUTO_INCREMENT,
	  url VARCHAR(60) NOT NULL,
	  tag VARCHAR(60) NOT NULL,
	  UNIQUE KEY id (url,tag),
	  PRIMARY KEY id (id)
	)DEFAULT CHARACTER SET = utf8,
	  COLLATE = utf8_general_ci made by activate_plugin, do_action('activate_parse-url/url-parse-plugin.php'), WP_Hook->do_action, WP_Hook->apply_filters, create_table, dbDelta, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[17-May-2025 14:48:10 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>INSERT INTO `wp_url_parse` (`url`, `tag`) VALUES ('timesofindia.indiatimes.com', 'div class=Normal')</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: INSERT INTO `wp_url_parse` (`url`, `tag`) VALUES (:param0 , :param1 ) | parameters: timesofindia.indiatimes.com, div class=Normal</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_url_parse.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-includes/class-wpdb.php(2614): WP_SQLite_DB->query('INSERT INTO `wp...')
#2 /wordpress/wp-includes/class-wpdb.php(2503): wpdb->_insert_replace_helper('wp_url_parse', Array, NULL, 'INSERT')
#3 /wordpress/wp-content/plugins/parse-url/url-parse-plugin.php(520): wpdb->insert('wp_url_parse', Array)
#4 /wordpress/wp-includes/class-wp-hook.php(324): add_initial_data(false)
#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_parse-...', false)
#8 /internal/eval.php(20): activate_plugin('parse-url/url-p...')
#9 {main}</pre>
 for query INSERT INTO `wp_url_parse` (`url`, `tag`) VALUES ('timesofindia.indiatimes.com', 'div class=Normal') made by activate_plugin, do_action('activate_parse-url/url-parse-plugin.php'), WP_Hook->do_action, WP_Hook->apply_filters, add_initial_data, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[17-May-2025 14:48:10 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>INSERT INTO `wp_url_parse` (`url`, `tag`) VALUES ('economictimes.indiatimes.com', 'div class=Normal')</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: INSERT INTO `wp_url_parse` (`url`, `tag`) VALUES (:param0 , :param1 ) | parameters: economictimes.indiatimes.com, div class=Normal</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_url_parse.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-includes/class-wpdb.php(2614): WP_SQLite_DB->query('INSERT INTO `wp...')
#2 /wordpress/wp-includes/class-wpdb.php(2503): wpdb->_insert_replace_helper('wp_url_parse', Array, NULL, 'INSERT')
#3 /wordpress/wp-content/plugins/parse-url/url-parse-plugin.php(528): wpdb->insert('wp_url_parse', Array)
#4 /wordpress/wp-includes/class-wp-hook.php(324): add_initial_data(false)
#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_parse-...', false)
#8 /internal/eval.php(20): activate_plugin('parse-url/url-p...')
#9 {main}</pre>
 for query INSERT INTO `wp_url_parse` (`url`, `tag`) VALUES ('economictimes.indiatimes.com', 'div class=Normal') made by activate_plugin, do_action('activate_parse-url/url-parse-plugin.php'), WP_Hook->do_action, WP_Hook->apply_filters, add_initial_data, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[17-May-2025 14:48:10 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>INSERT INTO `wp_url_parse` (`url`, `tag`) VALUES ('www.indiatimes.com', 'div class=lftcolum2 plusFont')</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: INSERT INTO `wp_url_parse` (`url`, `tag`) VALUES (:param0 , :param1 ) | parameters: www.indiatimes.com, div class=lftcolum2 plusFont</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_url_parse.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-includes/class-wpdb.php(2614): WP_SQLite_DB->query('INSERT INTO `wp...')
#2 /wordpress/wp-includes/class-wpdb.php(2503): wpdb->_insert_replace_helper('wp_url_parse', Array, NULL, 'INSERT')
#3 /wordpress/wp-content/plugins/parse-url/url-parse-plugin.php(536): wpdb->insert('wp_url_parse', Array)
#4 /wordpress/wp-includes/class-wp-hook.php(324): add_initial_data(false)
#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_parse-...', false)
#8 /internal/eval.php(20): activate_plugin('parse-url/url-p...')
#9 {main}</pre>
 for query INSERT INTO `wp_url_parse` (`url`, `tag`) VALUES ('www.indiatimes.com', 'div class=lftcolum2 plusFont') made by activate_plugin, do_action('activate_parse-url/url-parse-plugin.php'), WP_Hook->do_action, WP_Hook->apply_filters, add_initial_data, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[17-May-2025 14:51:03 UTC] PHP Fatal error:  Uncaught Error: Undefined constant "querydb_TITLESTRING" in /wordpress/wp-content/plugins/querydb/querydb.php:12
Stack trace:
#0 /wordpress/wp-admin/includes/plugin.php(2387): include_once()
#1 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('querydb/querydb...')
#2 /internal/eval.php(20): activate_plugin('querydb/querydb...')
#3 {main}
  thrown in /wordpress/wp-content/plugins/querydb/querydb.php on line 12
[17-May-2025 14:51:11 UTC] PHP Fatal error:  Uncaught Error: Undefined constant "querydb_TITLESTRING" in /wordpress/wp-content/plugins/querydb/querydb.php:12
Stack trace:
#0 /wordpress/wp-admin/includes/plugin.php(2387): include_once()
#1 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('querydb/querydb...')
#2 /internal/eval.php(20): activate_plugin('querydb/querydb...')
#3 {main}
  thrown in /wordpress/wp-content/plugins/querydb/querydb.php on line 12

    at Object.onBind (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async V (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:64:10)
    at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {
  [cause]: Error: Error when executing the blueprint step #1 ({"step":"installPlugin","pluginData":{"resource":"wordpress.org/plugins","slug":"querydb"},"options":{"activate":true}}) : PHP.run() failed with exit code 255 and the following output: 
      at Object.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12449:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async ms (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12552:3)
      ... 2 lines matching cause stack trace ...
      at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {
    [cause]: PHPExecutionFailureError: PHP.run() failed with exit code 255 and the following output: 
        at PHP.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@php-wasm/universal/index.js:987:19)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async wr (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:33:39)
        at async Object.gt [as installPlugin] (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:974:42)
        at async g (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12517:30)
        at async Object.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12446:23)
        at async ms (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12552:3)
        at async Object.onBind (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:227:48)
        at async V (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:64:10)
        at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {
      response: PHPResponse {
        httpStatusCode: 500,
        headers: {
          'x-powered-by': [ 'PHP/8.0.30-dev' ],
          'content-type': [ 'text/html; charset=UTF-8' ]
        },
        bytes: Uint8Array(0) [],
        exitCode: 255,
        errors: ''
      },
      source: 'request'
    }
  }
}

Node.js v23.11.0
