file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237
        throw new Error(y, { cause: u });
              ^

Error: [12-Apr-2025 04:52:02 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>LOAD DATA LOCAL INFILE '/wordpress/wp-content/plugins/thalaivarin-sinthanai/data/sinthanai.txt' INTO TABLE wp_sinthanai CHARACTER SET UTF8 COLUMNS TERMINATED BY '	' ENCLOSED BY '"' LINES TERMINATED BY '
'</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
MySQL query not supported. Cause: statement type: "loadStatement"
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php(690): WP_SQLite_Driver->new_driver_exception('MySQL query not...', 0, Object(WP_SQLite_Driver_Exception))
#1 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(472): WP_SQLite_Driver->query('LOAD DATA LOCAL...')
#2 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(413): WP_SQLite_DB->_do_query('LOAD DATA LOCAL...')
#3 /wordpress/wp-content/plugins/thalaivarin-sinthanai/Sinthanai.php(63): WP_SQLite_DB->query('LOAD DATA LOCAL...')
#4 /wordpress/wp-includes/class-wp-hook.php(324): sinthanai_install(false)
#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_thalai...', false)
#8 /internal/eval.php(20): activate_plugin('thalaivarin-sin...')
#9 {main}</pre>
 for query LOAD DATA LOCAL INFILE '/wordpress/wp-content/plugins/thalaivarin-sinthanai/data/sinthanai.txt' INTO TABLE wp_sinthanai CHARACTER SET UTF8 COLUMNS TERMINATED BY '	' ENCLOSED BY '"' LINES TERMINATED BY '
' made by activate_plugin, do_action('activate_thalaivarin-sinthanai/Sinthanai.php'), WP_Hook->do_action, WP_Hook->apply_filters, sinthanai_install, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[12-Apr-2025 04:52:10 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>LOAD DATA LOCAL INFILE '/wordpress/wp-content/plugins/thalaivarin-sinthanai/data/sinthanai.txt' INTO TABLE wp_sinthanai CHARACTER SET UTF8 COLUMNS TERMINATED BY '	' ENCLOSED BY '"' LINES TERMINATED BY '
'</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown query type: LOAD DATA.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-content/plugins/thalaivarin-sinthanai/Sinthanai.php(63): WP_SQLite_DB->query('LOAD DATA LOCAL...')
#2 /wordpress/wp-includes/class-wp-hook.php(324): sinthanai_install(false)
#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_thalai...', false)
#6 /internal/eval.php(20): activate_plugin('thalaivarin-sin...')
#7 {main}</pre>
 for query LOAD DATA LOCAL INFILE '/wordpress/wp-content/plugins/thalaivarin-sinthanai/data/sinthanai.txt' INTO TABLE wp_sinthanai CHARACTER SET UTF8 COLUMNS TERMINATED BY '	' ENCLOSED BY '"' LINES TERMINATED BY '
' made by activate_plugin, do_action('activate_thalaivarin-sinthanai/Sinthanai.php'), WP_Hook->do_action, WP_Hook->apply_filters, sinthanai_install, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[12-Apr-2025 04:52:18 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>LOAD DATA LOCAL INFILE '/wordpress/wp-content/plugins/thalaivarin-sinthanai/data/sinthanai.txt' INTO TABLE wp_sinthanai CHARACTER SET UTF8 COLUMNS TERMINATED BY '	' ENCLOSED BY '"' LINES TERMINATED BY '
'</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown query type: LOAD DATA.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-content/plugins/thalaivarin-sinthanai/Sinthanai.php(63): WP_SQLite_DB->query('LOAD DATA LOCAL...')
#2 /wordpress/wp-includes/class-wp-hook.php(324): sinthanai_install(false)
#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_thalai...', false)
#6 /internal/eval.php(20): activate_plugin('thalaivarin-sin...')
#7 {main}</pre>
 for query LOAD DATA LOCAL INFILE '/wordpress/wp-content/plugins/thalaivarin-sinthanai/data/sinthanai.txt' INTO TABLE wp_sinthanai CHARACTER SET UTF8 COLUMNS TERMINATED BY '	' ENCLOSED BY '"' LINES TERMINATED BY '
' made by activate_plugin, do_action('activate_thalaivarin-sinthanai/Sinthanai.php'), WP_Hook->do_action, WP_Hook->apply_filters, sinthanai_install, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[12-Apr-2025 04:55:27 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function create_function() in /wordpress/wp-content/plugins/total-wp-reviews/total-reviews.php:42
Stack trace:
#0 /wordpress/wp-admin/includes/plugin.php(2387): include_once()
#1 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('total-wp-review...')
#2 /internal/eval.php(20): activate_plugin('total-wp-review...')
#3 {main}
  thrown in /wordpress/wp-content/plugins/total-wp-reviews/total-reviews.php on line 42
[12-Apr-2025 04:55:35 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function create_function() in /wordpress/wp-content/plugins/total-wp-reviews/total-reviews.php:42
Stack trace:
#0 /wordpress/wp-admin/includes/plugin.php(2387): include_once()
#1 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('total-wp-review...')
#2 /internal/eval.php(20): activate_plugin('total-wp-review...')
#3 {main}
  thrown in /wordpress/wp-content/plugins/total-wp-reviews/total-reviews.php on line 42
[12-Apr-2025 04:55:43 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function create_function() in /wordpress/wp-content/plugins/total-wp-reviews/total-reviews.php:42
Stack trace:
#0 /wordpress/wp-admin/includes/plugin.php(2387): include_once()
#1 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('total-wp-review...')
#2 /internal/eval.php(20): activate_plugin('total-wp-review...')
#3 {main}
  thrown in /wordpress/wp-content/plugins/total-wp-reviews/total-reviews.php on line 42

    at Object.onBind (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async V (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:64:10)
    at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {
  [cause]: Error: Error when executing the blueprint step #5 ({"step":"installPlugin","pluginData":{"resource":"wordpress.org/plugins","slug":"traffic-conditions-uk"},"options":{"activate":true}}) : Could not download "https://downloads.wordpress.org/plugin/traffic-conditions-uk.latest-stable.zip".
  				Check if the URL is correct and the server is reachable.
  				If it is reachable, the server might be blocking the request.
  				Check the browser console and network tabs for more information.
  
  				## Does the console show the error "No 'Access-Control-Allow-Origin' header"?
  
  				This means the server that hosts your file does not allow requests from other sites
  				(cross-origin requests, or CORS).	You need to move the asset to a server that allows
  				cross-origin file downloads. Learn more about CORS at
  				https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS.
  
  				If your file is on GitHub, load it from "raw.githubusercontent.com".
  				Here's how to do that:
  
  				1. Start with the original GitHub URL of the file. For example:
  				https://github.com/username/repository/blob/branch/filename.
  				2. Replace "github.com" with "raw.githubusercontent.com".
  				3. Remove the "/blob/" part of the URL.
  
  				The resulting URL should look like this:
  				https://raw.githubusercontent.com/username/repository/branch/filename
  
  				Error:
  				Error: Could not download "https://downloads.wordpress.org/plugin/traffic-conditions-uk.latest-stable.zip"
      at Object.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12449:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async ms (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12552:3)
      at async Object.onBind (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:227:48)
      at async V (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:64:10)
      at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {
    [cause]: Error: Could not download "https://downloads.wordpress.org/plugin/traffic-conditions-uk.latest-stable.zip".
    				Check if the URL is correct and the server is reachable.
    				If it is reachable, the server might be blocking the request.
    				Check the browser console and network tabs for more information.
    
    				## Does the console show the error "No 'Access-Control-Allow-Origin' header"?
    
    				This means the server that hosts your file does not allow requests from other sites
    				(cross-origin requests, or CORS).	You need to move the asset to a server that allows
    				cross-origin file downloads. Learn more about CORS at
    				https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS.
    
    				If your file is on GitHub, load it from "raw.githubusercontent.com".
    				Here's how to do that:
    
    				1. Start with the original GitHub URL of the file. For example:
    				https://github.com/username/repository/blob/branch/filename.
    				2. Replace "github.com" with "raw.githubusercontent.com".
    				3. Remove the "/blob/" part of the URL.
    
    				The resulting URL should look like this:
    				https://raw.githubusercontent.com/username/repository/branch/filename
    
    				Error:
    				Error: Could not download "https://downloads.wordpress.org/plugin/traffic-conditions-uk.latest-stable.zip"
        at Ct.resolve (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:1472:13)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async _.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@php-wasm/util/index.js:45:14)
  }
}

Node.js v23.11.0
