[
  {
    "message": "file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237\n        throw new Error(y, { cause: u });\n              ^\n",
    "level": "FATAL",
    "type": "PLAYGROUND",
    "test": "ast-sqlite-boot",
    "plugin": "seopilotpl-dla-wordpress",
    "details": "file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237\n        throw new Error(y, { cause: u });\n              ^\n",
    "log": "/tmp/tmp.WvUFcLihJK"
  },
  {
    "message": "SQLSTATE[HY000]: General error: 1 no such table: wp_securio_bf_bans.",
    "level": "FATAL",
    "type": "SQL",
    "test": "ast-sqlite-boot",
    "plugin": "seopilotpl-dla-wordpress",
    "details": "[10-May-2025 13:50:07 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>DELETE FROM wp_securio_bf_bans WHERE date_added < 1745675407</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: DELETE FROM wp_securio_bf_bans WHERE date_added &lt; 1745675407 | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_securio_bf_bans.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(182): WP_SQLite_DB->query('DELETE FROM wp_...')\n#2 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(165): Securio_WPLogin->cleanup()\n#3 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(76): Securio_WPLogin->__construct()\n#4 /wordpress/wp-admin/includes/plugin.php(2387): include_once('/wordpress/wp-c...')\n#5 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('securio-wplogin...')\n#6 /internal/eval.php(20): activate_plugin('securio-wplogin...')\n#7 {main}</pre>\n for query DELETE FROM wp_securio_bf_bans WHERE date_added < 1745675407 made by activate_plugin, plugin_sandbox_scrape, include_once('/plugins/securio-wplogin/securio-wplogin.php'), Securio_WPLogin->__construct, Securio_WPLogin->cleanup, WP_SQLite_DB->query, WP_SQLite_DB->print_error",
    "log": "/logs/plugins/s/seopilotpl-dla-wordpress/error.json"
  },
  {
    "message": "SQLSTATE[HY000]: General error: 1 no such table: wp_securio_bf_fails.",
    "level": "FATAL",
    "type": "SQL",
    "test": "ast-sqlite-boot",
    "plugin": "seopilotpl-dla-wordpress",
    "details": "[10-May-2025 13:50:07 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>DELETE FROM wp_securio_bf_fails WHERE date_added < 1745675407</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: DELETE FROM wp_securio_bf_fails WHERE date_added &lt; 1745675407 | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_securio_bf_fails.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(186): WP_SQLite_DB->query('DELETE FROM wp_...')\n#2 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(165): Securio_WPLogin->cleanup()\n#3 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(76): Securio_WPLogin->__construct()\n#4 /wordpress/wp-admin/includes/plugin.php(2387): include_once('/wordpress/wp-c...')\n#5 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('securio-wplogin...')\n#6 /internal/eval.php(20): activate_plugin('securio-wplogin...')\n#7 {main}</pre>\n for query DELETE FROM wp_securio_bf_fails WHERE date_added < 1745675407 made by activate_plugin, plugin_sandbox_scrape, include_once('/plugins/securio-wplogin/securio-wplogin.php'), Securio_WPLogin->__construct, Securio_WPLogin->cleanup, WP_SQLite_DB->query, WP_SQLite_DB->print_error",
    "log": "/logs/plugins/s/seopilotpl-dla-wordpress/error.json"
  },
  {
    "message": "SQLSTATE[HY000]: General error: 1 no such table: wp_securio_bf_bans.",
    "level": "FATAL",
    "type": "SQL",
    "test": "ast-sqlite-boot",
    "plugin": "seopilotpl-dla-wordpress",
    "details": "[10-May-2025 13:50:16 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>DELETE FROM wp_securio_bf_bans WHERE date_added < 1745675416</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: DELETE FROM wp_securio_bf_bans WHERE date_added &lt; 1745675416 | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_securio_bf_bans.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(182): WP_SQLite_DB->query('DELETE FROM wp_...')\n#2 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(165): Securio_WPLogin->cleanup()\n#3 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(76): Securio_WPLogin->__construct()\n#4 /wordpress/wp-admin/includes/plugin.php(2387): include_once('/wordpress/wp-c...')\n#5 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('securio-wplogin...')\n#6 /internal/eval.php(20): activate_plugin('securio-wplogin...')\n#7 {main}</pre>\n for query DELETE FROM wp_securio_bf_bans WHERE date_added < 1745675416 made by activate_plugin, plugin_sandbox_scrape, include_once('/plugins/securio-wplogin/securio-wplogin.php'), Securio_WPLogin->__construct, Securio_WPLogin->cleanup, WP_SQLite_DB->query, WP_SQLite_DB->print_error",
    "log": "/logs/plugins/s/seopilotpl-dla-wordpress/error.json"
  },
  {
    "message": "SQLSTATE[HY000]: General error: 1 no such table: wp_securio_bf_fails.",
    "level": "FATAL",
    "type": "SQL",
    "test": "ast-sqlite-boot",
    "plugin": "seopilotpl-dla-wordpress",
    "details": "[10-May-2025 13:50:16 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>DELETE FROM wp_securio_bf_fails WHERE date_added < 1745675416</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: DELETE FROM wp_securio_bf_fails WHERE date_added &lt; 1745675416 | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_securio_bf_fails.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(186): WP_SQLite_DB->query('DELETE FROM wp_...')\n#2 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(165): Securio_WPLogin->cleanup()\n#3 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(76): Securio_WPLogin->__construct()\n#4 /wordpress/wp-admin/includes/plugin.php(2387): include_once('/wordpress/wp-c...')\n#5 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('securio-wplogin...')\n#6 /internal/eval.php(20): activate_plugin('securio-wplogin...')\n#7 {main}</pre>\n for query DELETE FROM wp_securio_bf_fails WHERE date_added < 1745675416 made by activate_plugin, plugin_sandbox_scrape, include_once('/plugins/securio-wplogin/securio-wplogin.php'), Securio_WPLogin->__construct, Securio_WPLogin->cleanup, WP_SQLite_DB->query, WP_SQLite_DB->print_error",
    "log": "/logs/plugins/s/seopilotpl-dla-wordpress/error.json"
  },
  {
    "message": "Uncaught Error: Call to undefined function create_function() in /wordpress/wp-content/plugins/seopilotpl-dla-wordpress/spdwp.php:374",
    "level": "FATAL",
    "type": "PHP",
    "test": "ast-sqlite-boot",
    "plugin": "seopilotpl-dla-wordpress",
    "details": "[10-May-2025 13:50:24 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function create_function() in /wordpress/wp-content/plugins/seopilotpl-dla-wordpress/spdwp.php:374\nStack trace:\n#0 /wordpress/wp-admin/includes/plugin.php(2387): include_once()\n#1 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('seopilotpl-dla-...')\n#2 /internal/eval.php(20): activate_plugin('seopilotpl-dla-...')\n#3 {main}\n  thrown in /wordpress/wp-content/plugins/seopilotpl-dla-wordpress/spdwp.php on line 374\n\n    at Object.onBind (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async V (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:64:10)\n    at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {\n  [cause]: Error: Error when executing the blueprint step #5 ({\"step\":\"installPlugin\",\"pluginData\":{\"resource\":\"wordpress.org/plugins\",\"slug\":\"seopilotpl-dla-wordpress\"},\"options\":{\"activate\":true}}) : PHP.run() failed with exit code 255 and the following output: \n      at Object.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12449:19)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async ms (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12552:3)\n      ... 2 lines matching cause stack trace ...\n      at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {\n    [cause]: PHPExecutionFailureError: PHP.run() failed with exit code 255 and the following output: \n        at PHP.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@php-wasm/universal/index.js:987:19)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async wr (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:33:39)\n        at async Object.gt [as installPlugin] (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:974:42)\n        at async g (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12517:30)\n        at async Object.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12446:23)\n        at async ms (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12552:3)\n        at async Object.onBind (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:227:48)\n        at async V (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:64:10)\n        at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {\n      response: PHPResponse {\n        httpStatusCode: 500,\n        headers: {\n          'x-powered-by': [ 'PHP/8.0.30-dev' ],\n          'content-type': [ 'text/html; charset=UTF-8' ]\n        },\n        bytes: Uint8Array(0) [],\n        exitCode: 255,\n        errors: ''\n      },\n      source: 'request'\n    }\n  }\n}\n\n",
    "log": "/logs/plugins/s/seopilotpl-dla-wordpress/error.json"
  },
  {
    "message": "file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237\n        throw new Error(y, { cause: u });\n              ^\n",
    "level": "FATAL",
    "type": "PLAYGROUND",
    "test": "asyncify-boot",
    "plugin": "seopilotpl-dla-wordpress",
    "details": "file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237\n        throw new Error(y, { cause: u });\n              ^\n",
    "log": "/tmp/tmp.MXSsHawktF"
  },
  {
    "message": "SQLSTATE[HY000]: General error: 1 no such table: wp_securio_bf_bans.",
    "level": "FATAL",
    "type": "SQL",
    "test": "asyncify-boot",
    "plugin": "seopilotpl-dla-wordpress",
    "details": "[10-May-2025 13:50:07 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>DELETE FROM wp_securio_bf_bans WHERE date_added < 1745675407</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: DELETE FROM wp_securio_bf_bans WHERE date_added &lt; 1745675407 | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_securio_bf_bans.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(182): WP_SQLite_DB->query('DELETE FROM wp_...')\n#2 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(165): Securio_WPLogin->cleanup()\n#3 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(76): Securio_WPLogin->__construct()\n#4 /wordpress/wp-admin/includes/plugin.php(2387): include_once('/wordpress/wp-c...')\n#5 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('securio-wplogin...')\n#6 /internal/eval.php(20): activate_plugin('securio-wplogin...')\n#7 {main}</pre>\n for query DELETE FROM wp_securio_bf_bans WHERE date_added < 1745675407 made by activate_plugin, plugin_sandbox_scrape, include_once('/plugins/securio-wplogin/securio-wplogin.php'), Securio_WPLogin->__construct, Securio_WPLogin->cleanup, WP_SQLite_DB->query, WP_SQLite_DB->print_error",
    "log": "/logs/plugins/s/seopilotpl-dla-wordpress/error.json"
  },
  {
    "message": "SQLSTATE[HY000]: General error: 1 no such table: wp_securio_bf_fails.",
    "level": "FATAL",
    "type": "SQL",
    "test": "asyncify-boot",
    "plugin": "seopilotpl-dla-wordpress",
    "details": "[10-May-2025 13:50:07 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>DELETE FROM wp_securio_bf_fails WHERE date_added < 1745675407</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: DELETE FROM wp_securio_bf_fails WHERE date_added &lt; 1745675407 | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_securio_bf_fails.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(186): WP_SQLite_DB->query('DELETE FROM wp_...')\n#2 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(165): Securio_WPLogin->cleanup()\n#3 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(76): Securio_WPLogin->__construct()\n#4 /wordpress/wp-admin/includes/plugin.php(2387): include_once('/wordpress/wp-c...')\n#5 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('securio-wplogin...')\n#6 /internal/eval.php(20): activate_plugin('securio-wplogin...')\n#7 {main}</pre>\n for query DELETE FROM wp_securio_bf_fails WHERE date_added < 1745675407 made by activate_plugin, plugin_sandbox_scrape, include_once('/plugins/securio-wplogin/securio-wplogin.php'), Securio_WPLogin->__construct, Securio_WPLogin->cleanup, WP_SQLite_DB->query, WP_SQLite_DB->print_error",
    "log": "/logs/plugins/s/seopilotpl-dla-wordpress/error.json"
  },
  {
    "message": "SQLSTATE[HY000]: General error: 1 no such table: wp_securio_bf_bans.",
    "level": "FATAL",
    "type": "SQL",
    "test": "asyncify-boot",
    "plugin": "seopilotpl-dla-wordpress",
    "details": "[10-May-2025 13:50:16 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>DELETE FROM wp_securio_bf_bans WHERE date_added < 1745675416</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: DELETE FROM wp_securio_bf_bans WHERE date_added &lt; 1745675416 | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_securio_bf_bans.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(182): WP_SQLite_DB->query('DELETE FROM wp_...')\n#2 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(165): Securio_WPLogin->cleanup()\n#3 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(76): Securio_WPLogin->__construct()\n#4 /wordpress/wp-admin/includes/plugin.php(2387): include_once('/wordpress/wp-c...')\n#5 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('securio-wplogin...')\n#6 /internal/eval.php(20): activate_plugin('securio-wplogin...')\n#7 {main}</pre>\n for query DELETE FROM wp_securio_bf_bans WHERE date_added < 1745675416 made by activate_plugin, plugin_sandbox_scrape, include_once('/plugins/securio-wplogin/securio-wplogin.php'), Securio_WPLogin->__construct, Securio_WPLogin->cleanup, WP_SQLite_DB->query, WP_SQLite_DB->print_error",
    "log": "/logs/plugins/s/seopilotpl-dla-wordpress/error.json"
  },
  {
    "message": "SQLSTATE[HY000]: General error: 1 no such table: wp_securio_bf_fails.",
    "level": "FATAL",
    "type": "SQL",
    "test": "asyncify-boot",
    "plugin": "seopilotpl-dla-wordpress",
    "details": "[10-May-2025 13:50:16 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>DELETE FROM wp_securio_bf_fails WHERE date_added < 1745675416</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: DELETE FROM wp_securio_bf_fails WHERE date_added &lt; 1745675416 | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_securio_bf_fails.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(186): WP_SQLite_DB->query('DELETE FROM wp_...')\n#2 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(165): Securio_WPLogin->cleanup()\n#3 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(76): Securio_WPLogin->__construct()\n#4 /wordpress/wp-admin/includes/plugin.php(2387): include_once('/wordpress/wp-c...')\n#5 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('securio-wplogin...')\n#6 /internal/eval.php(20): activate_plugin('securio-wplogin...')\n#7 {main}</pre>\n for query DELETE FROM wp_securio_bf_fails WHERE date_added < 1745675416 made by activate_plugin, plugin_sandbox_scrape, include_once('/plugins/securio-wplogin/securio-wplogin.php'), Securio_WPLogin->__construct, Securio_WPLogin->cleanup, WP_SQLite_DB->query, WP_SQLite_DB->print_error",
    "log": "/logs/plugins/s/seopilotpl-dla-wordpress/error.json"
  },
  {
    "message": "Uncaught Error: Call to undefined function create_function() in /wordpress/wp-content/plugins/seopilotpl-dla-wordpress/spdwp.php:374",
    "level": "FATAL",
    "type": "PHP",
    "test": "asyncify-boot",
    "plugin": "seopilotpl-dla-wordpress",
    "details": "[10-May-2025 13:50:24 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function create_function() in /wordpress/wp-content/plugins/seopilotpl-dla-wordpress/spdwp.php:374\nStack trace:\n#0 /wordpress/wp-admin/includes/plugin.php(2387): include_once()\n#1 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('seopilotpl-dla-...')\n#2 /internal/eval.php(20): activate_plugin('seopilotpl-dla-...')\n#3 {main}\n  thrown in /wordpress/wp-content/plugins/seopilotpl-dla-wordpress/spdwp.php on line 374",
    "log": "/logs/plugins/s/seopilotpl-dla-wordpress/error.json"
  },
  {
    "message": "Uncaught Error: Call to undefined function create_function() in /wordpress/wp-content/plugins/seopilotpl-dla-wordpress/spdwp.php:374",
    "level": "FATAL",
    "type": "PHP",
    "test": "asyncify-boot",
    "plugin": "seopilotpl-dla-wordpress",
    "details": "[10-May-2025 13:50:32 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function create_function() in /wordpress/wp-content/plugins/seopilotpl-dla-wordpress/spdwp.php:374\nStack trace:\n#0 /wordpress/wp-admin/includes/plugin.php(2387): include_once()\n#1 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('seopilotpl-dla-...')\n#2 /internal/eval.php(20): activate_plugin('seopilotpl-dla-...')\n#3 {main}\n  thrown in /wordpress/wp-content/plugins/seopilotpl-dla-wordpress/spdwp.php on line 374\n\n    at Object.onBind (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async V (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:64:10)\n    at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {\n  [cause]: Error: Error when executing the blueprint step #1 ({\"step\":\"installPlugin\",\"pluginData\":{\"resource\":\"wordpress.org/plugins\",\"slug\":\"seopilotpl-dla-wordpress\"},\"options\":{\"activate\":true}}) : PHP.run() failed with exit code 255 and the following output: \n      at Object.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12449:19)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async ms (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12552:3)\n      ... 2 lines matching cause stack trace ...\n      at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {\n    [cause]: PHPExecutionFailureError: PHP.run() failed with exit code 255 and the following output: \n        at PHP.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@php-wasm/universal/index.js:987:19)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async wr (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:33:39)\n        at async Object.gt [as installPlugin] (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:974:42)\n        at async g (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12517:30)\n        at async Object.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12446:23)\n        at async ms (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12552:3)\n        at async Object.onBind (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:227:48)\n        at async V (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:64:10)\n        at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {\n      response: PHPResponse {\n        httpStatusCode: 500,\n        headers: {\n          'x-powered-by': [ 'PHP/8.0.30-dev' ],\n          'content-type': [ 'text/html; charset=UTF-8' ]\n        },\n        bytes: Uint8Array(0) [],\n        exitCode: 255,\n        errors: ''\n      },\n      source: 'request'\n    }\n  }\n}\n\n",
    "log": "/logs/plugins/s/seopilotpl-dla-wordpress/error.json"
  },
  {
    "message": "file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237\n        throw new Error(y, { cause: u });\n              ^\n",
    "level": "FATAL",
    "type": "PLAYGROUND",
    "test": "jspi-boot",
    "plugin": "seopilotpl-dla-wordpress",
    "details": "file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237\n        throw new Error(y, { cause: u });\n              ^\n",
    "log": "/tmp/tmp.4Dv8zWFAnY"
  },
  {
    "message": "SQLSTATE[HY000]: General error: 1 no such table: wp_securio_bf_bans.",
    "level": "FATAL",
    "type": "SQL",
    "test": "jspi-boot",
    "plugin": "seopilotpl-dla-wordpress",
    "details": "[10-May-2025 13:50:07 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>DELETE FROM wp_securio_bf_bans WHERE date_added < 1745675407</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: DELETE FROM wp_securio_bf_bans WHERE date_added &lt; 1745675407 | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_securio_bf_bans.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(182): WP_SQLite_DB->query('DELETE FROM wp_...')\n#2 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(165): Securio_WPLogin->cleanup()\n#3 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(76): Securio_WPLogin->__construct()\n#4 /wordpress/wp-admin/includes/plugin.php(2387): include_once('/wordpress/wp-c...')\n#5 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('securio-wplogin...')\n#6 /internal/eval.php(20): activate_plugin('securio-wplogin...')\n#7 {main}</pre>\n for query DELETE FROM wp_securio_bf_bans WHERE date_added < 1745675407 made by activate_plugin, plugin_sandbox_scrape, include_once('/plugins/securio-wplogin/securio-wplogin.php'), Securio_WPLogin->__construct, Securio_WPLogin->cleanup, WP_SQLite_DB->query, WP_SQLite_DB->print_error",
    "log": "/logs/plugins/s/seopilotpl-dla-wordpress/error.json"
  },
  {
    "message": "SQLSTATE[HY000]: General error: 1 no such table: wp_securio_bf_fails.",
    "level": "FATAL",
    "type": "SQL",
    "test": "jspi-boot",
    "plugin": "seopilotpl-dla-wordpress",
    "details": "[10-May-2025 13:50:07 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>DELETE FROM wp_securio_bf_fails WHERE date_added < 1745675407</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: DELETE FROM wp_securio_bf_fails WHERE date_added &lt; 1745675407 | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_securio_bf_fails.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(186): WP_SQLite_DB->query('DELETE FROM wp_...')\n#2 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(165): Securio_WPLogin->cleanup()\n#3 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(76): Securio_WPLogin->__construct()\n#4 /wordpress/wp-admin/includes/plugin.php(2387): include_once('/wordpress/wp-c...')\n#5 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('securio-wplogin...')\n#6 /internal/eval.php(20): activate_plugin('securio-wplogin...')\n#7 {main}</pre>\n for query DELETE FROM wp_securio_bf_fails WHERE date_added < 1745675407 made by activate_plugin, plugin_sandbox_scrape, include_once('/plugins/securio-wplogin/securio-wplogin.php'), Securio_WPLogin->__construct, Securio_WPLogin->cleanup, WP_SQLite_DB->query, WP_SQLite_DB->print_error",
    "log": "/logs/plugins/s/seopilotpl-dla-wordpress/error.json"
  },
  {
    "message": "SQLSTATE[HY000]: General error: 1 no such table: wp_securio_bf_bans.",
    "level": "FATAL",
    "type": "SQL",
    "test": "jspi-boot",
    "plugin": "seopilotpl-dla-wordpress",
    "details": "[10-May-2025 13:50:16 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>DELETE FROM wp_securio_bf_bans WHERE date_added < 1745675416</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: DELETE FROM wp_securio_bf_bans WHERE date_added &lt; 1745675416 | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_securio_bf_bans.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(182): WP_SQLite_DB->query('DELETE FROM wp_...')\n#2 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(165): Securio_WPLogin->cleanup()\n#3 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(76): Securio_WPLogin->__construct()\n#4 /wordpress/wp-admin/includes/plugin.php(2387): include_once('/wordpress/wp-c...')\n#5 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('securio-wplogin...')\n#6 /internal/eval.php(20): activate_plugin('securio-wplogin...')\n#7 {main}</pre>\n for query DELETE FROM wp_securio_bf_bans WHERE date_added < 1745675416 made by activate_plugin, plugin_sandbox_scrape, include_once('/plugins/securio-wplogin/securio-wplogin.php'), Securio_WPLogin->__construct, Securio_WPLogin->cleanup, WP_SQLite_DB->query, WP_SQLite_DB->print_error",
    "log": "/logs/plugins/s/seopilotpl-dla-wordpress/error.json"
  },
  {
    "message": "SQLSTATE[HY000]: General error: 1 no such table: wp_securio_bf_fails.",
    "level": "FATAL",
    "type": "SQL",
    "test": "jspi-boot",
    "plugin": "seopilotpl-dla-wordpress",
    "details": "[10-May-2025 13:50:16 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>DELETE FROM wp_securio_bf_fails WHERE date_added < 1745675416</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: DELETE FROM wp_securio_bf_fails WHERE date_added &lt; 1745675416 | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_securio_bf_fails.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(186): WP_SQLite_DB->query('DELETE FROM wp_...')\n#2 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(165): Securio_WPLogin->cleanup()\n#3 /wordpress/wp-content/plugins/securio-wplogin/securio-wplogin.php(76): Securio_WPLogin->__construct()\n#4 /wordpress/wp-admin/includes/plugin.php(2387): include_once('/wordpress/wp-c...')\n#5 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('securio-wplogin...')\n#6 /internal/eval.php(20): activate_plugin('securio-wplogin...')\n#7 {main}</pre>\n for query DELETE FROM wp_securio_bf_fails WHERE date_added < 1745675416 made by activate_plugin, plugin_sandbox_scrape, include_once('/plugins/securio-wplogin/securio-wplogin.php'), Securio_WPLogin->__construct, Securio_WPLogin->cleanup, WP_SQLite_DB->query, WP_SQLite_DB->print_error",
    "log": "/logs/plugins/s/seopilotpl-dla-wordpress/error.json"
  },
  {
    "message": "Uncaught Error: Call to undefined function create_function() in /wordpress/wp-content/plugins/seopilotpl-dla-wordpress/spdwp.php:374",
    "level": "FATAL",
    "type": "PHP",
    "test": "jspi-boot",
    "plugin": "seopilotpl-dla-wordpress",
    "details": "[10-May-2025 13:50:24 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function create_function() in /wordpress/wp-content/plugins/seopilotpl-dla-wordpress/spdwp.php:374\nStack trace:\n#0 /wordpress/wp-admin/includes/plugin.php(2387): include_once()\n#1 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('seopilotpl-dla-...')\n#2 /internal/eval.php(20): activate_plugin('seopilotpl-dla-...')\n#3 {main}\n  thrown in /wordpress/wp-content/plugins/seopilotpl-dla-wordpress/spdwp.php on line 374",
    "log": "/logs/plugins/s/seopilotpl-dla-wordpress/error.json"
  },
  {
    "message": "Uncaught Error: Call to undefined function create_function() in /wordpress/wp-content/plugins/seopilotpl-dla-wordpress/spdwp.php:374",
    "level": "FATAL",
    "type": "PHP",
    "test": "jspi-boot",
    "plugin": "seopilotpl-dla-wordpress",
    "details": "[10-May-2025 13:50:32 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function create_function() in /wordpress/wp-content/plugins/seopilotpl-dla-wordpress/spdwp.php:374\nStack trace:\n#0 /wordpress/wp-admin/includes/plugin.php(2387): include_once()\n#1 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('seopilotpl-dla-...')\n#2 /internal/eval.php(20): activate_plugin('seopilotpl-dla-...')\n#3 {main}\n  thrown in /wordpress/wp-content/plugins/seopilotpl-dla-wordpress/spdwp.php on line 374",
    "log": "/logs/plugins/s/seopilotpl-dla-wordpress/error.json"
  },
  {
    "message": "Uncaught Error: Call to undefined function create_function() in /wordpress/wp-content/plugins/seopilotpl-dla-wordpress/spdwp.php:374",
    "level": "FATAL",
    "type": "PHP",
    "test": "jspi-boot",
    "plugin": "seopilotpl-dla-wordpress",
    "details": "[10-May-2025 13:50:40 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function create_function() in /wordpress/wp-content/plugins/seopilotpl-dla-wordpress/spdwp.php:374\nStack trace:\n#0 /wordpress/wp-admin/includes/plugin.php(2387): include_once()\n#1 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('seopilotpl-dla-...')\n#2 /internal/eval.php(20): activate_plugin('seopilotpl-dla-...')\n#3 {main}\n  thrown in /wordpress/wp-content/plugins/seopilotpl-dla-wordpress/spdwp.php on line 374\n\n    at Object.onBind (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async V (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:64:10)\n    at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {\n  [cause]: Error: Error when executing the blueprint step #1 ({\"step\":\"installPlugin\",\"pluginData\":{\"resource\":\"wordpress.org/plugins\",\"slug\":\"seopilotpl-dla-wordpress\"},\"options\":{\"activate\":true}}) : PHP.run() failed with exit code 255 and the following output: \n      at Object.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12449:19)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async ms (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12552:3)\n      ... 2 lines matching cause stack trace ...\n      at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {\n    [cause]: PHPExecutionFailureError: PHP.run() failed with exit code 255 and the following output: \n        at PHP.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@php-wasm/universal/index.js:987:19)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async wr (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:33:39)\n        at async Object.gt [as installPlugin] (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:974:42)\n        at async g (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12517:30)\n        at async Object.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12446:23)\n        at async ms (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12552:3)\n        at async Object.onBind (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:227:48)\n        at async V (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:64:10)\n        at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {\n      response: PHPResponse {\n        httpStatusCode: 500,\n        headers: {\n          'x-powered-by': [ 'PHP/8.0.30-dev' ],\n          'content-type': [ 'text/html; charset=UTF-8' ]\n        },\n        bytes: Uint8Array(0) [],\n        exitCode: 255,\n        errors: ''\n      },\n      source: 'request'\n    }\n  }\n}\n\n",
    "log": "/logs/plugins/s/seopilotpl-dla-wordpress/error.json"
  }
]
