[
{"message":"file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237\n        throw new Error(y, { cause: u });\n              ^\n","level":"FATAL","type":"PLAYGROUND","test":"jspi-boot","plugin":"revpulse","details":"file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237\n        throw new Error(y, { cause: u });\n              ^\n","log":"/tmp/tmp.c3bmUVc1PS"}
,
{"message":"Unknown create type: UNIQUE INDEX.","level":"FATAL","type":"SQL","test":"jspi-boot","plugin":"revpulse","details":"[16-May-2025 17:24:33 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>CREATE UNIQUE INDEX shortcode_index ON wp_ppgbo_cache ( shortcode );</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown create type: UNIQUE INDEX.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/presta-products/presta-products.php(1290): WP_SQLite_DB->query('CREATE UNIQUE I...')\n#2 /wordpress/wp-content/plugins/presta-products/presta-products.php(83): PrestaProducts->ppgbo_install_mysql()\n#3 /wordpress/wp-content/plugins/presta-products/presta-products.php(1369): PrestaProducts->__construct()\n#4 /wordpress/wp-admin/includes/plugin.php(2387): include_once('/wordpress/wp-c...')\n#5 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('presta-products...')\n#6 /internal/eval.php(20): activate_plugin('presta-products...')\n#7 {main}</pre>\n for query CREATE UNIQUE INDEX shortcode_index ON wp_ppgbo_cache ( shortcode ); made by activate_plugin, plugin_sandbox_scrape, include_once('/plugins/presta-products/presta-products.php'), PrestaProducts->__construct, PrestaProducts->ppgbo_install_mysql, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/r/revpulse/error.json"}
,
{"message":"Unknown create type: UNIQUE INDEX.","level":"FATAL","type":"SQL","test":"jspi-boot","plugin":"revpulse","details":"[16-May-2025 17:24:33 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>CREATE UNIQUE INDEX id_cat_index ON wp_ppgbo_categories ( id_cat_wordpress );</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown create type: UNIQUE INDEX.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/presta-products/presta-products.php(1306): WP_SQLite_DB->query('CREATE UNIQUE I...')\n#2 /wordpress/wp-content/plugins/presta-products/presta-products.php(83): PrestaProducts->ppgbo_install_mysql()\n#3 /wordpress/wp-content/plugins/presta-products/presta-products.php(1369): PrestaProducts->__construct()\n#4 /wordpress/wp-admin/includes/plugin.php(2387): include_once('/wordpress/wp-c...')\n#5 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('presta-products...')\n#6 /internal/eval.php(20): activate_plugin('presta-products...')\n#7 {main}</pre>\n for query CREATE UNIQUE INDEX id_cat_index ON wp_ppgbo_categories ( id_cat_wordpress ); made by activate_plugin, plugin_sandbox_scrape, include_once('/plugins/presta-products/presta-products.php'), PrestaProducts->__construct, PrestaProducts->ppgbo_install_mysql, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/r/revpulse/error.json"}
,
{"message":"Unknown create type: UNIQUE INDEX.","level":"FATAL","type":"SQL","test":"jspi-boot","plugin":"revpulse","details":"[16-May-2025 17:24:36 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>CREATE UNIQUE INDEX shortcode_index ON wp_ppgbo_cache ( shortcode );</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown create type: UNIQUE INDEX.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/presta-products/presta-products.php(1290): WP_SQLite_DB->query('CREATE UNIQUE I...')\n#2 /wordpress/wp-content/plugins/presta-products/presta-products.php(83): PrestaProducts->ppgbo_install_mysql()\n#3 /wordpress/wp-content/plugins/presta-products/presta-products.php(1369): PrestaProducts->__construct()\n#4 /wordpress/wp-settings.php(545): include_once('/wordpress/wp-c...')\n#5 /wordpress/wp-config.php(102): require_once('/wordpress/wp-s...')\n#6 /wordpress/wp-load.php(50): require_once('/wordpress/wp-c...')\n#7 /internal/eval.php(3): require_once('/wordpress/wp-l...')\n#8 {main}</pre>\n for query CREATE UNIQUE INDEX shortcode_index ON wp_ppgbo_cache ( shortcode ); made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), include_once('/plugins/presta-products/presta-products.php'), PrestaProducts->__construct, PrestaProducts->ppgbo_install_mysql, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/r/revpulse/error.json"}
,
{"message":"Unknown create type: UNIQUE INDEX.","level":"FATAL","type":"SQL","test":"jspi-boot","plugin":"revpulse","details":"[16-May-2025 17:24:36 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>CREATE UNIQUE INDEX id_cat_index ON wp_ppgbo_categories ( id_cat_wordpress );</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown create type: UNIQUE INDEX.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/presta-products/presta-products.php(1306): WP_SQLite_DB->query('CREATE UNIQUE I...')\n#2 /wordpress/wp-content/plugins/presta-products/presta-products.php(83): PrestaProducts->ppgbo_install_mysql()\n#3 /wordpress/wp-content/plugins/presta-products/presta-products.php(1369): PrestaProducts->__construct()\n#4 /wordpress/wp-settings.php(545): include_once('/wordpress/wp-c...')\n#5 /wordpress/wp-config.php(102): require_once('/wordpress/wp-s...')\n#6 /wordpress/wp-load.php(50): require_once('/wordpress/wp-c...')\n#7 /internal/eval.php(3): require_once('/wordpress/wp-l...')\n#8 {main}</pre>\n for query CREATE UNIQUE INDEX id_cat_index ON wp_ppgbo_categories ( id_cat_wordpress ); made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), include_once('/plugins/presta-products/presta-products.php'), PrestaProducts->__construct, PrestaProducts->ppgbo_install_mysql, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/r/revpulse/error.json"}
,
{"message":"Unknown create type: UNIQUE INDEX.","level":"FATAL","type":"SQL","test":"jspi-boot","plugin":"revpulse","details":"[16-May-2025 17:24:45 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>CREATE UNIQUE INDEX shortcode_index ON wp_ppgbo_cache ( shortcode );</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown create type: UNIQUE INDEX.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/presta-products/presta-products.php(1290): WP_SQLite_DB->query('CREATE UNIQUE I...')\n#2 /wordpress/wp-content/plugins/presta-products/presta-products.php(83): PrestaProducts->ppgbo_install_mysql()\n#3 /wordpress/wp-content/plugins/presta-products/presta-products.php(1369): PrestaProducts->__construct()\n#4 /wordpress/wp-admin/includes/plugin.php(2387): include_once('/wordpress/wp-c...')\n#5 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('presta-products...')\n#6 /internal/eval.php(20): activate_plugin('presta-products...')\n#7 {main}</pre>\n for query CREATE UNIQUE INDEX shortcode_index ON wp_ppgbo_cache ( shortcode ); made by activate_plugin, plugin_sandbox_scrape, include_once('/plugins/presta-products/presta-products.php'), PrestaProducts->__construct, PrestaProducts->ppgbo_install_mysql, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/r/revpulse/error.json"}
,
{"message":"Unknown create type: UNIQUE INDEX.","level":"FATAL","type":"SQL","test":"jspi-boot","plugin":"revpulse","details":"[16-May-2025 17:24:45 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>CREATE UNIQUE INDEX id_cat_index ON wp_ppgbo_categories ( id_cat_wordpress );</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown create type: UNIQUE INDEX.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/presta-products/presta-products.php(1306): WP_SQLite_DB->query('CREATE UNIQUE I...')\n#2 /wordpress/wp-content/plugins/presta-products/presta-products.php(83): PrestaProducts->ppgbo_install_mysql()\n#3 /wordpress/wp-content/plugins/presta-products/presta-products.php(1369): PrestaProducts->__construct()\n#4 /wordpress/wp-admin/includes/plugin.php(2387): include_once('/wordpress/wp-c...')\n#5 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('presta-products...')\n#6 /internal/eval.php(20): activate_plugin('presta-products...')\n#7 {main}</pre>\n for query CREATE UNIQUE INDEX id_cat_index ON wp_ppgbo_categories ( id_cat_wordpress ); made by activate_plugin, plugin_sandbox_scrape, include_once('/plugins/presta-products/presta-products.php'), PrestaProducts->__construct, PrestaProducts->ppgbo_install_mysql, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/r/revpulse/error.json"}
,
{"message":"Unknown create type: UNIQUE INDEX.","level":"FATAL","type":"SQL","test":"jspi-boot","plugin":"revpulse","details":"[16-May-2025 17:24:47 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>CREATE UNIQUE INDEX shortcode_index ON wp_ppgbo_cache ( shortcode );</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown create type: UNIQUE INDEX.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/presta-products/presta-products.php(1290): WP_SQLite_DB->query('CREATE UNIQUE I...')\n#2 /wordpress/wp-content/plugins/presta-products/presta-products.php(83): PrestaProducts->ppgbo_install_mysql()\n#3 /wordpress/wp-content/plugins/presta-products/presta-products.php(1369): PrestaProducts->__construct()\n#4 /wordpress/wp-settings.php(545): include_once('/wordpress/wp-c...')\n#5 /wordpress/wp-config.php(102): require_once('/wordpress/wp-s...')\n#6 /wordpress/wp-load.php(50): require_once('/wordpress/wp-c...')\n#7 /internal/eval.php(3): require_once('/wordpress/wp-l...')\n#8 {main}</pre>\n for query CREATE UNIQUE INDEX shortcode_index ON wp_ppgbo_cache ( shortcode ); made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), include_once('/plugins/presta-products/presta-products.php'), PrestaProducts->__construct, PrestaProducts->ppgbo_install_mysql, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/r/revpulse/error.json"}
,
{"message":"Unknown create type: UNIQUE INDEX.","level":"FATAL","type":"SQL","test":"jspi-boot","plugin":"revpulse","details":"[16-May-2025 17:24:47 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>CREATE UNIQUE INDEX id_cat_index ON wp_ppgbo_categories ( id_cat_wordpress );</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown create type: UNIQUE INDEX.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/presta-products/presta-products.php(1306): WP_SQLite_DB->query('CREATE UNIQUE I...')\n#2 /wordpress/wp-content/plugins/presta-products/presta-products.php(83): PrestaProducts->ppgbo_install_mysql()\n#3 /wordpress/wp-content/plugins/presta-products/presta-products.php(1369): PrestaProducts->__construct()\n#4 /wordpress/wp-settings.php(545): include_once('/wordpress/wp-c...')\n#5 /wordpress/wp-config.php(102): require_once('/wordpress/wp-s...')\n#6 /wordpress/wp-load.php(50): require_once('/wordpress/wp-c...')\n#7 /internal/eval.php(3): require_once('/wordpress/wp-l...')\n#8 {main}</pre>\n for query CREATE UNIQUE INDEX id_cat_index ON wp_ppgbo_categories ( id_cat_wordpress ); made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), include_once('/plugins/presta-products/presta-products.php'), PrestaProducts->__construct, PrestaProducts->ppgbo_install_mysql, WP_SQLite_DB->query, WP_SQLite_DB->print_error","log":"/logs/plugins/r/revpulse/error.json"}
,
{"message":"Uncaught TypeError: sizeof(): Argument #1 ($value) must be of type Countable|array, bool given in /wordpress/wp-content/plugins/retainly/dashboard/includes/options_config.php:47","level":"FATAL","type":"PHP","test":"jspi-boot","plugin":"revpulse","details":"[16-May-2025 17:28:59 UTC] PHP Fatal error:  Uncaught TypeError: sizeof(): Argument #1 ($value) must be of type Countable|array, bool given in /wordpress/wp-content/plugins/retainly/dashboard/includes/options_config.php:47\nStack trace:\n#0 /wordpress/wp-content/plugins/retainly/dashboard/includes/options.php(47): require()\n#1 /wordpress/wp-content/plugins/retainly/dashboard/dashboard.php(86): require('/wordpress/wp-c...')\n#2 /wordpress/wp-content/plugins/retainly/dashboard/dashboard.php(43): RAD_Dashboard->include_options()\n#3 /wordpress/wp-content/plugins/retainly/retainly.php(86): RAD_Dashboard->__construct(Array)\n#4 /wordpress/wp-content/plugins/retainly/retainly.php(4858): RAD_Rapidology->__construct()\n#5 /wordpress/wp-admin/includes/plugin.php(2387): include_once('/wordpress/wp-c...')\n#6 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('retainly/retain...')\n#7 /internal/eval.php(20): activate_plugin('retainly/retain...')\n#8 {main}\n  thrown in /wordpress/wp-content/plugins/retainly/dashboard/includes/options_config.php on line 47","log":"/logs/plugins/r/revpulse/error.json"}
,
{"message":"Uncaught TypeError: sizeof(): Argument #1 ($value) must be of type Countable|array, bool given in /wordpress/wp-content/plugins/retainly/dashboard/includes/options_config.php:47","level":"FATAL","type":"PHP","test":"jspi-boot","plugin":"revpulse","details":"[16-May-2025 17:29:07 UTC] PHP Fatal error:  Uncaught TypeError: sizeof(): Argument #1 ($value) must be of type Countable|array, bool given in /wordpress/wp-content/plugins/retainly/dashboard/includes/options_config.php:47\nStack trace:\n#0 /wordpress/wp-content/plugins/retainly/dashboard/includes/options.php(47): require()\n#1 /wordpress/wp-content/plugins/retainly/dashboard/dashboard.php(86): require('/wordpress/wp-c...')\n#2 /wordpress/wp-content/plugins/retainly/dashboard/dashboard.php(43): RAD_Dashboard->include_options()\n#3 /wordpress/wp-content/plugins/retainly/retainly.php(86): RAD_Dashboard->__construct(Array)\n#4 /wordpress/wp-content/plugins/retainly/retainly.php(4858): RAD_Rapidology->__construct()\n#5 /wordpress/wp-admin/includes/plugin.php(2387): include_once('/wordpress/wp-c...')\n#6 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('retainly/retain...')\n#7 /internal/eval.php(20): activate_plugin('retainly/retain...')\n#8 {main}\n  thrown in /wordpress/wp-content/plugins/retainly/dashboard/includes/options_config.php on line 47","log":"/logs/plugins/r/revpulse/error.json"}
,
{"message":"Uncaught TypeError: sizeof(): Argument #1 ($value) must be of type Countable|array, bool given in /wordpress/wp-content/plugins/retainly/dashboard/includes/options_config.php:47","level":"FATAL","type":"PHP","test":"jspi-boot","plugin":"revpulse","details":"[16-May-2025 17:29:15 UTC] PHP Fatal error:  Uncaught TypeError: sizeof(): Argument #1 ($value) must be of type Countable|array, bool given in /wordpress/wp-content/plugins/retainly/dashboard/includes/options_config.php:47\nStack trace:\n#0 /wordpress/wp-content/plugins/retainly/dashboard/includes/options.php(47): require()\n#1 /wordpress/wp-content/plugins/retainly/dashboard/dashboard.php(86): require('/wordpress/wp-c...')\n#2 /wordpress/wp-content/plugins/retainly/dashboard/dashboard.php(43): RAD_Dashboard->include_options()\n#3 /wordpress/wp-content/plugins/retainly/retainly.php(86): RAD_Dashboard->__construct(Array)\n#4 /wordpress/wp-content/plugins/retainly/retainly.php(4858): RAD_Rapidology->__construct()\n#5 /wordpress/wp-admin/includes/plugin.php(2387): include_once('/wordpress/wp-c...')\n#6 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('retainly/retain...')\n#7 /internal/eval.php(20): activate_plugin('retainly/retain...')\n#8 {main}\n  thrown in /wordpress/wp-content/plugins/retainly/dashboard/includes/options_config.php on line 47\n\n    at Object.onBind (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async V (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:64:10)\n    at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {\n  [cause]: Error: Error when executing the blueprint step #1 ({\"step\":\"installPlugin\",\"pluginData\":{\"resource\":\"wordpress.org/plugins\",\"slug\":\"revpulse\"},\"options\":{\"activate\":true}}) : Could not download \"https://downloads.wordpress.org/plugin/revpulse.latest-stable.zip\".\n  \t\t\t\tCheck if the URL is correct and the server is reachable.\n  \t\t\t\tIf it is reachable, the server might be blocking the request.\n  \t\t\t\tCheck the browser console and network tabs for more information.\n  \n  \t\t\t\t## Does the console show the error \"No 'Access-Control-Allow-Origin' header\"?\n  \n  \t\t\t\tThis means the server that hosts your file does not allow requests from other sites\n  \t\t\t\t(cross-origin requests, or CORS).\tYou need to move the asset to a server that allows\n  \t\t\t\tcross-origin file downloads. Learn more about CORS at\n  \t\t\t\thttps://developer.mozilla.org/en-US/docs/Web/HTTP/CORS.\n  \n  \t\t\t\tIf your file is on GitHub, load it from \"raw.githubusercontent.com\".\n  \t\t\t\tHere's how to do that:\n  \n  \t\t\t\t1. Start with the original GitHub URL of the file. For example:\n  \t\t\t\thttps://github.com/username/repository/blob/branch/filename.\n  \t\t\t\t2. Replace \"github.com\" with \"raw.githubusercontent.com\".\n  \t\t\t\t3. Remove the \"/blob/\" part of the URL.\n  \n  \t\t\t\tThe resulting URL should look like this:\n  \t\t\t\thttps://raw.githubusercontent.com/username/repository/branch/filename\n  \n  \t\t\t\tError:\n  \t\t\t\tError: Could not download \"https://downloads.wordpress.org/plugin/revpulse.latest-stable.zip\"\n      at Object.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12449:19)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async ms (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12552:3)\n      at async Object.onBind (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:227:48)\n      at async V (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:64:10)\n      at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {\n    [cause]: Error: Could not download \"https://downloads.wordpress.org/plugin/revpulse.latest-stable.zip\".\n    \t\t\t\tCheck if the URL is correct and the server is reachable.\n    \t\t\t\tIf it is reachable, the server might be blocking the request.\n    \t\t\t\tCheck the browser console and network tabs for more information.\n    \n    \t\t\t\t## Does the console show the error \"No 'Access-Control-Allow-Origin' header\"?\n    \n    \t\t\t\tThis means the server that hosts your file does not allow requests from other sites\n    \t\t\t\t(cross-origin requests, or CORS).\tYou need to move the asset to a server that allows\n    \t\t\t\tcross-origin file downloads. Learn more about CORS at\n    \t\t\t\thttps://developer.mozilla.org/en-US/docs/Web/HTTP/CORS.\n    \n    \t\t\t\tIf your file is on GitHub, load it from \"raw.githubusercontent.com\".\n    \t\t\t\tHere's how to do that:\n    \n    \t\t\t\t1. Start with the original GitHub URL of the file. For example:\n    \t\t\t\thttps://github.com/username/repository/blob/branch/filename.\n    \t\t\t\t2. Replace \"github.com\" with \"raw.githubusercontent.com\".\n    \t\t\t\t3. Remove the \"/blob/\" part of the URL.\n    \n    \t\t\t\tThe resulting URL should look like this:\n    \t\t\t\thttps://raw.githubusercontent.com/username/repository/branch/filename\n    \n    \t\t\t\tError:\n    \t\t\t\tError: Could not download \"https://downloads.wordpress.org/plugin/revpulse.latest-stable.zip\"\n        at Ct.resolve (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:1472:13)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async _.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@php-wasm/util/index.js:45:14)\n  }\n}\n\n","log":"/logs/plugins/r/revpulse/error.json"}
]
