[
  {
    "message": "file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237\n        throw new Error(y, { cause: u });\n              ^\n",
    "level": "FATAL",
    "type": "PLAYGROUND",
    "test": "ast-sqlite-boot",
    "plugin": "pica-protector",
    "details": "file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237\n        throw new Error(y, { cause: u });\n              ^\n",
    "log": "/tmp/tmp.eADUWzjoiM"
  },
  {
    "message": "SQLSTATE[HY000]: General error: 1 no such table: wp_woocommerce_attribute_taxonomies.",
    "level": "FATAL",
    "type": "SQL",
    "test": "ast-sqlite-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 16:57:59 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_invisible INT(1) NULL</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: wp_woocommerce_attribute_taxonomies, ATTRIBUTE_INVISIBLE, int(1)</li>\n<li>Executing: ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_invisible integer NULL | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_woocommerce_attribute_taxonomies.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/product-attribute-global-order-and-visibility/woo-attribute-global-order-visibility.php(37): WP_SQLite_DB->query('ALTER TABLE wp_...')\n#2 /wordpress/wp-includes/class-wp-hook.php(324): pagov_product_attribute_order_visibility(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_produc...', false)\n#6 /internal/eval.php(20): activate_plugin('product-attribu...')\n#7 {main}</pre>\n for query ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_invisible INT(1) NULL made by activate_plugin, do_action('activate_product-attribute-global-order-and-visibility/woo-attribute-global-order-visibility.php'), WP_Hook->do_action, WP_Hook->apply_filters, pagov_product_attribute_order_visibility, WP_SQLite_DB->query, WP_SQLite_DB->print_error",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "SQLSTATE[HY000]: General error: 1 no such table: wp_woocommerce_attribute_taxonomies.",
    "level": "FATAL",
    "type": "SQL",
    "test": "ast-sqlite-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 16:57:59 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_custom_order INT(10) NULL</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: wp_woocommerce_attribute_taxonomies, ATTRIBUTE_CUSTOM_ORDER, int(10)</li>\n<li>Executing: ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_custom_order integer NULL | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_woocommerce_attribute_taxonomies.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/product-attribute-global-order-and-visibility/woo-attribute-global-order-visibility.php(38): WP_SQLite_DB->query('ALTER TABLE wp_...')\n#2 /wordpress/wp-includes/class-wp-hook.php(324): pagov_product_attribute_order_visibility(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_produc...', false)\n#6 /internal/eval.php(20): activate_plugin('product-attribu...')\n#7 {main}</pre>\n for query ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_custom_order INT(10) NULL made by activate_plugin, do_action('activate_product-attribute-global-order-and-visibility/woo-attribute-global-order-visibility.php'), WP_Hook->do_action, WP_Hook->apply_filters, pagov_product_attribute_order_visibility, WP_SQLite_DB->query, WP_SQLite_DB->print_error",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "SQLSTATE[HY000]: General error: 1 no such table: wp_woocommerce_attribute_taxonomies.",
    "level": "FATAL",
    "type": "SQL",
    "test": "ast-sqlite-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 16:58:07 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_invisible INT(1) NULL</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: wp_woocommerce_attribute_taxonomies, ATTRIBUTE_INVISIBLE, int(1)</li>\n<li>Executing: ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_invisible integer NULL | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_woocommerce_attribute_taxonomies.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/product-attribute-global-order-and-visibility/woo-attribute-global-order-visibility.php(37): WP_SQLite_DB->query('ALTER TABLE wp_...')\n#2 /wordpress/wp-includes/class-wp-hook.php(324): pagov_product_attribute_order_visibility(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_produc...', false)\n#6 /internal/eval.php(20): activate_plugin('product-attribu...')\n#7 {main}</pre>\n for query ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_invisible INT(1) NULL made by activate_plugin, do_action('activate_product-attribute-global-order-and-visibility/woo-attribute-global-order-visibility.php'), WP_Hook->do_action, WP_Hook->apply_filters, pagov_product_attribute_order_visibility, WP_SQLite_DB->query, WP_SQLite_DB->print_error",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "SQLSTATE[HY000]: General error: 1 no such table: wp_woocommerce_attribute_taxonomies.",
    "level": "FATAL",
    "type": "SQL",
    "test": "ast-sqlite-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 16:58:07 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_custom_order INT(10) NULL</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: wp_woocommerce_attribute_taxonomies, ATTRIBUTE_CUSTOM_ORDER, int(10)</li>\n<li>Executing: ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_custom_order integer NULL | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_woocommerce_attribute_taxonomies.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/product-attribute-global-order-and-visibility/woo-attribute-global-order-visibility.php(38): WP_SQLite_DB->query('ALTER TABLE wp_...')\n#2 /wordpress/wp-includes/class-wp-hook.php(324): pagov_product_attribute_order_visibility(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_produc...', false)\n#6 /internal/eval.php(20): activate_plugin('product-attribu...')\n#7 {main}</pre>\n for query ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_custom_order INT(10) NULL made by activate_plugin, do_action('activate_product-attribute-global-order-and-visibility/woo-attribute-global-order-visibility.php'), WP_Hook->do_action, WP_Hook->apply_filters, pagov_product_attribute_order_visibility, WP_SQLite_DB->query, WP_SQLite_DB->print_error",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "level": "DEPRECATED",
    "type": "PHP",
    "test": "ast-sqlite-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 16:59:30 UTC] PHP Deprecated:  Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "level": "DEPRECATED",
    "type": "PHP",
    "test": "ast-sqlite-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 16:59:31 UTC] PHP Deprecated:  Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "level": "DEPRECATED",
    "type": "PHP",
    "test": "ast-sqlite-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 16:59:38 UTC] PHP Deprecated:  Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "level": "DEPRECATED",
    "type": "PHP",
    "test": "ast-sqlite-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 16:59:39 UTC] PHP Deprecated:  Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "level": "DEPRECATED",
    "type": "PHP",
    "test": "ast-sqlite-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 16:59:47 UTC] PHP Deprecated:  Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "level": "DEPRECATED",
    "type": "PHP",
    "test": "ast-sqlite-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 16:59:48 UTC] PHP Deprecated:  Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "Uncaught Error: Call to undefined function get_editable_roles() in /wordpress/wp-content/plugins/persian-gravity-sms-pro/includes/main.php:111",
    "level": "FATAL",
    "type": "PHP",
    "test": "ast-sqlite-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 17:01:50 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function get_editable_roles() in /wordpress/wp-content/plugins/persian-gravity-sms-pro/includes/main.php:111\nStack trace:\n#0 /wordpress/wp-includes/class-wp-hook.php(324): GFHANNANSMS_Pro::active(false)\n#1 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#2 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#3 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_persia...', false)\n#4 /internal/eval.php(20): activate_plugin('persian-gravity...')\n#5 {main}\n  thrown in /wordpress/wp-content/plugins/persian-gravity-sms-pro/includes/main.php on line 111",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "Uncaught Error: Call to undefined function get_editable_roles() in /wordpress/wp-content/plugins/persian-gravity-sms-pro/includes/main.php:111",
    "level": "FATAL",
    "type": "PHP",
    "test": "ast-sqlite-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 17:01:58 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function get_editable_roles() in /wordpress/wp-content/plugins/persian-gravity-sms-pro/includes/main.php:111\nStack trace:\n#0 /wordpress/wp-includes/class-wp-hook.php(324): GFHANNANSMS_Pro::active(false)\n#1 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#2 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#3 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_persia...', false)\n#4 /internal/eval.php(20): activate_plugin('persian-gravity...')\n#5 {main}\n  thrown in /wordpress/wp-content/plugins/persian-gravity-sms-pro/includes/main.php on line 111",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "Uncaught Error: Call to undefined function get_editable_roles() in /wordpress/wp-content/plugins/persian-gravity-sms-pro/includes/main.php:111",
    "level": "FATAL",
    "type": "PHP",
    "test": "ast-sqlite-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 17:02:05 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function get_editable_roles() in /wordpress/wp-content/plugins/persian-gravity-sms-pro/includes/main.php:111\nStack trace:\n#0 /wordpress/wp-includes/class-wp-hook.php(324): GFHANNANSMS_Pro::active(false)\n#1 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#2 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#3 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_persia...', false)\n#4 /internal/eval.php(20): activate_plugin('persian-gravity...')\n#5 {main}\n  thrown in /wordpress/wp-content/plugins/persian-gravity-sms-pro/includes/main.php on line 111\n\n    at Object.onBind (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async V (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:64:10)\n    at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {\n  [cause]: Error: Error when executing the blueprint step #5 ({\"step\":\"installPlugin\",\"pluginData\":{\"resource\":\"wordpress.org/plugins\",\"slug\":\"pica-protector\"},\"options\":{\"activate\":true}}) : Could not download \"https://downloads.wordpress.org/plugin/pica-protector.latest-stable.zip\".\n  \t\t\t\tCheck if the URL is correct and the server is reachable.\n  \t\t\t\tIf it is reachable, the server might be blocking the request.\n  \t\t\t\tCheck the browser console and network tabs for more information.\n  \n  \t\t\t\t## Does the console show the error \"No 'Access-Control-Allow-Origin' header\"?\n  \n  \t\t\t\tThis means the server that hosts your file does not allow requests from other sites\n  \t\t\t\t(cross-origin requests, or CORS).\tYou need to move the asset to a server that allows\n  \t\t\t\tcross-origin file downloads. Learn more about CORS at\n  \t\t\t\thttps://developer.mozilla.org/en-US/docs/Web/HTTP/CORS.\n  \n  \t\t\t\tIf your file is on GitHub, load it from \"raw.githubusercontent.com\".\n  \t\t\t\tHere's how to do that:\n  \n  \t\t\t\t1. Start with the original GitHub URL of the file. For example:\n  \t\t\t\thttps://github.com/username/repository/blob/branch/filename.\n  \t\t\t\t2. Replace \"github.com\" with \"raw.githubusercontent.com\".\n  \t\t\t\t3. Remove the \"/blob/\" part of the URL.\n  \n  \t\t\t\tThe resulting URL should look like this:\n  \t\t\t\thttps://raw.githubusercontent.com/username/repository/branch/filename\n  \n  \t\t\t\tError:\n  \t\t\t\tError: Could not download \"https://downloads.wordpress.org/plugin/pica-protector.latest-stable.zip\"\n      at Object.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12449:19)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async ms (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12552:3)\n      at async Object.onBind (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:227:48)\n      at async V (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:64:10)\n      at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {\n    [cause]: Error: Could not download \"https://downloads.wordpress.org/plugin/pica-protector.latest-stable.zip\".\n    \t\t\t\tCheck if the URL is correct and the server is reachable.\n    \t\t\t\tIf it is reachable, the server might be blocking the request.\n    \t\t\t\tCheck the browser console and network tabs for more information.\n    \n    \t\t\t\t## Does the console show the error \"No 'Access-Control-Allow-Origin' header\"?\n    \n    \t\t\t\tThis means the server that hosts your file does not allow requests from other sites\n    \t\t\t\t(cross-origin requests, or CORS).\tYou need to move the asset to a server that allows\n    \t\t\t\tcross-origin file downloads. Learn more about CORS at\n    \t\t\t\thttps://developer.mozilla.org/en-US/docs/Web/HTTP/CORS.\n    \n    \t\t\t\tIf your file is on GitHub, load it from \"raw.githubusercontent.com\".\n    \t\t\t\tHere's how to do that:\n    \n    \t\t\t\t1. Start with the original GitHub URL of the file. For example:\n    \t\t\t\thttps://github.com/username/repository/blob/branch/filename.\n    \t\t\t\t2. Replace \"github.com\" with \"raw.githubusercontent.com\".\n    \t\t\t\t3. Remove the \"/blob/\" part of the URL.\n    \n    \t\t\t\tThe resulting URL should look like this:\n    \t\t\t\thttps://raw.githubusercontent.com/username/repository/branch/filename\n    \n    \t\t\t\tError:\n    \t\t\t\tError: Could not download \"https://downloads.wordpress.org/plugin/pica-protector.latest-stable.zip\"\n        at Ct.resolve (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:1472:13)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async _.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@php-wasm/util/index.js:45:14)\n  }\n}\n\n",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237\n        throw new Error(y, { cause: u });\n              ^\n",
    "level": "FATAL",
    "type": "PLAYGROUND",
    "test": "asyncify-boot",
    "plugin": "pica-protector",
    "details": "file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237\n        throw new Error(y, { cause: u });\n              ^\n",
    "log": "/tmp/tmp.vJaSvmd7v7"
  },
  {
    "message": "SQLSTATE[HY000]: General error: 1 no such table: wp_woocommerce_attribute_taxonomies.",
    "level": "FATAL",
    "type": "SQL",
    "test": "asyncify-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 16:57:59 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_invisible INT(1) NULL</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: wp_woocommerce_attribute_taxonomies, ATTRIBUTE_INVISIBLE, int(1)</li>\n<li>Executing: ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_invisible integer NULL | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_woocommerce_attribute_taxonomies.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/product-attribute-global-order-and-visibility/woo-attribute-global-order-visibility.php(37): WP_SQLite_DB->query('ALTER TABLE wp_...')\n#2 /wordpress/wp-includes/class-wp-hook.php(324): pagov_product_attribute_order_visibility(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_produc...', false)\n#6 /internal/eval.php(20): activate_plugin('product-attribu...')\n#7 {main}</pre>\n for query ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_invisible INT(1) NULL made by activate_plugin, do_action('activate_product-attribute-global-order-and-visibility/woo-attribute-global-order-visibility.php'), WP_Hook->do_action, WP_Hook->apply_filters, pagov_product_attribute_order_visibility, WP_SQLite_DB->query, WP_SQLite_DB->print_error",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "SQLSTATE[HY000]: General error: 1 no such table: wp_woocommerce_attribute_taxonomies.",
    "level": "FATAL",
    "type": "SQL",
    "test": "asyncify-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 16:57:59 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_custom_order INT(10) NULL</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: wp_woocommerce_attribute_taxonomies, ATTRIBUTE_CUSTOM_ORDER, int(10)</li>\n<li>Executing: ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_custom_order integer NULL | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_woocommerce_attribute_taxonomies.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/product-attribute-global-order-and-visibility/woo-attribute-global-order-visibility.php(38): WP_SQLite_DB->query('ALTER TABLE wp_...')\n#2 /wordpress/wp-includes/class-wp-hook.php(324): pagov_product_attribute_order_visibility(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_produc...', false)\n#6 /internal/eval.php(20): activate_plugin('product-attribu...')\n#7 {main}</pre>\n for query ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_custom_order INT(10) NULL made by activate_plugin, do_action('activate_product-attribute-global-order-and-visibility/woo-attribute-global-order-visibility.php'), WP_Hook->do_action, WP_Hook->apply_filters, pagov_product_attribute_order_visibility, WP_SQLite_DB->query, WP_SQLite_DB->print_error",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "SQLSTATE[HY000]: General error: 1 no such table: wp_woocommerce_attribute_taxonomies.",
    "level": "FATAL",
    "type": "SQL",
    "test": "asyncify-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 16:58:07 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_invisible INT(1) NULL</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: wp_woocommerce_attribute_taxonomies, ATTRIBUTE_INVISIBLE, int(1)</li>\n<li>Executing: ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_invisible integer NULL | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_woocommerce_attribute_taxonomies.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/product-attribute-global-order-and-visibility/woo-attribute-global-order-visibility.php(37): WP_SQLite_DB->query('ALTER TABLE wp_...')\n#2 /wordpress/wp-includes/class-wp-hook.php(324): pagov_product_attribute_order_visibility(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_produc...', false)\n#6 /internal/eval.php(20): activate_plugin('product-attribu...')\n#7 {main}</pre>\n for query ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_invisible INT(1) NULL made by activate_plugin, do_action('activate_product-attribute-global-order-and-visibility/woo-attribute-global-order-visibility.php'), WP_Hook->do_action, WP_Hook->apply_filters, pagov_product_attribute_order_visibility, WP_SQLite_DB->query, WP_SQLite_DB->print_error",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "SQLSTATE[HY000]: General error: 1 no such table: wp_woocommerce_attribute_taxonomies.",
    "level": "FATAL",
    "type": "SQL",
    "test": "asyncify-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 16:58:07 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_custom_order INT(10) NULL</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: wp_woocommerce_attribute_taxonomies, ATTRIBUTE_CUSTOM_ORDER, int(10)</li>\n<li>Executing: ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_custom_order integer NULL | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_woocommerce_attribute_taxonomies.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/product-attribute-global-order-and-visibility/woo-attribute-global-order-visibility.php(38): WP_SQLite_DB->query('ALTER TABLE wp_...')\n#2 /wordpress/wp-includes/class-wp-hook.php(324): pagov_product_attribute_order_visibility(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_produc...', false)\n#6 /internal/eval.php(20): activate_plugin('product-attribu...')\n#7 {main}</pre>\n for query ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_custom_order INT(10) NULL made by activate_plugin, do_action('activate_product-attribute-global-order-and-visibility/woo-attribute-global-order-visibility.php'), WP_Hook->do_action, WP_Hook->apply_filters, pagov_product_attribute_order_visibility, WP_SQLite_DB->query, WP_SQLite_DB->print_error",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "level": "DEPRECATED",
    "type": "PHP",
    "test": "asyncify-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 16:59:30 UTC] PHP Deprecated:  Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "level": "DEPRECATED",
    "type": "PHP",
    "test": "asyncify-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 16:59:31 UTC] PHP Deprecated:  Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "level": "DEPRECATED",
    "type": "PHP",
    "test": "asyncify-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 16:59:38 UTC] PHP Deprecated:  Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "level": "DEPRECATED",
    "type": "PHP",
    "test": "asyncify-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 16:59:39 UTC] PHP Deprecated:  Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "level": "DEPRECATED",
    "type": "PHP",
    "test": "asyncify-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 16:59:47 UTC] PHP Deprecated:  Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "level": "DEPRECATED",
    "type": "PHP",
    "test": "asyncify-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 16:59:48 UTC] PHP Deprecated:  Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "Uncaught Error: Call to undefined function get_editable_roles() in /wordpress/wp-content/plugins/persian-gravity-sms-pro/includes/main.php:111",
    "level": "FATAL",
    "type": "PHP",
    "test": "asyncify-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 17:01:50 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function get_editable_roles() in /wordpress/wp-content/plugins/persian-gravity-sms-pro/includes/main.php:111\nStack trace:\n#0 /wordpress/wp-includes/class-wp-hook.php(324): GFHANNANSMS_Pro::active(false)\n#1 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#2 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#3 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_persia...', false)\n#4 /internal/eval.php(20): activate_plugin('persian-gravity...')\n#5 {main}\n  thrown in /wordpress/wp-content/plugins/persian-gravity-sms-pro/includes/main.php on line 111",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "Uncaught Error: Call to undefined function get_editable_roles() in /wordpress/wp-content/plugins/persian-gravity-sms-pro/includes/main.php:111",
    "level": "FATAL",
    "type": "PHP",
    "test": "asyncify-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 17:01:58 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function get_editable_roles() in /wordpress/wp-content/plugins/persian-gravity-sms-pro/includes/main.php:111\nStack trace:\n#0 /wordpress/wp-includes/class-wp-hook.php(324): GFHANNANSMS_Pro::active(false)\n#1 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#2 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#3 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_persia...', false)\n#4 /internal/eval.php(20): activate_plugin('persian-gravity...')\n#5 {main}\n  thrown in /wordpress/wp-content/plugins/persian-gravity-sms-pro/includes/main.php on line 111",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "Uncaught Error: Call to undefined function get_editable_roles() in /wordpress/wp-content/plugins/persian-gravity-sms-pro/includes/main.php:111",
    "level": "FATAL",
    "type": "PHP",
    "test": "asyncify-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 17:02:05 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function get_editable_roles() in /wordpress/wp-content/plugins/persian-gravity-sms-pro/includes/main.php:111\nStack trace:\n#0 /wordpress/wp-includes/class-wp-hook.php(324): GFHANNANSMS_Pro::active(false)\n#1 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#2 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#3 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_persia...', false)\n#4 /internal/eval.php(20): activate_plugin('persian-gravity...')\n#5 {main}\n  thrown in /wordpress/wp-content/plugins/persian-gravity-sms-pro/includes/main.php on line 111\n\n    at Object.onBind (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async V (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:64:10)\n    at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {\n  [cause]: Error: Error when executing the blueprint step #1 ({\"step\":\"installPlugin\",\"pluginData\":{\"resource\":\"wordpress.org/plugins\",\"slug\":\"pica-protector\"},\"options\":{\"activate\":true}}) : Could not download \"https://downloads.wordpress.org/plugin/pica-protector.latest-stable.zip\".\n  \t\t\t\tCheck if the URL is correct and the server is reachable.\n  \t\t\t\tIf it is reachable, the server might be blocking the request.\n  \t\t\t\tCheck the browser console and network tabs for more information.\n  \n  \t\t\t\t## Does the console show the error \"No 'Access-Control-Allow-Origin' header\"?\n  \n  \t\t\t\tThis means the server that hosts your file does not allow requests from other sites\n  \t\t\t\t(cross-origin requests, or CORS).\tYou need to move the asset to a server that allows\n  \t\t\t\tcross-origin file downloads. Learn more about CORS at\n  \t\t\t\thttps://developer.mozilla.org/en-US/docs/Web/HTTP/CORS.\n  \n  \t\t\t\tIf your file is on GitHub, load it from \"raw.githubusercontent.com\".\n  \t\t\t\tHere's how to do that:\n  \n  \t\t\t\t1. Start with the original GitHub URL of the file. For example:\n  \t\t\t\thttps://github.com/username/repository/blob/branch/filename.\n  \t\t\t\t2. Replace \"github.com\" with \"raw.githubusercontent.com\".\n  \t\t\t\t3. Remove the \"/blob/\" part of the URL.\n  \n  \t\t\t\tThe resulting URL should look like this:\n  \t\t\t\thttps://raw.githubusercontent.com/username/repository/branch/filename\n  \n  \t\t\t\tError:\n  \t\t\t\tError: Could not download \"https://downloads.wordpress.org/plugin/pica-protector.latest-stable.zip\"\n      at Object.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12449:19)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async ms (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12552:3)\n      at async Object.onBind (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:227:48)\n      at async V (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:64:10)\n      at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {\n    [cause]: Error: Could not download \"https://downloads.wordpress.org/plugin/pica-protector.latest-stable.zip\".\n    \t\t\t\tCheck if the URL is correct and the server is reachable.\n    \t\t\t\tIf it is reachable, the server might be blocking the request.\n    \t\t\t\tCheck the browser console and network tabs for more information.\n    \n    \t\t\t\t## Does the console show the error \"No 'Access-Control-Allow-Origin' header\"?\n    \n    \t\t\t\tThis means the server that hosts your file does not allow requests from other sites\n    \t\t\t\t(cross-origin requests, or CORS).\tYou need to move the asset to a server that allows\n    \t\t\t\tcross-origin file downloads. Learn more about CORS at\n    \t\t\t\thttps://developer.mozilla.org/en-US/docs/Web/HTTP/CORS.\n    \n    \t\t\t\tIf your file is on GitHub, load it from \"raw.githubusercontent.com\".\n    \t\t\t\tHere's how to do that:\n    \n    \t\t\t\t1. Start with the original GitHub URL of the file. For example:\n    \t\t\t\thttps://github.com/username/repository/blob/branch/filename.\n    \t\t\t\t2. Replace \"github.com\" with \"raw.githubusercontent.com\".\n    \t\t\t\t3. Remove the \"/blob/\" part of the URL.\n    \n    \t\t\t\tThe resulting URL should look like this:\n    \t\t\t\thttps://raw.githubusercontent.com/username/repository/branch/filename\n    \n    \t\t\t\tError:\n    \t\t\t\tError: Could not download \"https://downloads.wordpress.org/plugin/pica-protector.latest-stable.zip\"\n        at Ct.resolve (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:1472:13)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async _.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@php-wasm/util/index.js:45:14)\n  }\n}\n\n",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237\n        throw new Error(y, { cause: u });\n              ^\n",
    "level": "FATAL",
    "type": "PLAYGROUND",
    "test": "jspi-boot",
    "plugin": "pica-protector",
    "details": "file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237\n        throw new Error(y, { cause: u });\n              ^\n",
    "log": "/tmp/tmp.0J69wm452u"
  },
  {
    "message": "SQLSTATE[HY000]: General error: 1 no such table: wp_woocommerce_attribute_taxonomies.",
    "level": "FATAL",
    "type": "SQL",
    "test": "jspi-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 16:57:59 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_invisible INT(1) NULL</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: wp_woocommerce_attribute_taxonomies, ATTRIBUTE_INVISIBLE, int(1)</li>\n<li>Executing: ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_invisible integer NULL | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_woocommerce_attribute_taxonomies.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/product-attribute-global-order-and-visibility/woo-attribute-global-order-visibility.php(37): WP_SQLite_DB->query('ALTER TABLE wp_...')\n#2 /wordpress/wp-includes/class-wp-hook.php(324): pagov_product_attribute_order_visibility(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_produc...', false)\n#6 /internal/eval.php(20): activate_plugin('product-attribu...')\n#7 {main}</pre>\n for query ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_invisible INT(1) NULL made by activate_plugin, do_action('activate_product-attribute-global-order-and-visibility/woo-attribute-global-order-visibility.php'), WP_Hook->do_action, WP_Hook->apply_filters, pagov_product_attribute_order_visibility, WP_SQLite_DB->query, WP_SQLite_DB->print_error",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "SQLSTATE[HY000]: General error: 1 no such table: wp_woocommerce_attribute_taxonomies.",
    "level": "FATAL",
    "type": "SQL",
    "test": "jspi-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 16:57:59 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_custom_order INT(10) NULL</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: wp_woocommerce_attribute_taxonomies, ATTRIBUTE_CUSTOM_ORDER, int(10)</li>\n<li>Executing: ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_custom_order integer NULL | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_woocommerce_attribute_taxonomies.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/product-attribute-global-order-and-visibility/woo-attribute-global-order-visibility.php(38): WP_SQLite_DB->query('ALTER TABLE wp_...')\n#2 /wordpress/wp-includes/class-wp-hook.php(324): pagov_product_attribute_order_visibility(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_produc...', false)\n#6 /internal/eval.php(20): activate_plugin('product-attribu...')\n#7 {main}</pre>\n for query ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_custom_order INT(10) NULL made by activate_plugin, do_action('activate_product-attribute-global-order-and-visibility/woo-attribute-global-order-visibility.php'), WP_Hook->do_action, WP_Hook->apply_filters, pagov_product_attribute_order_visibility, WP_SQLite_DB->query, WP_SQLite_DB->print_error",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "SQLSTATE[HY000]: General error: 1 no such table: wp_woocommerce_attribute_taxonomies.",
    "level": "FATAL",
    "type": "SQL",
    "test": "jspi-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 16:58:07 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_invisible INT(1) NULL</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: wp_woocommerce_attribute_taxonomies, ATTRIBUTE_INVISIBLE, int(1)</li>\n<li>Executing: ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_invisible integer NULL | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_woocommerce_attribute_taxonomies.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/product-attribute-global-order-and-visibility/woo-attribute-global-order-visibility.php(37): WP_SQLite_DB->query('ALTER TABLE wp_...')\n#2 /wordpress/wp-includes/class-wp-hook.php(324): pagov_product_attribute_order_visibility(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_produc...', false)\n#6 /internal/eval.php(20): activate_plugin('product-attribu...')\n#7 {main}</pre>\n for query ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_invisible INT(1) NULL made by activate_plugin, do_action('activate_product-attribute-global-order-and-visibility/woo-attribute-global-order-visibility.php'), WP_Hook->do_action, WP_Hook->apply_filters, pagov_product_attribute_order_visibility, WP_SQLite_DB->query, WP_SQLite_DB->print_error",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "SQLSTATE[HY000]: General error: 1 no such table: wp_woocommerce_attribute_taxonomies.",
    "level": "FATAL",
    "type": "SQL",
    "test": "jspi-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 16:58:07 UTC] WordPress database error <div style=\"clear:both\">&nbsp;</div>\n<div class=\"queries\" style=\"clear:both;margin-bottom:2px;border:red dotted thin;\">\n<p>MySQL query:</p>\n<p>ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_custom_order INT(10) NULL</p>\n<p>Queries made or created this session were:</p>\n<ol>\n<li>Executing: BEGIN | (no parameters)</li>\n<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)\n\t\t\t\tVALUES (:table, :column, :datatype)\n\t\t\t\tON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype\n\t\t\t | parameters: wp_woocommerce_attribute_taxonomies, ATTRIBUTE_CUSTOM_ORDER, int(10)</li>\n<li>Executing: ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_custom_order integer NULL | (no parameters)</li>\n<li>Executing: ROLLBACK | (no parameters)</li>\n</ol>\n</div>\n<div style=\"clear:both;margin-bottom:2px;border:red dotted thin;\" class=\"error_message\" style=\"border-bottom:dotted blue thin;\">\nError occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_woocommerce_attribute_taxonomies.\n</div>\n<p>Backtrace:</p>\n<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()\n#1 /wordpress/wp-content/plugins/product-attribute-global-order-and-visibility/woo-attribute-global-order-visibility.php(38): WP_SQLite_DB->query('ALTER TABLE wp_...')\n#2 /wordpress/wp-includes/class-wp-hook.php(324): pagov_product_attribute_order_visibility(false)\n#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_produc...', false)\n#6 /internal/eval.php(20): activate_plugin('product-attribu...')\n#7 {main}</pre>\n for query ALTER TABLE wp_woocommerce_attribute_taxonomies ADD attribute_custom_order INT(10) NULL made by activate_plugin, do_action('activate_product-attribute-global-order-and-visibility/woo-attribute-global-order-visibility.php'), WP_Hook->do_action, WP_Hook->apply_filters, pagov_product_attribute_order_visibility, WP_SQLite_DB->query, WP_SQLite_DB->print_error",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "level": "DEPRECATED",
    "type": "PHP",
    "test": "jspi-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 16:59:30 UTC] PHP Deprecated:  Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "level": "DEPRECATED",
    "type": "PHP",
    "test": "jspi-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 16:59:31 UTC] PHP Deprecated:  Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "level": "DEPRECATED",
    "type": "PHP",
    "test": "jspi-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 16:59:38 UTC] PHP Deprecated:  Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "level": "DEPRECATED",
    "type": "PHP",
    "test": "jspi-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 16:59:39 UTC] PHP Deprecated:  Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "level": "DEPRECATED",
    "type": "PHP",
    "test": "jspi-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 16:59:47 UTC] PHP Deprecated:  Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "level": "DEPRECATED",
    "type": "PHP",
    "test": "jspi-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 16:59:48 UTC] PHP Deprecated:  Function is_plugin_page is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /wordpress/wp-includes/functions.php on line 6114",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "Uncaught Error: Call to undefined function get_editable_roles() in /wordpress/wp-content/plugins/persian-gravity-sms-pro/includes/main.php:111",
    "level": "FATAL",
    "type": "PHP",
    "test": "jspi-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 17:01:50 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function get_editable_roles() in /wordpress/wp-content/plugins/persian-gravity-sms-pro/includes/main.php:111\nStack trace:\n#0 /wordpress/wp-includes/class-wp-hook.php(324): GFHANNANSMS_Pro::active(false)\n#1 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#2 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#3 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_persia...', false)\n#4 /internal/eval.php(20): activate_plugin('persian-gravity...')\n#5 {main}\n  thrown in /wordpress/wp-content/plugins/persian-gravity-sms-pro/includes/main.php on line 111",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "Uncaught Error: Call to undefined function get_editable_roles() in /wordpress/wp-content/plugins/persian-gravity-sms-pro/includes/main.php:111",
    "level": "FATAL",
    "type": "PHP",
    "test": "jspi-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 17:01:58 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function get_editable_roles() in /wordpress/wp-content/plugins/persian-gravity-sms-pro/includes/main.php:111\nStack trace:\n#0 /wordpress/wp-includes/class-wp-hook.php(324): GFHANNANSMS_Pro::active(false)\n#1 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#2 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#3 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_persia...', false)\n#4 /internal/eval.php(20): activate_plugin('persian-gravity...')\n#5 {main}\n  thrown in /wordpress/wp-content/plugins/persian-gravity-sms-pro/includes/main.php on line 111",
    "log": "/logs/plugins/p/pica-protector/error.json"
  },
  {
    "message": "Uncaught Error: Call to undefined function get_editable_roles() in /wordpress/wp-content/plugins/persian-gravity-sms-pro/includes/main.php:111",
    "level": "FATAL",
    "type": "PHP",
    "test": "jspi-boot",
    "plugin": "pica-protector",
    "details": "[14-Apr-2025 17:02:05 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function get_editable_roles() in /wordpress/wp-content/plugins/persian-gravity-sms-pro/includes/main.php:111\nStack trace:\n#0 /wordpress/wp-includes/class-wp-hook.php(324): GFHANNANSMS_Pro::active(false)\n#1 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)\n#2 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#3 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_persia...', false)\n#4 /internal/eval.php(20): activate_plugin('persian-gravity...')\n#5 {main}\n  thrown in /wordpress/wp-content/plugins/persian-gravity-sms-pro/includes/main.php on line 111\n\n    at Object.onBind (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async V (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:64:10)\n    at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {\n  [cause]: Error: Error when executing the blueprint step #1 ({\"step\":\"installPlugin\",\"pluginData\":{\"resource\":\"wordpress.org/plugins\",\"slug\":\"pica-protector\"},\"options\":{\"activate\":true}}) : Could not download \"https://downloads.wordpress.org/plugin/pica-protector.latest-stable.zip\".\n  \t\t\t\tCheck if the URL is correct and the server is reachable.\n  \t\t\t\tIf it is reachable, the server might be blocking the request.\n  \t\t\t\tCheck the browser console and network tabs for more information.\n  \n  \t\t\t\t## Does the console show the error \"No 'Access-Control-Allow-Origin' header\"?\n  \n  \t\t\t\tThis means the server that hosts your file does not allow requests from other sites\n  \t\t\t\t(cross-origin requests, or CORS).\tYou need to move the asset to a server that allows\n  \t\t\t\tcross-origin file downloads. Learn more about CORS at\n  \t\t\t\thttps://developer.mozilla.org/en-US/docs/Web/HTTP/CORS.\n  \n  \t\t\t\tIf your file is on GitHub, load it from \"raw.githubusercontent.com\".\n  \t\t\t\tHere's how to do that:\n  \n  \t\t\t\t1. Start with the original GitHub URL of the file. For example:\n  \t\t\t\thttps://github.com/username/repository/blob/branch/filename.\n  \t\t\t\t2. Replace \"github.com\" with \"raw.githubusercontent.com\".\n  \t\t\t\t3. Remove the \"/blob/\" part of the URL.\n  \n  \t\t\t\tThe resulting URL should look like this:\n  \t\t\t\thttps://raw.githubusercontent.com/username/repository/branch/filename\n  \n  \t\t\t\tError:\n  \t\t\t\tError: Could not download \"https://downloads.wordpress.org/plugin/pica-protector.latest-stable.zip\"\n      at Object.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12449:19)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async ms (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12552:3)\n      at async Object.onBind (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:227:48)\n      at async V (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:64:10)\n      at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {\n    [cause]: Error: Could not download \"https://downloads.wordpress.org/plugin/pica-protector.latest-stable.zip\".\n    \t\t\t\tCheck if the URL is correct and the server is reachable.\n    \t\t\t\tIf it is reachable, the server might be blocking the request.\n    \t\t\t\tCheck the browser console and network tabs for more information.\n    \n    \t\t\t\t## Does the console show the error \"No 'Access-Control-Allow-Origin' header\"?\n    \n    \t\t\t\tThis means the server that hosts your file does not allow requests from other sites\n    \t\t\t\t(cross-origin requests, or CORS).\tYou need to move the asset to a server that allows\n    \t\t\t\tcross-origin file downloads. Learn more about CORS at\n    \t\t\t\thttps://developer.mozilla.org/en-US/docs/Web/HTTP/CORS.\n    \n    \t\t\t\tIf your file is on GitHub, load it from \"raw.githubusercontent.com\".\n    \t\t\t\tHere's how to do that:\n    \n    \t\t\t\t1. Start with the original GitHub URL of the file. For example:\n    \t\t\t\thttps://github.com/username/repository/blob/branch/filename.\n    \t\t\t\t2. Replace \"github.com\" with \"raw.githubusercontent.com\".\n    \t\t\t\t3. Remove the \"/blob/\" part of the URL.\n    \n    \t\t\t\tThe resulting URL should look like this:\n    \t\t\t\thttps://raw.githubusercontent.com/username/repository/branch/filename\n    \n    \t\t\t\tError:\n    \t\t\t\tError: Could not download \"https://downloads.wordpress.org/plugin/pica-protector.latest-stable.zip\"\n        at Ct.resolve (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:1472:13)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async _.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@php-wasm/util/index.js:45:14)\n  }\n}\n\n",
    "log": "/logs/plugins/p/pica-protector/error.json"
  }
]
