file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237
        throw new Error(y, { cause: u });
              ^

Error: [24-May-2025 21:29:34 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
MySQL query not supported. Cause: SET statement: setStatement
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php(1905): WP_SQLite_Driver->new_not_supported_exception('SET statement: ...')
#1 /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php(885): WP_SQLite_Driver->execute_set_statement(Object(WP_Parser_Node))
#2 /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php(669): WP_SQLite_Driver->execute_mysql_query(Object(WP_Parser_Node))
#3 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(491): WP_SQLite_Driver->query('\n\n/*!40101 SET ...')
#4 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(432): WP_SQLite_DB->_do_query('\n\n/*!40101 SET ...')
#5 /wordpress/wp-content/plugins/blaatschaap-oauth/db.php(91): WP_SQLite_DB->query('\n\n/*!40101 SET ...')
#6 /wordpress/wp-includes/class-wp-hook.php(324): blaatoauth_install_database(false)
#7 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#8 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#9 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_blaats...', false)
#10 /internal/eval.php(20): activate_plugin('blaatschaap-oau...')
#11 {main}</pre>
 for query 

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */ made by activate_plugin, do_action('activate_blaatschaap-oauth/blaatoauth.php'), WP_Hook->do_action, WP_Hook->apply_filters, blaatoauth_install_database, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[24-May-2025 21:29:34 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
MySQL query not supported. Cause: SET statement: setStatement
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php(1905): WP_SQLite_Driver->new_not_supported_exception('SET statement: ...')
#1 /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php(885): WP_SQLite_Driver->execute_set_statement(Object(WP_Parser_Node))
#2 /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php(669): WP_SQLite_Driver->execute_mysql_query(Object(WP_Parser_Node))
#3 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(491): WP_SQLite_Driver->query('\n/*!40101 SET @...')
#4 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(432): WP_SQLite_DB->_do_query('\n/*!40101 SET @...')
#5 /wordpress/wp-content/plugins/blaatschaap-oauth/db.php(91): WP_SQLite_DB->query('\n/*!40101 SET @...')
#6 /wordpress/wp-includes/class-wp-hook.php(324): blaatoauth_install_database(false)
#7 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#8 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#9 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_blaats...', false)
#10 /internal/eval.php(20): activate_plugin('blaatschaap-oau...')
#11 {main}</pre>
 for query 
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */ made by activate_plugin, do_action('activate_blaatschaap-oauth/blaatoauth.php'), WP_Hook->do_action, WP_Hook->apply_filters, blaatoauth_install_database, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[24-May-2025 21:29:34 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
MySQL query not supported. Cause: SET statement: setStatement
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php(1905): WP_SQLite_Driver->new_not_supported_exception('SET statement: ...')
#1 /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php(885): WP_SQLite_Driver->execute_set_statement(Object(WP_Parser_Node))
#2 /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php(669): WP_SQLite_Driver->execute_mysql_query(Object(WP_Parser_Node))
#3 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(491): WP_SQLite_Driver->query('\n/*!40101 SET @...')
#4 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(432): WP_SQLite_DB->_do_query('\n/*!40101 SET @...')
#5 /wordpress/wp-content/plugins/blaatschaap-oauth/db.php(91): WP_SQLite_DB->query('\n/*!40101 SET @...')
#6 /wordpress/wp-includes/class-wp-hook.php(324): blaatoauth_install_database(false)
#7 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#8 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#9 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_blaats...', false)
#10 /internal/eval.php(20): activate_plugin('blaatschaap-oau...')
#11 {main}</pre>
 for query 
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */ made by activate_plugin, do_action('activate_blaatschaap-oauth/blaatoauth.php'), WP_Hook->do_action, WP_Hook->apply_filters, blaatoauth_install_database, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[24-May-2025 21:29:34 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>
/*!40101 SET NAMES utf8 */</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
MySQL query not supported. Cause: SET statement: setStatement
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php(1905): WP_SQLite_Driver->new_not_supported_exception('SET statement: ...')
#1 /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php(885): WP_SQLite_Driver->execute_set_statement(Object(WP_Parser_Node))
#2 /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php(669): WP_SQLite_Driver->execute_mysql_query(Object(WP_Parser_Node))
#3 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(491): WP_SQLite_Driver->query('\n/*!40101 SET N...')
#4 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(432): WP_SQLite_DB->_do_query('\n/*!40101 SET N...')
#5 /wordpress/wp-content/plugins/blaatschaap-oauth/db.php(91): WP_SQLite_DB->query('\n/*!40101 SET N...')
#6 /wordpress/wp-includes/class-wp-hook.php(324): blaatoauth_install_database(false)
#7 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#8 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#9 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_blaats...', false)
#10 /internal/eval.php(20): activate_plugin('blaatschaap-oau...')
#11 {main}</pre>
 for query 
/*!40101 SET NAMES utf8 */ made by activate_plugin, do_action('activate_blaatschaap-oauth/blaatoauth.php'), WP_Hook->do_action, WP_Hook->apply_filters, blaatoauth_install_database, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[24-May-2025 21:29:34 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>
</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Expected 1 child node, got: 0
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php(799): WP_SQLite_Driver->new_driver_exception('Expected 1 chil...')
#1 /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php(669): WP_SQLite_Driver->execute_mysql_query(Object(WP_Parser_Node))
#2 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(491): WP_SQLite_Driver->query('\n')
#3 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(432): WP_SQLite_DB->_do_query('\n')
#4 /wordpress/wp-content/plugins/blaatschaap-oauth/db.php(91): WP_SQLite_DB->query('\n')
#5 /wordpress/wp-includes/class-wp-hook.php(324): blaatoauth_install_database(false)
#6 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#7 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#8 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_blaats...', false)
#9 /internal/eval.php(20): activate_plugin('blaatschaap-oau...')
#10 {main}</pre>
 for query 
 made by activate_plugin, do_action('activate_blaatschaap-oauth/blaatoauth.php'), WP_Hook->do_action, WP_Hook->apply_filters, blaatoauth_install_database, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[24-May-2025 21:29:43 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>
</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown query type: .
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-content/plugins/blaatschaap-oauth/db.php(91): WP_SQLite_DB->query('\n')
#2 /wordpress/wp-includes/class-wp-hook.php(324): blaatoauth_install_database(false)
#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_blaats...', false)
#6 /internal/eval.php(20): activate_plugin('blaatschaap-oau...')
#7 {main}</pre>
 for query 
 made by activate_plugin, do_action('activate_blaatschaap-oauth/blaatoauth.php'), WP_Hook->do_action, WP_Hook->apply_filters, blaatoauth_install_database, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[24-May-2025 21:29:53 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>
</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown query type: .
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-content/plugins/blaatschaap-oauth/db.php(91): WP_SQLite_DB->query('\n')
#2 /wordpress/wp-includes/class-wp-hook.php(324): blaatoauth_install_database(false)
#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_blaats...', false)
#6 /internal/eval.php(20): activate_plugin('blaatschaap-oau...')
#7 {main}</pre>
 for query 
 made by activate_plugin, do_action('activate_blaatschaap-oauth/blaatoauth.php'), WP_Hook->do_action, WP_Hook->apply_filters, blaatoauth_install_database, WP_SQLite_DB->query, WP_SQLite_DB->print_error

    at Object.onBind (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async V (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:64:10)
    at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {
  [cause]: Error: Error when executing the blueprint step #5 ({"step":"installPlugin","pluginData":{"resource":"wordpress.org/plugins","slug":"buy-x-get-y-free-by-storepro"},"options":{"activate":true}}) : Plugin /wordpress/wp-content/plugins/buy-x-get-y-free-by-storepro could not be activated – WordPress exited with no error. Sometimes, when $_SERVER or site options are not configured correctly, WordPress exits early with a 301 redirect. Inspect the "debug" logs in the console for more details.
      at Object.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12449:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async ms (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12552:3)
      ... 2 lines matching cause stack trace ...
      at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {
    [cause]: Error: Plugin /wordpress/wp-content/plugins/buy-x-get-y-free-by-storepro could not be activated – WordPress exited with no error. Sometimes, when $_SERVER or site options are not configured correctly, WordPress exits early with a 301 redirect. Inspect the "debug" logs in the console for more details.
        at wr (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:119:51)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async Object.gt [as installPlugin] (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:974:42)
        at async g (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12517:30)
        at async Object.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12446:23)
        at async ms (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12552:3)
        at async Object.onBind (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:227:48)
        at async V (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:64:10)
        at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12)
  }
}

Node.js v23.11.0
