file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237
        throw new Error(y, { cause: u });
              ^

Error: [20-May-2025 01:56:59 UTC] PHP Parse error:  syntax error, unexpected '$req' (T_VARIABLE), expecting ',' or ')' in /wordpress/wp-content/plugins/cybershield-waf/cybershield-wp-plugin.php on line 201
[20-May-2025 01:57:07 UTC] PHP Parse error:  syntax error, unexpected '$req' (T_VARIABLE), expecting ',' or ')' in /wordpress/wp-content/plugins/cybershield-waf/cybershield-wp-plugin.php on line 201
[20-May-2025 01:57:15 UTC] PHP Parse error:  syntax error, unexpected '$req' (T_VARIABLE), expecting ',' or ')' in /wordpress/wp-content/plugins/cybershield-waf/cybershield-wp-plugin.php on line 201
[20-May-2025 01:58:18 UTC] PHP Fatal error:  Uncaught Error: Undefined constant "_PAGE_TITLE" in /wordpress/wp-content/plugins/casals-online-seo/settings.php:4
Stack trace:
#0 /wordpress/wp-content/plugins/casals-online-seo/casals-online-seo.php(16): require_once()
#1 /wordpress/wp-admin/includes/plugin.php(2387): include_once('/wordpress/wp-c...')
#2 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('casals-online-s...')
#3 /internal/eval.php(20): activate_plugin('casals-online-s...')
#4 {main}
  thrown in /wordpress/wp-content/plugins/casals-online-seo/settings.php on line 4
[20-May-2025 01:58:26 UTC] PHP Fatal error:  Uncaught Error: Undefined constant "_PAGE_TITLE" in /wordpress/wp-content/plugins/casals-online-seo/settings.php:4
Stack trace:
#0 /wordpress/wp-content/plugins/casals-online-seo/casals-online-seo.php(16): require_once()
#1 /wordpress/wp-admin/includes/plugin.php(2387): include_once('/wordpress/wp-c...')
#2 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('casals-online-s...')
#3 /internal/eval.php(20): activate_plugin('casals-online-s...')
#4 {main}
  thrown in /wordpress/wp-content/plugins/casals-online-seo/settings.php on line 4
[20-May-2025 01:58:33 UTC] PHP Fatal error:  Uncaught Error: Undefined constant "_PAGE_TITLE" in /wordpress/wp-content/plugins/casals-online-seo/settings.php:4
Stack trace:
#0 /wordpress/wp-content/plugins/casals-online-seo/casals-online-seo.php(16): require_once()
#1 /wordpress/wp-admin/includes/plugin.php(2387): include_once('/wordpress/wp-c...')
#2 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('casals-online-s...')
#3 /internal/eval.php(20): activate_plugin('casals-online-s...')
#4 {main}
  thrown in /wordpress/wp-content/plugins/casals-online-seo/settings.php on line 4
[20-May-2025 01:59:41 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>DELETE FROM wp_chained_completed WHERE not_empty=0 AND datetime < '2025-05-20 01:59:41' - INTERVAL 24 HOUR</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: DELETE FROM `wp_chained_completed` WHERE `not_empty` = 0 AND `datetime` &lt; '2025-05-20 01:59:41' - INTERVAL 24 HOUR | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
SQLSTATE[HY000]: General error: 1 near "24": syntax error
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php(683): WP_SQLite_Driver->new_driver_exception('SQLSTATE[HY000]...', 'HY000', Object(PDOException))
#1 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(491): WP_SQLite_Driver->query('DELETE FROM wp_...')
#2 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(432): WP_SQLite_DB->_do_query('DELETE FROM wp_...')
#3 /wordpress/wp-content/plugins/chained-quiz/models/basic.php(259): WP_SQLite_DB->query('DELETE FROM wp_...')
#4 /wordpress/wp-includes/class-wp-hook.php(324): ChainedQuiz::init('')
#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /wordpress/wp-settings.php(727): do_action('init')
#8 /wordpress/wp-config.php(102): require_once('/wordpress/wp-s...')
#9 /wordpress/wp-load.php(50): require_once('/wordpress/wp-c...')
#10 /internal/eval.php(3): require_once('/wordpress/wp-l...')
#11 {main}</pre>
 for query DELETE FROM wp_chained_completed WHERE not_empty=0 AND datetime < '2025-05-20 01:59:41' - INTERVAL 24 HOUR made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, ChainedQuiz::init, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[20-May-2025 01:59:48 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>ALTER TABLE `wp_chained_questions` ADD autocontinue TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD sort_order INT UNSIGNED NOT NULL DEFAULT 0, ADD accept_comments TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD accept_comments_label VARCHAR(255) NOT NULL DEFAULT ''</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)
				VALUES (:table, :column, :datatype)
				ON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype
			 | parameters: wp_chained_questions, AUTOCONTINUE, tinyint UNSIGNED</li>
<li>Executing: ALTER TABLE wp_chained_questions ADD autocontinue  integer NOT NULL DEFAULT 0 | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 duplicate column name: autocontinue.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-content/plugins/chained-quiz/helpers/htmlhelper.php(34): WP_SQLite_DB->query('ALTER TABLE `wp...')
#2 /wordpress/wp-content/plugins/chained-quiz/models/basic.php(115): chainedquiz_add_db_fields(Array, 'wp_chained_ques...')
#3 /wordpress/wp-includes/class-wp-hook.php(324): ChainedQuiz::install(false)
#4 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#5 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_chaine...', false)
#7 /internal/eval.php(20): activate_plugin('chained-quiz/ch...')
#8 {main}</pre>
 for query ALTER TABLE `wp_chained_questions` ADD autocontinue TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD sort_order INT UNSIGNED NOT NULL DEFAULT 0, ADD accept_comments TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD accept_comments_label VARCHAR(255) NOT NULL DEFAULT '' made by activate_plugin, do_action('activate_chained-quiz/chained-quiz.php'), WP_Hook->do_action, WP_Hook->apply_filters, ChainedQuiz::install, chainedquiz_add_db_fields, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[20-May-2025 01:59:48 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>ALTER TABLE `wp_chained_results` ADD redirect_url VARCHAR(255) NOT NULL DEFAULT ''</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)
				VALUES (:table, :column, :datatype)
				ON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype
			 | parameters: wp_chained_results, REDIRECT_URL, varchar(255)</li>
<li>Executing: ALTER TABLE wp_chained_results ADD redirect_url text NOT NULL DEFAULT '' | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 duplicate column name: redirect_url.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-content/plugins/chained-quiz/helpers/htmlhelper.php(34): WP_SQLite_DB->query('ALTER TABLE `wp...')
#2 /wordpress/wp-content/plugins/chained-quiz/models/basic.php(119): chainedquiz_add_db_fields(Array, 'wp_chained_resu...')
#3 /wordpress/wp-includes/class-wp-hook.php(324): ChainedQuiz::install(false)
#4 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#5 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_chaine...', false)
#7 /internal/eval.php(20): activate_plugin('chained-quiz/ch...')
#8 {main}</pre>
 for query ALTER TABLE `wp_chained_results` ADD redirect_url VARCHAR(255) NOT NULL DEFAULT '' made by activate_plugin, do_action('activate_chained-quiz/chained-quiz.php'), WP_Hook->do_action, WP_Hook->apply_filters, ChainedQuiz::install, chainedquiz_add_db_fields, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[20-May-2025 01:59:48 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>ALTER TABLE `wp_chained_user_answers` ADD comments TEXT, ADD is_correct TINYINT UNSIGNED NOT NULL DEFAULT 0</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)
				VALUES (:table, :column, :datatype)
				ON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype
			 | parameters: wp_chained_user_answers, COMMENTS, text</li>
<li>Executing: ALTER TABLE wp_chained_user_answers ADD comments text | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 duplicate column name: comments.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-content/plugins/chained-quiz/helpers/htmlhelper.php(34): WP_SQLite_DB->query('ALTER TABLE `wp...')
#2 /wordpress/wp-content/plugins/chained-quiz/models/basic.php(124): chainedquiz_add_db_fields(Array, 'wp_chained_user...')
#3 /wordpress/wp-includes/class-wp-hook.php(324): ChainedQuiz::install(false)
#4 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#5 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_chaine...', false)
#7 /internal/eval.php(20): activate_plugin('chained-quiz/ch...')
#8 {main}</pre>
 for query ALTER TABLE `wp_chained_user_answers` ADD comments TEXT, ADD is_correct TINYINT UNSIGNED NOT NULL DEFAULT 0 made by activate_plugin, do_action('activate_chained-quiz/chained-quiz.php'), WP_Hook->do_action, WP_Hook->apply_filters, ChainedQuiz::install, chainedquiz_add_db_fields, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[20-May-2025 01:59:48 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>ALTER TABLE `wp_chained_quizzes` ADD email_admin TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD email_user TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD require_login TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD times_to_take INT UNSIGNED NOT NULL DEFAULT 0, ADD save_source_url TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD set_email_output TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD email_output TEXT, ADD admin_email VARCHAR(255) NOT NULL DEFAULT '', ADD email_required TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD hide_email_field TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD require_text_captcha TINYINT UNSIGNED NOT NULL DEFAULT 0</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)
				VALUES (:table, :column, :datatype)
				ON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype
			 | parameters: wp_chained_quizzes, EMAIL_ADMIN, tinyint UNSIGNED</li>
<li>Executing: ALTER TABLE wp_chained_quizzes ADD email_admin  integer NOT NULL DEFAULT 0 | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 duplicate column name: email_admin.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-content/plugins/chained-quiz/helpers/htmlhelper.php(34): WP_SQLite_DB->query('ALTER TABLE `wp...')
#2 /wordpress/wp-content/plugins/chained-quiz/models/basic.php(138): chainedquiz_add_db_fields(Array, 'wp_chained_quiz...')
#3 /wordpress/wp-includes/class-wp-hook.php(324): ChainedQuiz::install(false)
#4 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#5 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_chaine...', false)
#7 /internal/eval.php(20): activate_plugin('chained-quiz/ch...')
#8 {main}</pre>
 for query ALTER TABLE `wp_chained_quizzes` ADD email_admin TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD email_user TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD require_login TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD times_to_take INT UNSIGNED NOT NULL DEFAULT 0, ADD save_source_url TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD set_email_output TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD email_output TEXT, ADD admin_email VARCHAR(255) NOT NULL DEFAULT '', ADD email_required TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD hide_email_field TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD require_text_captcha TINYINT UNSIGNED NOT NULL DEFAULT 0 made by activate_plugin, do_action('activate_chained-quiz/chained-quiz.php'), WP_Hook->do_action, WP_Hook->apply_filters, ChainedQuiz::install, chainedquiz_add_db_fields, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[20-May-2025 01:59:48 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>ALTER TABLE `wp_chained_completed` ADD not_empty TINYINT NOT NULL DEFAULT 0, ADD source_url VARCHAR(255) NOT NULL DEFAULT '', ADD email VARCHAR(255) NOT NULL DEFAULT ''</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)
				VALUES (:table, :column, :datatype)
				ON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype
			 | parameters: wp_chained_completed, NOT_EMPTY, tinyint</li>
<li>Executing: ALTER TABLE wp_chained_completed ADD not_empty integer NOT NULL DEFAULT 0 | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 duplicate column name: not_empty.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-content/plugins/chained-quiz/helpers/htmlhelper.php(34): WP_SQLite_DB->query('ALTER TABLE `wp...')
#2 /wordpress/wp-content/plugins/chained-quiz/models/basic.php(144): chainedquiz_add_db_fields(Array, 'wp_chained_comp...')
#3 /wordpress/wp-includes/class-wp-hook.php(324): ChainedQuiz::install(false)
#4 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#5 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_chaine...', false)
#7 /internal/eval.php(20): activate_plugin('chained-quiz/ch...')
#8 {main}</pre>
 for query ALTER TABLE `wp_chained_completed` ADD not_empty TINYINT NOT NULL DEFAULT 0, ADD source_url VARCHAR(255) NOT NULL DEFAULT '', ADD email VARCHAR(255) NOT NULL DEFAULT '' made by activate_plugin, do_action('activate_chained-quiz/chained-quiz.php'), WP_Hook->do_action, WP_Hook->apply_filters, ChainedQuiz::install, chainedquiz_add_db_fields, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[20-May-2025 01:59:48 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>ALTER TABLE `wp_chained_mail_relations` ADD tags TEXT</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)
				VALUES (:table, :column, :datatype)
				ON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype
			 | parameters: wp_chained_mail_relations, TAGS, text</li>
<li>Executing: ALTER TABLE wp_chained_mail_relations ADD tags text | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 duplicate column name: tags.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-content/plugins/chained-quiz/helpers/htmlhelper.php(34): WP_SQLite_DB->query('ALTER TABLE `wp...')
#2 /wordpress/wp-content/plugins/chained-quiz/models/basic.php(148): chainedquiz_add_db_fields(Array, 'wp_chained_mail...')
#3 /wordpress/wp-includes/class-wp-hook.php(324): ChainedQuiz::install(false)
#4 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#5 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_chaine...', false)
#7 /internal/eval.php(20): activate_plugin('chained-quiz/ch...')
#8 {main}</pre>
 for query ALTER TABLE `wp_chained_mail_relations` ADD tags TEXT made by activate_plugin, do_action('activate_chained-quiz/chained-quiz.php'), WP_Hook->do_action, WP_Hook->apply_filters, ChainedQuiz::install, chainedquiz_add_db_fields, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[20-May-2025 01:59:57 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>ALTER TABLE `wp_chained_questions` ADD autocontinue TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD sort_order INT UNSIGNED NOT NULL DEFAULT 0, ADD accept_comments TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD accept_comments_label VARCHAR(255) NOT NULL DEFAULT ''</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)
				VALUES (:table, :column, :datatype)
				ON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype
			 | parameters: wp_chained_questions, AUTOCONTINUE, tinyint UNSIGNED</li>
<li>Executing: ALTER TABLE wp_chained_questions ADD autocontinue  integer NOT NULL DEFAULT 0 | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 duplicate column name: autocontinue.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-content/plugins/chained-quiz/helpers/htmlhelper.php(34): WP_SQLite_DB->query('ALTER TABLE `wp...')
#2 /wordpress/wp-content/plugins/chained-quiz/models/basic.php(115): chainedquiz_add_db_fields(Array, 'wp_chained_ques...')
#3 /wordpress/wp-includes/class-wp-hook.php(324): ChainedQuiz::install(false)
#4 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#5 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_chaine...', false)
#7 /internal/eval.php(20): activate_plugin('chained-quiz/ch...')
#8 {main}</pre>
 for query ALTER TABLE `wp_chained_questions` ADD autocontinue TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD sort_order INT UNSIGNED NOT NULL DEFAULT 0, ADD accept_comments TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD accept_comments_label VARCHAR(255) NOT NULL DEFAULT '' made by activate_plugin, do_action('activate_chained-quiz/chained-quiz.php'), WP_Hook->do_action, WP_Hook->apply_filters, ChainedQuiz::install, chainedquiz_add_db_fields, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[20-May-2025 01:59:57 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>ALTER TABLE `wp_chained_results` ADD redirect_url VARCHAR(255) NOT NULL DEFAULT ''</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)
				VALUES (:table, :column, :datatype)
				ON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype
			 | parameters: wp_chained_results, REDIRECT_URL, varchar(255)</li>
<li>Executing: ALTER TABLE wp_chained_results ADD redirect_url text NOT NULL DEFAULT '' | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 duplicate column name: redirect_url.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-content/plugins/chained-quiz/helpers/htmlhelper.php(34): WP_SQLite_DB->query('ALTER TABLE `wp...')
#2 /wordpress/wp-content/plugins/chained-quiz/models/basic.php(119): chainedquiz_add_db_fields(Array, 'wp_chained_resu...')
#3 /wordpress/wp-includes/class-wp-hook.php(324): ChainedQuiz::install(false)
#4 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#5 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_chaine...', false)
#7 /internal/eval.php(20): activate_plugin('chained-quiz/ch...')
#8 {main}</pre>
 for query ALTER TABLE `wp_chained_results` ADD redirect_url VARCHAR(255) NOT NULL DEFAULT '' made by activate_plugin, do_action('activate_chained-quiz/chained-quiz.php'), WP_Hook->do_action, WP_Hook->apply_filters, ChainedQuiz::install, chainedquiz_add_db_fields, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[20-May-2025 01:59:57 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>ALTER TABLE `wp_chained_user_answers` ADD comments TEXT, ADD is_correct TINYINT UNSIGNED NOT NULL DEFAULT 0</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)
				VALUES (:table, :column, :datatype)
				ON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype
			 | parameters: wp_chained_user_answers, COMMENTS, text</li>
<li>Executing: ALTER TABLE wp_chained_user_answers ADD comments text | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 duplicate column name: comments.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-content/plugins/chained-quiz/helpers/htmlhelper.php(34): WP_SQLite_DB->query('ALTER TABLE `wp...')
#2 /wordpress/wp-content/plugins/chained-quiz/models/basic.php(124): chainedquiz_add_db_fields(Array, 'wp_chained_user...')
#3 /wordpress/wp-includes/class-wp-hook.php(324): ChainedQuiz::install(false)
#4 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#5 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_chaine...', false)
#7 /internal/eval.php(20): activate_plugin('chained-quiz/ch...')
#8 {main}</pre>
 for query ALTER TABLE `wp_chained_user_answers` ADD comments TEXT, ADD is_correct TINYINT UNSIGNED NOT NULL DEFAULT 0 made by activate_plugin, do_action('activate_chained-quiz/chained-quiz.php'), WP_Hook->do_action, WP_Hook->apply_filters, ChainedQuiz::install, chainedquiz_add_db_fields, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[20-May-2025 01:59:57 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>ALTER TABLE `wp_chained_quizzes` ADD email_admin TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD email_user TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD require_login TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD times_to_take INT UNSIGNED NOT NULL DEFAULT 0, ADD save_source_url TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD set_email_output TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD email_output TEXT, ADD admin_email VARCHAR(255) NOT NULL DEFAULT '', ADD email_required TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD hide_email_field TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD require_text_captcha TINYINT UNSIGNED NOT NULL DEFAULT 0</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)
				VALUES (:table, :column, :datatype)
				ON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype
			 | parameters: wp_chained_quizzes, EMAIL_ADMIN, tinyint UNSIGNED</li>
<li>Executing: ALTER TABLE wp_chained_quizzes ADD email_admin  integer NOT NULL DEFAULT 0 | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 duplicate column name: email_admin.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-content/plugins/chained-quiz/helpers/htmlhelper.php(34): WP_SQLite_DB->query('ALTER TABLE `wp...')
#2 /wordpress/wp-content/plugins/chained-quiz/models/basic.php(138): chainedquiz_add_db_fields(Array, 'wp_chained_quiz...')
#3 /wordpress/wp-includes/class-wp-hook.php(324): ChainedQuiz::install(false)
#4 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#5 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_chaine...', false)
#7 /internal/eval.php(20): activate_plugin('chained-quiz/ch...')
#8 {main}</pre>
 for query ALTER TABLE `wp_chained_quizzes` ADD email_admin TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD email_user TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD require_login TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD times_to_take INT UNSIGNED NOT NULL DEFAULT 0, ADD save_source_url TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD set_email_output TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD email_output TEXT, ADD admin_email VARCHAR(255) NOT NULL DEFAULT '', ADD email_required TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD hide_email_field TINYINT UNSIGNED NOT NULL DEFAULT 0, ADD require_text_captcha TINYINT UNSIGNED NOT NULL DEFAULT 0 made by activate_plugin, do_action('activate_chained-quiz/chained-quiz.php'), WP_Hook->do_action, WP_Hook->apply_filters, ChainedQuiz::install, chainedquiz_add_db_fields, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[20-May-2025 01:59:57 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>ALTER TABLE `wp_chained_completed` ADD not_empty TINYINT NOT NULL DEFAULT 0, ADD source_url VARCHAR(255) NOT NULL DEFAULT '', ADD email VARCHAR(255) NOT NULL DEFAULT ''</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)
				VALUES (:table, :column, :datatype)
				ON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype
			 | parameters: wp_chained_completed, NOT_EMPTY, tinyint</li>
<li>Executing: ALTER TABLE wp_chained_completed ADD not_empty integer NOT NULL DEFAULT 0 | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 duplicate column name: not_empty.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-content/plugins/chained-quiz/helpers/htmlhelper.php(34): WP_SQLite_DB->query('ALTER TABLE `wp...')
#2 /wordpress/wp-content/plugins/chained-quiz/models/basic.php(144): chainedquiz_add_db_fields(Array, 'wp_chained_comp...')
#3 /wordpress/wp-includes/class-wp-hook.php(324): ChainedQuiz::install(false)
#4 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#5 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_chaine...', false)
#7 /internal/eval.php(20): activate_plugin('chained-quiz/ch...')
#8 {main}</pre>
 for query ALTER TABLE `wp_chained_completed` ADD not_empty TINYINT NOT NULL DEFAULT 0, ADD source_url VARCHAR(255) NOT NULL DEFAULT '', ADD email VARCHAR(255) NOT NULL DEFAULT '' made by activate_plugin, do_action('activate_chained-quiz/chained-quiz.php'), WP_Hook->do_action, WP_Hook->apply_filters, ChainedQuiz::install, chainedquiz_add_db_fields, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[20-May-2025 01:59:57 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>ALTER TABLE `wp_chained_mail_relations` ADD tags TEXT</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: INSERT INTO _mysql_data_types_cache (`table`, `column_or_index`, `mysql_type`)
				VALUES (:table, :column, :datatype)
				ON CONFLICT(`table`, `column_or_index`) DO UPDATE SET `mysql_type` = :datatype
			 | parameters: wp_chained_mail_relations, TAGS, text</li>
<li>Executing: ALTER TABLE wp_chained_mail_relations ADD tags text | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 duplicate column name: tags.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-content/plugins/chained-quiz/helpers/htmlhelper.php(34): WP_SQLite_DB->query('ALTER TABLE `wp...')
#2 /wordpress/wp-content/plugins/chained-quiz/models/basic.php(148): chainedquiz_add_db_fields(Array, 'wp_chained_mail...')
#3 /wordpress/wp-includes/class-wp-hook.php(324): ChainedQuiz::install(false)
#4 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#5 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_chaine...', false)
#7 /internal/eval.php(20): activate_plugin('chained-quiz/ch...')
#8 {main}</pre>
 for query ALTER TABLE `wp_chained_mail_relations` ADD tags TEXT made by activate_plugin, do_action('activate_chained-quiz/chained-quiz.php'), WP_Hook->do_action, WP_Hook->apply_filters, ChainedQuiz::install, chainedquiz_add_db_fields, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[20-May-2025 02:01:27 UTC] PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /wordpress/wp-content/plugins/custom-post-permalinks/custom-post-permalinks.php on line 353
[20-May-2025 02:01:35 UTC] PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /wordpress/wp-content/plugins/custom-post-permalinks/custom-post-permalinks.php on line 353
[20-May-2025 02:01:44 UTC] PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /wordpress/wp-content/plugins/custom-post-permalinks/custom-post-permalinks.php on line 353
[20-May-2025 02:02:22 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>SELECT * FROM wp_clickky_ads WHERE name='Native Apps' AND status=1</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: SELECT * FROM `wp_clickky_ads` WHERE `name` = 'Native Apps' AND `status` = 1 | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
SQLSTATE[HY000]: General error: 1 no such table: wp_clickky_ads
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php(683): WP_SQLite_Driver->new_driver_exception('SQLSTATE[HY000]...', 'HY000', Object(PDOException))
#1 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(491): WP_SQLite_Driver->query('SELECT * FROM w...')
#2 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(432): WP_SQLite_DB->_do_query('SELECT * FROM w...')
#3 /wordpress/wp-includes/class-wpdb.php(3146): WP_SQLite_DB->query('SELECT * FROM w...')
#4 /wordpress/wp-content/plugins/clickkys-mobile-web-monetization-tool/public/class-clickky-public.php(56): wpdb->get_results('SELECT * FROM w...')
#5 /wordpress/wp-content/plugins/clickkys-mobile-web-monetization-tool/includes/class-clickky.php(187): Clickky_Public->__construct('clickky', '1.3.6')
#6 /wordpress/wp-content/plugins/clickkys-mobile-web-monetization-tool/includes/class-clickky.php(65): Clickky->define_public_hooks()
#7 /wordpress/wp-content/plugins/clickkys-mobile-web-monetization-tool/clickky.php(69): Clickky->__construct()
#8 /wordpress/wp-content/plugins/clickkys-mobile-web-monetization-tool/clickky.php(73): run_clickky()
#9 /wordpress/wp-admin/includes/plugin.php(2387): include_once('/wordpress/wp-c...')
#10 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('clickkys-mobile...')
#11 /internal/eval.php(20): activate_plugin('clickkys-mobile...')
#12 {main}</pre>
 for query SELECT * FROM wp_clickky_ads WHERE name='Native Apps' AND status=1 made by activate_plugin, plugin_sandbox_scrape, include_once('/plugins/clickkys-mobile-web-monetization-tool/clickky.php'), run_clickky, Clickky->__construct, Clickky->define_public_hooks, Clickky_Public->__construct, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[20-May-2025 02:02:22 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>SELECT * FROM wp_clickky_ads WHERE name='Native Apps' AND status=1</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: SELECT * FROM `wp_clickky_ads` WHERE `name` = 'Native Apps' AND `status` = 1 | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
SQLSTATE[HY000]: General error: 1 no such table: wp_clickky_ads
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite-ast/class-wp-sqlite-driver.php(683): WP_SQLite_Driver->new_driver_exception('SQLSTATE[HY000]...', 'HY000', Object(PDOException))
#1 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(491): WP_SQLite_Driver->query('SELECT * FROM w...')
#2 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(432): WP_SQLite_DB->_do_query('SELECT * FROM w...')
#3 /wordpress/wp-includes/class-wpdb.php(3146): WP_SQLite_DB->query('SELECT * FROM w...')
#4 /wordpress/wp-content/plugins/clickkys-mobile-web-monetization-tool/includes/class-clickky.php(205): wpdb->get_results('SELECT * FROM w...')
#5 /wordpress/wp-content/plugins/clickkys-mobile-web-monetization-tool/includes/class-clickky.php(65): Clickky->define_public_hooks()
#6 /wordpress/wp-content/plugins/clickkys-mobile-web-monetization-tool/clickky.php(69): Clickky->__construct()
#7 /wordpress/wp-content/plugins/clickkys-mobile-web-monetization-tool/clickky.php(73): run_clickky()
#8 /wordpress/wp-admin/includes/plugin.php(2387): include_once('/wordpress/wp-c...')
#9 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('clickkys-mobile...')
#10 /internal/eval.php(20): activate_plugin('clickkys-mobile...')
#11 {main}</pre>
 for query SELECT * FROM wp_clickky_ads WHERE name='Native Apps' AND status=1 made by activate_plugin, plugin_sandbox_scrape, include_once('/plugins/clickkys-mobile-web-monetization-tool/clickky.php'), run_clickky, Clickky->__construct, Clickky->define_public_hooks, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[20-May-2025 02:02:23 UTC] PHP Notice:  Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>clickky</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /wordpress/wp-includes/functions.php on line 6121
[20-May-2025 02:02:31 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>SELECT * FROM wp_clickky_ads WHERE name='Native Apps' AND status=1</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: SELECT * FROM wp_clickky_ads WHERE name=:param0  AND status=1 | parameters: Native Apps</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_clickky_ads.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-includes/class-wpdb.php(3146): WP_SQLite_DB->query('SELECT * FROM w...')
#2 /wordpress/wp-content/plugins/clickkys-mobile-web-monetization-tool/public/class-clickky-public.php(56): wpdb->get_results('SELECT * FROM w...')
#3 /wordpress/wp-content/plugins/clickkys-mobile-web-monetization-tool/includes/class-clickky.php(187): Clickky_Public->__construct('clickky', '1.3.6')
#4 /wordpress/wp-content/plugins/clickkys-mobile-web-monetization-tool/includes/class-clickky.php(65): Clickky->define_public_hooks()
#5 /wordpress/wp-content/plugins/clickkys-mobile-web-monetization-tool/clickky.php(69): Clickky->__construct()
#6 /wordpress/wp-content/plugins/clickkys-mobile-web-monetization-tool/clickky.php(73): run_clickky()
#7 /wordpress/wp-admin/includes/plugin.php(2387): include_once('/wordpress/wp-c...')
#8 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('clickkys-mobile...')
#9 /internal/eval.php(20): activate_plugin('clickkys-mobile...')
#10 {main}</pre>
 for query SELECT * FROM wp_clickky_ads WHERE name='Native Apps' AND status=1 made by activate_plugin, plugin_sandbox_scrape, include_once('/plugins/clickkys-mobile-web-monetization-tool/clickky.php'), run_clickky, Clickky->__construct, Clickky->define_public_hooks, Clickky_Public->__construct, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[20-May-2025 02:02:31 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>SELECT * FROM wp_clickky_ads WHERE name='Native Apps' AND status=1</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: SELECT * FROM wp_clickky_ads WHERE name=:param0  AND status=1 | parameters: Native Apps</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_clickky_ads.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-includes/class-wpdb.php(3146): WP_SQLite_DB->query('SELECT * FROM w...')
#2 /wordpress/wp-content/plugins/clickkys-mobile-web-monetization-tool/includes/class-clickky.php(205): wpdb->get_results('SELECT * FROM w...')
#3 /wordpress/wp-content/plugins/clickkys-mobile-web-monetization-tool/includes/class-clickky.php(65): Clickky->define_public_hooks()
#4 /wordpress/wp-content/plugins/clickkys-mobile-web-monetization-tool/clickky.php(69): Clickky->__construct()
#5 /wordpress/wp-content/plugins/clickkys-mobile-web-monetization-tool/clickky.php(73): run_clickky()
#6 /wordpress/wp-admin/includes/plugin.php(2387): include_once('/wordpress/wp-c...')
#7 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('clickkys-mobile...')
#8 /internal/eval.php(20): activate_plugin('clickkys-mobile...')
#9 {main}</pre>
 for query SELECT * FROM wp_clickky_ads WHERE name='Native Apps' AND status=1 made by activate_plugin, plugin_sandbox_scrape, include_once('/plugins/clickkys-mobile-web-monetization-tool/clickky.php'), run_clickky, Clickky->__construct, Clickky->define_public_hooks, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[20-May-2025 02:02:32 UTC] PHP Notice:  Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>clickky</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /wordpress/wp-includes/functions.php on line 6121
[20-May-2025 02:02:40 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>SELECT * FROM wp_clickky_ads WHERE name='Native Apps' AND status=1</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: SELECT * FROM wp_clickky_ads WHERE name=:param0  AND status=1 | parameters: Native Apps</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_clickky_ads.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-includes/class-wpdb.php(3146): WP_SQLite_DB->query('SELECT * FROM w...')
#2 /wordpress/wp-content/plugins/clickkys-mobile-web-monetization-tool/public/class-clickky-public.php(56): wpdb->get_results('SELECT * FROM w...')
#3 /wordpress/wp-content/plugins/clickkys-mobile-web-monetization-tool/includes/class-clickky.php(187): Clickky_Public->__construct('clickky', '1.3.6')
#4 /wordpress/wp-content/plugins/clickkys-mobile-web-monetization-tool/includes/class-clickky.php(65): Clickky->define_public_hooks()
#5 /wordpress/wp-content/plugins/clickkys-mobile-web-monetization-tool/clickky.php(69): Clickky->__construct()
#6 /wordpress/wp-content/plugins/clickkys-mobile-web-monetization-tool/clickky.php(73): run_clickky()
#7 /wordpress/wp-admin/includes/plugin.php(2387): include_once('/wordpress/wp-c...')
#8 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('clickkys-mobile...')
#9 /internal/eval.php(20): activate_plugin('clickkys-mobile...')
#10 {main}</pre>
 for query SELECT * FROM wp_clickky_ads WHERE name='Native Apps' AND status=1 made by activate_plugin, plugin_sandbox_scrape, include_once('/plugins/clickkys-mobile-web-monetization-tool/clickky.php'), run_clickky, Clickky->__construct, Clickky->define_public_hooks, Clickky_Public->__construct, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[20-May-2025 02:02:40 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>SELECT * FROM wp_clickky_ads WHERE name='Native Apps' AND status=1</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: SELECT * FROM wp_clickky_ads WHERE name=:param0  AND status=1 | parameters: Native Apps</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: SQLSTATE[HY000]: General error: 1 no such table: wp_clickky_ads.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-includes/class-wpdb.php(3146): WP_SQLite_DB->query('SELECT * FROM w...')
#2 /wordpress/wp-content/plugins/clickkys-mobile-web-monetization-tool/includes/class-clickky.php(205): wpdb->get_results('SELECT * FROM w...')
#3 /wordpress/wp-content/plugins/clickkys-mobile-web-monetization-tool/includes/class-clickky.php(65): Clickky->define_public_hooks()
#4 /wordpress/wp-content/plugins/clickkys-mobile-web-monetization-tool/clickky.php(69): Clickky->__construct()
#5 /wordpress/wp-content/plugins/clickkys-mobile-web-monetization-tool/clickky.php(73): run_clickky()
#6 /wordpress/wp-admin/includes/plugin.php(2387): include_once('/wordpress/wp-c...')
#7 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('clickkys-mobile...')
#8 /internal/eval.php(20): activate_plugin('clickkys-mobile...')
#9 {main}</pre>
 for query SELECT * FROM wp_clickky_ads WHERE name='Native Apps' AND status=1 made by activate_plugin, plugin_sandbox_scrape, include_once('/plugins/clickkys-mobile-web-monetization-tool/clickky.php'), run_clickky, Clickky->__construct, Clickky->define_public_hooks, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[20-May-2025 02:02:41 UTC] PHP Notice:  Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>clickky</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in /wordpress/wp-includes/functions.php on line 6121
[20-May-2025 02:03:17 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function create_function() in /wordpress/wp-content/plugins/color-widgets/colorwidgets.php:139
Stack trace:
#0 /wordpress/wp-admin/includes/plugin.php(2387): include_once()
#1 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('color-widgets/c...')
#2 /internal/eval.php(20): activate_plugin('color-widgets/c...')
#3 {main}
  thrown in /wordpress/wp-content/plugins/color-widgets/colorwidgets.php on line 139
[20-May-2025 02:03:26 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function create_function() in /wordpress/wp-content/plugins/color-widgets/colorwidgets.php:139
Stack trace:
#0 /wordpress/wp-admin/includes/plugin.php(2387): include_once()
#1 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('color-widgets/c...')
#2 /internal/eval.php(20): activate_plugin('color-widgets/c...')
#3 {main}
  thrown in /wordpress/wp-content/plugins/color-widgets/colorwidgets.php on line 139
[20-May-2025 02:03:33 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function create_function() in /wordpress/wp-content/plugins/color-widgets/colorwidgets.php:139
Stack trace:
#0 /wordpress/wp-admin/includes/plugin.php(2387): include_once()
#1 /wordpress/wp-admin/includes/plugin.php(673): plugin_sandbox_scrape('color-widgets/c...')
#2 /internal/eval.php(20): activate_plugin('color-widgets/c...')
#3 {main}
  thrown in /wordpress/wp-content/plugins/color-widgets/colorwidgets.php on line 139

    at Object.onBind (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async V (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:64:10)
    at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {
  [cause]: Error: Error when executing the blueprint step #5 ({"step":"installPlugin","pluginData":{"resource":"wordpress.org/plugins","slug":"context-sharing"},"options":{"activate":true}}) : Could not download "https://downloads.wordpress.org/plugin/context-sharing.latest-stable.zip".
  				Check if the URL is correct and the server is reachable.
  				If it is reachable, the server might be blocking the request.
  				Check the browser console and network tabs for more information.
  
  				## Does the console show the error "No 'Access-Control-Allow-Origin' header"?
  
  				This means the server that hosts your file does not allow requests from other sites
  				(cross-origin requests, or CORS).	You need to move the asset to a server that allows
  				cross-origin file downloads. Learn more about CORS at
  				https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS.
  
  				If your file is on GitHub, load it from "raw.githubusercontent.com".
  				Here's how to do that:
  
  				1. Start with the original GitHub URL of the file. For example:
  				https://github.com/username/repository/blob/branch/filename.
  				2. Replace "github.com" with "raw.githubusercontent.com".
  				3. Remove the "/blob/" part of the URL.
  
  				The resulting URL should look like this:
  				https://raw.githubusercontent.com/username/repository/branch/filename
  
  				Error:
  				Error: Could not download "https://downloads.wordpress.org/plugin/context-sharing.latest-stable.zip"
      at Object.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12449:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async ms (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12552:3)
      at async Object.onBind (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:227:48)
      at async V (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:64:10)
      at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {
    [cause]: Error: Could not download "https://downloads.wordpress.org/plugin/context-sharing.latest-stable.zip".
    				Check if the URL is correct and the server is reachable.
    				If it is reachable, the server might be blocking the request.
    				Check the browser console and network tabs for more information.
    
    				## Does the console show the error "No 'Access-Control-Allow-Origin' header"?
    
    				This means the server that hosts your file does not allow requests from other sites
    				(cross-origin requests, or CORS).	You need to move the asset to a server that allows
    				cross-origin file downloads. Learn more about CORS at
    				https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS.
    
    				If your file is on GitHub, load it from "raw.githubusercontent.com".
    				Here's how to do that:
    
    				1. Start with the original GitHub URL of the file. For example:
    				https://github.com/username/repository/blob/branch/filename.
    				2. Replace "github.com" with "raw.githubusercontent.com".
    				3. Remove the "/blob/" part of the URL.
    
    				The resulting URL should look like this:
    				https://raw.githubusercontent.com/username/repository/branch/filename
    
    				Error:
    				Error: Could not download "https://downloads.wordpress.org/plugin/context-sharing.latest-stable.zip"
        at Ct.resolve (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:1472:13)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async _.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@php-wasm/util/index.js:45:14)
  }
}

Node.js v23.11.0
