file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237
        throw new Error(y, { cause: u });
              ^

Error: [14-May-2025 15:51:15 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function wp_generate_attachment_metadata() in /wordpress/wp-content/plugins/mycred/includes/mycred-functions.php:4224
Stack trace:
#0 /wordpress/wp-content/plugins/mycred/includes/mycred-setup.php(72): mycred_upload_default_point_image()
#1 /wordpress/wp-content/plugins/mycred/includes/mycred-setup.php(33): myCRED_Setup->setup_default_point_type()
#2 /wordpress/wp-content/plugins/mycred/includes/mycred-install.php(94): myCRED_Setup->load()
#3 /wordpress/wp-content/plugins/mycred/includes/mycred-functions.php(3510): myCRED_Install::activate()
#4 /wordpress/wp-includes/class-wp-hook.php(324): mycred_plugin_activation(false)
#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_mycred...', false)
#8 /internal/eval.php(20): activate_plugin('mycred/mycred.p...')
#9 {main}
  thrown in /wordpress/wp-content/plugins/mycred/includes/mycred-functions.php on line 4224
[14-May-2025 15:51:27 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function wp_generate_attachment_metadata() in /wordpress/wp-content/plugins/mycred/includes/mycred-functions.php:4224
Stack trace:
#0 /wordpress/wp-content/plugins/mycred/includes/mycred-setup.php(72): mycred_upload_default_point_image()
#1 /wordpress/wp-content/plugins/mycred/includes/mycred-setup.php(33): myCRED_Setup->setup_default_point_type()
#2 /wordpress/wp-content/plugins/mycred/includes/mycred-install.php(94): myCRED_Setup->load()
#3 /wordpress/wp-content/plugins/mycred/includes/mycred-functions.php(3510): myCRED_Install::activate()
#4 /wordpress/wp-includes/class-wp-hook.php(324): mycred_plugin_activation(false)
#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_mycred...', false)
#8 /internal/eval.php(20): activate_plugin('mycred/mycred.p...')
#9 {main}
  thrown in /wordpress/wp-content/plugins/mycred/includes/mycred-functions.php on line 4224
[14-May-2025 15:51:40 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function wp_generate_attachment_metadata() in /wordpress/wp-content/plugins/mycred/includes/mycred-functions.php:4224
Stack trace:
#0 /wordpress/wp-content/plugins/mycred/includes/mycred-setup.php(72): mycred_upload_default_point_image()
#1 /wordpress/wp-content/plugins/mycred/includes/mycred-setup.php(33): myCRED_Setup->setup_default_point_type()
#2 /wordpress/wp-content/plugins/mycred/includes/mycred-install.php(94): myCRED_Setup->load()
#3 /wordpress/wp-content/plugins/mycred/includes/mycred-functions.php(3510): myCRED_Install::activate()
#4 /wordpress/wp-includes/class-wp-hook.php(324): mycred_plugin_activation(false)
#5 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#6 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_mycred...', false)
#8 /internal/eval.php(20): activate_plugin('mycred/mycred.p...')
#9 {main}
  thrown in /wordpress/wp-content/plugins/mycred/includes/mycred-functions.php on line 4224
[14-May-2025 15:53:07 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>create table wp_wpjf3_mr_access_keys ( id int auto_increment primary key, name varchar(100), access_key varchar(20), email varchar(100), created_at datetime not null default '0000-00-00 00:00:00', active int(1) not null default 1 )</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown create type: table.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-content/plugins/jf3-maintenance-mode/wpjf3_maintenance_redirect.php(60): WP_SQLite_DB->query('create table wp...')
#2 /wordpress/wp-includes/class-wp-hook.php(324): wpjf3_maintenance_redirect->init(false)
#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_jf3-ma...', false)
#6 /internal/eval.php(20): activate_plugin('jf3-maintenance...')
#7 {main}</pre>
 for query create table wp_wpjf3_mr_access_keys ( id int auto_increment primary key, name varchar(100), access_key varchar(20), email varchar(100), created_at datetime not null default '0000-00-00 00:00:00', active int(1) not null default 1 ) made by activate_plugin, do_action('activate_jf3-maintenance-mode/wpjf3_maintenance_redirect.php'), WP_Hook->do_action, WP_Hook->apply_filters, wpjf3_maintenance_redirect->init, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[14-May-2025 15:53:07 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>create table wp_wpjf3_mr_unrestricted_ips ( id int auto_increment primary key, name varchar(100), ip_address varchar(20), created_at datetime not null default '0000-00-00 00:00:00', active int(1) not null default 1 )</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown create type: table.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-content/plugins/jf3-maintenance-mode/wpjf3_maintenance_redirect.php(67): WP_SQLite_DB->query('create table wp...')
#2 /wordpress/wp-includes/class-wp-hook.php(324): wpjf3_maintenance_redirect->init(false)
#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_jf3-ma...', false)
#6 /internal/eval.php(20): activate_plugin('jf3-maintenance...')
#7 {main}</pre>
 for query create table wp_wpjf3_mr_unrestricted_ips ( id int auto_increment primary key, name varchar(100), ip_address varchar(20), created_at datetime not null default '0000-00-00 00:00:00', active int(1) not null default 1 ) made by activate_plugin, do_action('activate_jf3-maintenance-mode/wpjf3_maintenance_redirect.php'), WP_Hook->do_action, WP_Hook->apply_filters, wpjf3_maintenance_redirect->init, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[14-May-2025 15:53:16 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>create table wp_wpjf3_mr_access_keys ( id int auto_increment primary key, name varchar(100), access_key varchar(20), email varchar(100), created_at datetime not null default '0000-00-00 00:00:00', active int(1) not null default 1 )</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown create type: table.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-content/plugins/jf3-maintenance-mode/wpjf3_maintenance_redirect.php(60): WP_SQLite_DB->query('create table wp...')
#2 /wordpress/wp-includes/class-wp-hook.php(324): wpjf3_maintenance_redirect->init(false)
#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_jf3-ma...', false)
#6 /internal/eval.php(20): activate_plugin('jf3-maintenance...')
#7 {main}</pre>
 for query create table wp_wpjf3_mr_access_keys ( id int auto_increment primary key, name varchar(100), access_key varchar(20), email varchar(100), created_at datetime not null default '0000-00-00 00:00:00', active int(1) not null default 1 ) made by activate_plugin, do_action('activate_jf3-maintenance-mode/wpjf3_maintenance_redirect.php'), WP_Hook->do_action, WP_Hook->apply_filters, wpjf3_maintenance_redirect->init, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[14-May-2025 15:53:16 UTC] WordPress database error <div style="clear:both">&nbsp;</div>
<div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;">
<p>MySQL query:</p>
<p>create table wp_wpjf3_mr_unrestricted_ips ( id int auto_increment primary key, name varchar(100), ip_address varchar(20), created_at datetime not null default '0000-00-00 00:00:00', active int(1) not null default 1 )</p>
<p>Queries made or created this session were:</p>
<ol>
<li>Executing: BEGIN | (no parameters)</li>
<li>Executing: ROLLBACK | (no parameters)</li>
</ol>
</div>
<div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;">
Error occurred at line 4117 in Function <code>handle_error</code>. Error message was: Unknown create type: table.
</div>
<p>Backtrace:</p>
<pre>#0 /internal/shared/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message()
#1 /wordpress/wp-content/plugins/jf3-maintenance-mode/wpjf3_maintenance_redirect.php(67): WP_SQLite_DB->query('create table wp...')
#2 /wordpress/wp-includes/class-wp-hook.php(324): wpjf3_maintenance_redirect->init(false)
#3 /wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#4 /wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /wordpress/wp-admin/includes/plugin.php(703): do_action('activate_jf3-ma...', false)
#6 /internal/eval.php(20): activate_plugin('jf3-maintenance...')
#7 {main}</pre>
 for query create table wp_wpjf3_mr_unrestricted_ips ( id int auto_increment primary key, name varchar(100), ip_address varchar(20), created_at datetime not null default '0000-00-00 00:00:00', active int(1) not null default 1 ) made by activate_plugin, do_action('activate_jf3-maintenance-mode/wpjf3_maintenance_redirect.php'), WP_Hook->do_action, WP_Hook->apply_filters, wpjf3_maintenance_redirect->init, WP_SQLite_DB->query, WP_SQLite_DB->print_error
[14-May-2025 15:54:22 UTC] PHP Fatal error:  Cannot redeclare add_term_meta() (previously declared in /wordpress/wp-includes/taxonomy.php:1401) in /wordpress/wp-content/plugins/jam-taxonomy-image/lib/taxonomy-metadata.php on line 69

    at Object.onBind (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:237:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async V (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:64:10)
    at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {
  [cause]: Error: Error when executing the blueprint step #5 ({"step":"installPlugin","pluginData":{"resource":"wordpress.org/plugins","slug":"jam-taxonomy-image"},"options":{"activate":true}}) : PHP.run() failed with exit code 255 and the following output: 
      at Object.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12449:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async ms (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12552:3)
      ... 2 lines matching cause stack trace ...
      at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {
    [cause]: PHPExecutionFailureError: PHP.run() failed with exit code 255 and the following output: 
        at PHP.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@php-wasm/universal/index.js:987:19)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async wr (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:33:39)
        at async Object.gt [as installPlugin] (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:974:42)
        at async g (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12517:30)
        at async Object.run (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12446:23)
        at async ms (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/blueprints/index.js:12552:3)
        at async Object.onBind (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:227:48)
        at async V (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/index.js:64:10)
        at async ja (file:///home/runner/work/playground-tester/playground-tester/node_modules/@wp-playground/cli/cli.js:8161:12) {
      response: PHPResponse {
        httpStatusCode: 500,
        headers: {
          'x-powered-by': [ 'PHP/8.0.30-dev' ],
          'content-type': [ 'text/html; charset=UTF-8' ]
        },
        bytes: Uint8Array(0) [],
        exitCode: 255,
        errors: ''
      },
      source: 'request'
    }
  }
}

Node.js v23.11.0
